In [1]:
# Copied from main file
from getpass import getpass
import io
import pandas as pd
import msoffcrypto

file_path =r"C:\Users\danam\OneDrive\Desktop\Bachelorprojekt\Tidligere excel bearbejdninger\Alle Giftlinjen 2018-2022 (anonym) Aldersfordelt - Kopi.xlsx"
password = getpass("Enter Excel password: ")

decrypted = io.BytesIO()
with open(file_path, "rb") as f:
    office = msoffcrypto.OfficeFile(f)
    office.load_key(password=password)
    office.decrypt(decrypted)

# Move back to the start of the stream before reading
decrypted.seek(0)

# Specify the two sheets you want to load
sheet_names = ["Alder<70", "Alder>70"] 
# List the columns you want
keep = [
    '[Indtag tid(gift1)]',
    '[Mand(Patient data)]',
    '[Alder (år)(Patient data)]',
    '[Ingen risiko(Risiko)]',
    '[generisk navn(gift1)]',
    '[navn(gift1)]',
    '[substans type(gift1)]',
    '[Enhed(gift1)]',
    '[Styrke(gift1)]',
    '[antal(gift1)]',
    '[dosis(gift1)]',
    '[generisk navn(gift2)]',
    '[navn(gift2)]',
    '[substans type(gift2)]',
    '[Enhed(gift2)]',
    '[Styrke(gift2)]',
    '[antal(gift2)]',
    '[dosis(gift2)]',
    '[generisk navn(gift3)]',
    '[navn(gift3)]',
    '[substans type(gift3)]',
    '[Enhed(gift3)]',
    '[Styrke(gift3)]',
    '[antal(gift3)]',
    '[dosis(gift3)]',
    '[generisk navn(gift4)]',
    '[navn(gift4)]',
    '[substans type(gift4)]',
    '[Enhed(gift4)]',
    '[Styrke(gift4)]',
    '[antal(gift4)]',
    '[dosis(gift4)]',  
    '[generisk navn(gift5)]',
    '[navn(gift5)]',
    '[substans type(gift5)]',
    '[Enhed(gift5)]',
    '[Styrke(gift5)]',
    '[antal(gift5)]',
    '[dosis(gift5)]',
    '[generisk navn(gift6)]',
    '[navn(gift6)]',
    '[substans type(gift6)]',
    '[Enhed(gift6)]',
    '[Styrke(gift6)]',
    '[antal(gift6)]',
    '[Dosis(gift6)]',
    '[generisk navn(gift7)]',
    '[navn(gift7)]',
    '[substans type(gift7)]',
    '[Enhed(gift7)]',
    '[Styrke(gift7)]',
    '[antal(gift7)]',
    '[Dosis(gift7)]',
    '[generisk navn(gift8)]',
    '[navn(gift8)]',
    '[substans type(gift8)]',
    '[Enhed(gift8)]',
    '[Styrke(gift8)]',
    '[antal(gift8)]',
    '[Dosis(gift8)]',
    '[generisk navn(gift9)]',
    '[navn(gift9)]',
    '[substans type(gift9)]',
    '[Enhed(gift9)]',
    '[Styrke(gift9)]',
    '[antal(gift9)]',
    '[Dosis(gift9)]',
    '[generisk navn(gift10)]',
    '[navn(gift10)]',
    '[substans type(gift10)]',
    '[Enhed(gift10)]',
    '[Styrke(gift10)]',
    '[antal(gift10)]',
    '[Dosis(gift10)]',
    '[generisk navn(gift11)]',
    '[navn(gift11)]',
    '[substans type(gift11)]',
    '[Enhed(gift11)]',
    '[Styrke(gift11)]',
    '[antal(gift11)]',
    '[Dosis(gift11)]',
    '[generisk navn(gift12)]',
    '[navn(gift12)]',
    '[substans type(gift12)]',
    '[Enhed(gift12)]',
    '[Styrke(gift12)]',
    '[antal(gift12)]',
    '[Dosis(gift12)]',
    '[generisk navn(gift13)]',
    '[navn(gift13)]',
    '[substans type(gift13)]',
    '[Enhed(gift13)]',
    '[Styrke(gift13)]',
    '[antal(gift13)]',
    '[Dosis(gift13)]',
    '[generisk navn(gift14)]',
    '[navn(gift14)]',
    '[substans type(gift14)]',
    '[Enhed(gift14)]',
    '[Styrke(gift14)]',
    '[antal(gift14)]',
    '[Dosis(gift14)]',
    '[generisk navn(gift15)]',
    '[navn(gift15)]',
    '[substans type(gift15)]',
    '[Enhed(gift15)]',
    '[Styrke(gift15)]',
    '[antal(gift15)]',
    '[Dosis(gift15)]',
    '[Ingen(Anbefalet obs)]',
    '[Akut forgiftning(Forespørgselsart)]',
    '[Søg Hospital(hospital)]',
    '[Borger(Spørger1)]',
    '[Søg postnummer(postalcode)]',
    '[Søg By(postalcode)]',
    '[Råd(Tekst)]',
    '[Today(Oprettelse)]',
    '[Anamnese(Tekst)]',
    '[Psykiatriske sygdomme(Komorbiditet)]',
    '[Ulykke/uheld(Årsag)]',
    '[Leg(Årsag)]',
    '[Suicidal/Affekt(Årsag)]',
    '[Misbrug(Årsag)]',
    '[Forveksling(Årsag)]',
    '[Omhældning(Årsag)]',
    '[Fejldosering(Årsag)]',
    '[Levnedsmiddel(Årsag)]',
]

dfs = pd.read_excel(
    decrypted,
    sheet_name=sheet_names,
    usecols=keep
)

# All column names are now lowercase:
for sheet in sheet_names:
    dfs[sheet].columns = [c.lower() for c in dfs[sheet].columns]


young_filtered = dfs[sheet_names[0]]
old_filtered = dfs[sheet_names[1]]

## Duplicate-detection rule used by `find_duplicates`  
*(clique-based implementation – 2024-06, “multi-poison” revision)*  
---

### 1 Hard-key compatibility  
Two rows can **only** belong to the same potential case if they satisfy **all**
of the conditions below.

| Condition | Columns involved | Requirement |
|-----------|-----------------|-------------|
| Demographics | `[søg postnummer(postalcode)]`   `[mand(patient data)]`   `[alder (år)(patient data)]` | must be **identical** |
| Poison names – 30 raw columns | `[generisk navn(gift1)] … [generisk navn(gift15)]`<br>`[navn(gift1)] … [navn(gift15)]` | see “Poison-set rule” |

Poison-set rule  
1. For every row build  
   `POISON_SET(row)  = { all non-missing strings found in the 30 poison columns }`.  
   (Within one row duplicates and order are ignored.)  
2. Let A and B be two rows with poison sets `S_A` and `S_B`.  
   A and B pass the hard-key test iff  

     `S_A ⊆ S_B`  or  `S_B ⊆ S_A`  

   — i.e. the *smaller* set must be a subset of the larger; neither row may
   contain a poison name that the other row explicitly does **not** list.

Only rows that fulfil both the demographic equality and the poison-set
subset rule enter the subsequent stages.

---

### 2 Temporal proximity  
Inside every hard-key compatible group the rows are sorted by enquiry date  
`[today(oprettelse)]`.  
Whenever the absolute gap between two consecutive rows exceeds **4 days**
(`MAX_GAP = 4`) a new **time segment** starts.  
All later duplicate checks are performed **independently** inside each
segment.

---

### 3 Clique-based cluster formation inside one time segment  
Within one segment we build **duplicate clusters** so that *every pair of
rows* inside the cluster is mutually compatible.

1. **Candidate ordering**  
   Rows are processed in descending order of the count of non-missing values in
   the eight **Årsag** (“cause”) columns  
   `[ulykke/uheld(årsag)]`, …, `[levnedsmiddel(årsag)]`.

2. **Attempt to join an existing cluster**  
   For every existing cluster, the candidate row is compared to **all rows
   already present**.  It can join the first cluster where it is compatible
   with everybody (rules 3 a–3 c).  If no such cluster exists, a **new**
   cluster is started with that single row.

3. **Post-processing**  
   After all rows have been examined, clusters that contain fewer than two rows
   are discarded.

Because a candidate must match **every** member of a cluster, the resulting
clusters are cliques: no transitive “bridging” via partially filled columns is
possible.

#### 3 a Poison-set compatibility (new)  
Let `U_cluster` be the union of `POISON_SET` for all rows already in the
cluster.  
The candidate row C with set `S_C` is acceptable *iff* `S_C ⊆ U_cluster`
(C may omit substances but may not add new ones).

#### 3 b Semi-hard-key columns (unchanged)  
Four columns must agree pair-wise inside a cluster (symmetric rule, NaN acts
as a wildcard):

| Semi-hard-key column              |
|-----------------------------------|
| `[styrke(gift1)]`                 |
| `[antal(gift1)]`                  |
| `[dosis(gift1)]`                  |
| `[søg hospital(hospital)]`        |

Mismatch ⇔ both rows hold non-missing values **and** the values differ.

#### 3 c Årsag (“cause”) columns (unchanged)  
Eight cause columns use the existing *asymmetric* comparison rule  
(NaN in the reference row forbids the candidate from supplying a value that
disagrees).

---

### 4 Result returned by `find_duplicates`  
Rows that belong to any duplicate cluster are returned with two additional
columns:

| Column         | Type | Meaning                                   |
|----------------|------|-------------------------------------------|
| `is_duplicate` | bool | always `True` for these rows              |
| `dup_case_id`  | int  | Consecutive identifier of the cluster     |

Rows that are not part of any cluster are omitted from the returned
DataFrame.

In [2]:
# ================================================================
#  Duplicate detection – *clique-based* cluster logic
#              multi-poison (“subset”) revision 2024-06
# ================================================================
def find_duplicates(df):
    """
    Duplicate detection using the specification
        “Duplicate-detection rule … (multi-poison revision)”.

    Main differences to the previous version
    ----------------------------------------
    1.  30 poison-name columns are treated as ONE *unordered* set.
        For every row we build
            POISON_SET(row) = { all non-missing strings in those 30 cols }.

        Two rows are poison-compatible  ⇔
            POISON_SET(A) ⊆ POISON_SET(B)  or  POISON_SET(B) ⊆ POISON_SET(A)
        (⇒ the smaller set is a subset of the larger).

    2.  The demographic fields alone form the primary grouping key
            [søg postnummer(postalcode)],
            [mand(patient data)],
            [alder (år)(patient data)]
        – the poison subset rule is enforced later while the clusters
        are built.

    All other steps (temporal segmentation, semi-hard columns, cause
    columns, result formatting) are unchanged.

    The function returns **only** the rows that belong to a duplicate
    cluster and appends the columns

        is_duplicate : bool   (always True)
        dup_case_id  : int    (consecutive identifier)

    A short size report is printed at the end.
    """
    # ----------------------------------------------------------------
    # imports (local keeps namespace clean for caller)
    # ----------------------------------------------------------------
    import numpy as np
    import pandas as pd

    # ----------------------------------------------------------------
    # configuration
    # ----------------------------------------------------------------
    DATE_COL   = '[today(oprettelse)]'

    # ---- grouping (demographic) hard key ---------------------------
    KEY_COLS   = [
        '[søg postnummer(postalcode)]',
        '[mand(patient data)]',
        '[alder (år)(patient data)]',
    ]

    # ---- poison columns (30) ---------------------------------------
    POISON_GENERIC = [f'[generisk navn(gift{i})]' for i in range(1, 16)]
    POISON_BRAND   = [f'[navn(gift{i})]'           for i in range(1, 16)]
    POISON_COLS    = POISON_GENERIC + POISON_BRAND       # length 30

    # ---- semi-hard columns (unchanged) -----------------------------
    SEMI_COLS  = [
        '[styrke(gift1)]',
        '[antal(gift1)]',
        '[dosis(gift1)]',
        '[søg hospital(hospital)]',
    ]

    # ---- cause columns (unchanged) ---------------------------------
    CAUSE_COLS = [
        '[ulykke/uheld(årsag)]',
        '[leg(årsag)]',
        '[suicidal/affekt(årsag)]',
        '[misbrug(årsag)]',
        '[forveksling(årsag)]',
        '[omhældning(årsag)]',
        '[fejldosering(årsag)]',
        '[levnedsmiddel(årsag)]',
    ]

    MAX_GAP = 4          # maximum days between consecutive rows

    # ----------------------------------------------------------------
    # helper: turn the 30 poison columns into a frozenset (lower-cased,
    #         stripped, empty strings ignored)
    # ----------------------------------------------------------------
    def _row_to_poison_set(row_vals):
        out = [
            (v.strip().lower() if isinstance(v, str) else str(v).strip().lower())
            for v in row_vals
            if pd.notna(v) and str(v).strip() != ''
        ]
        return frozenset(out)

    # ----------------------------------------------------------------
    # helper – build clusters inside ONE time-segment
    # ----------------------------------------------------------------
    def _clusters_in_segment(seg: pd.DataFrame):
        """
        Returns a list of dataframes, each representing a duplicate
        cluster (at least 2 rows), where *every* pair of rows is mutually
        compatible according to

            • poison-set subset rule        (new)
            • semi-hard column rule         (symmetric)
            • cause column rule             (asymmetric, unchanged)
        """
        n = len(seg)
        if n < 2:
            return []

        # quick NumPy views on cause / semi columns -------------------
        cause_dat = seg[CAUSE_COLS].to_numpy(copy=False)
        cause_nn  = ~pd.isna(cause_dat)

        semi_dat  = seg[SEMI_COLS].to_numpy(copy=False)
        semi_nn   = ~pd.isna(semi_dat)

        # poison sets as a Python list (object dtype – small clusters)
        p_sets = seg['__poison_set'].tolist()

        # candidate order: many non-missing CAUSE cells first ----------
        order = np.argsort(-cause_nn.sum(axis=1))
        clusters = []                 # list[ list[int] ]  (row indices)

        for pos in order:             # candidate row (0 … n-1)
            placed = False
            for cl in clusters:       # try to join an existing cluster
                c_idx = np.asarray(cl)          # rows already in cluster

                # --------- CAUSE mismatches (asymmetric rule) --------
                cand_cause_nn   = cause_nn [pos]
                cand_cause_vals = cause_dat[pos]
                ref_cause_nn    = cause_nn [c_idx]
                ref_cause_vals  = cause_dat[c_idx]

                cond1 = cand_cause_nn & (~ref_cause_nn)                # value vs NaN
                cond2 = cand_cause_nn & ref_cause_nn & \
                        (cand_cause_vals != ref_cause_vals)
                mism_cause = (cond1 | cond2).any()

                # --------- SEMI-hard mismatches (symmetric rule) -----
                cand_semi_nn   = semi_nn [pos]
                cand_semi_vals = semi_dat[pos]
                ref_semi_nn    = semi_nn [c_idx]
                ref_semi_vals  = semi_dat[c_idx]

                mism_semi = (cand_semi_nn & ref_semi_nn & \
                             (cand_semi_vals != ref_semi_vals)).any()

                # --------- POISON-set mismatches (subset rule) -------
                set_c = p_sets[pos]
                mism_poison = False
                for idx in c_idx:
                    s_ref = p_sets[idx]
                    if not (set_c <= s_ref or s_ref <= set_c):
                        mism_poison = True
                        break

                # --------- final decision ---------------------------
                if not (mism_cause or mism_semi or mism_poison):
                    cl.append(pos)
                    placed = True
                    break

            if not placed:            # start a new cluster
                clusters.append([pos])

        # keep only clusters with ≥ 2 rows ----------------------------
        return [seg.iloc[cl].copy() for cl in clusters if len(cl) >= 2]

    # ----------------------------------------------------------------
    # main routine
    # ----------------------------------------------------------------
    df = df.copy()

    # -- create POISON_SET for every row ------------------------------
    df['__poison_set'] = df[POISON_COLS].apply(_row_to_poison_set, axis=1)

    # -- make sure the DATE column is proper datetime -----------------
    df[DATE_COL] = pd.to_datetime(df[DATE_COL], errors='coerce')

    # -- containers for the result markers ----------------------------
    is_dup      = pd.Series(False, index=df.index, dtype=bool)
    dup_case_id = pd.Series(np.nan,  index=df.index, dtype='float')

    # -- iterate over demographic groups ------------------------------
    cid = 0
    for _, grp in df.groupby(KEY_COLS, sort=False, observed=True):
        grp = grp.sort_values(DATE_COL)

        # ---- split by time gap --------------------------------------
        gap          = grp[DATE_COL].diff().dt.days.abs().fillna(MAX_GAP + 1)
        grp['__seg'] = (gap > MAX_GAP).cumsum()

        for _, seg in grp.groupby('__seg', sort=False):
            seg = seg.drop(columns='__seg')
            for cl in _clusters_in_segment(seg):
                idx = cl.index
                is_dup.loc[idx]      = True
                dup_case_id.loc[idx] = cid
                cid += 1

    # ----------------------------------------------------------------
    # assemble final dataframe
    # ----------------------------------------------------------------
    result = df[is_dup].copy()
    if not result.empty:
        result['is_duplicate'] = True
        result['dup_case_id']  = dup_case_id[is_dup].astype('int64')
        # internal helper column not wanted in the output
        result = result.drop(columns='__poison_set')
    else:
        result = pd.DataFrame(
            columns=df.columns.tolist() + ['is_duplicate', 'dup_case_id']
        )

    # ----------------------------------------------------------------
    # short size report
    # ----------------------------------------------------------------
    if result.empty:
        print("No duplicate cases detected.")
    else:
        sz   = result.groupby('dup_case_id').size()      # rows per case
        dist = sz.value_counts().sort_index()

        print("\nDuplicate case size distribution:")
        for rows, n_cases in dist.items():
            print(f"  {rows} rows : {n_cases} case(s)")
        print(f"  total     : {len(sz)} cases\n")

    return result

# --------------------------------------------------------------------
# Example usage
# --------------------------------------------------------------------
old_dups   = find_duplicates(old_filtered)
young_dups = find_duplicates(young_filtered)

Duplicate case size distribution:
  2 rows : 511 case(s)
  3 rows : 71 case(s)
  4 rows : 6 case(s)
  6 rows : 1 case(s)
  total     : 589 cases


Duplicate case size distribution:
  2 rows : 8369 case(s)
  3 rows : 1186 case(s)
  4 rows : 191 case(s)
  5 rows : 50 case(s)
  6 rows : 10 case(s)
  7 rows : 2 case(s)
  8 rows : 1 case(s)
  total     : 9809 cases

In [3]:
print("Young sheet – duplicate cases:", young_dups['dup_case_id'].nunique())
print("Old   sheet – duplicate cases:", old_dups['dup_case_id'].nunique())

Young sheet – duplicate cases: 9809
Old   sheet – duplicate cases: 589

In [4]:
from IPython.display import display, HTML
import pandas as pd

def display_duplicate_cases(df: pd.DataFrame,
                            sheet_label: str,
                            n_cases: int = 20) -> None:
    """
    Show every column of every row that belongs to the first *n_cases*
    duplicate cases found in *df* (use n_cases=None to show them all).

    Parameters
    ----------
    df          The dataframe returned by `find_duplicates`
    sheet_label A title that will be shown above each block
    n_cases     Number of duplicate cases to display (None = all)
    """

    DATE_COL = '[today(oprettelse)]'
    
    if df.empty:
        display(HTML(f"<h3>{sheet_label}: no duplicate cases</h3>"))
        return

    # make sure nothing is truncated in the HTML rendering
    with pd.option_context("display.max_columns", None,
                           "display.max_colwidth", None,
                           "display.width", None):
        case_ids = df["dup_case_id"].drop_duplicates()
        if n_cases is not None:
            case_ids = case_ids.head(n_cases)

        for cid in case_ids:
            subset = (
                df[df["dup_case_id"] == cid]
                .sort_values(DATE_COL)          # chronological inside the case
            )
            display(HTML(
                f"<h4>{sheet_label} – duplicate case {cid} "
                f"({len(subset)} rows)</h4>"
            ))
            display(subset)

# How many cases were detected?
print("Young sheet – duplicate cases:", young_dups["dup_case_id"].nunique())
print("Old   sheet – duplicate cases:", old_dups["dup_case_id"].nunique())

# Show the first 20 duplicate cases from each sheet
display_duplicate_cases(young_dups, "YOUNG SHEET", n_cases=20)
display_duplicate_cases(old_dups,   "OLD SHEET",   n_cases=20)

Young sheet – duplicate cases: 9809
Old   sheet – duplicate cases: 589

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
15,Risiko for livstruende forgiftning,QUETIAPIN FUMARAT,NaN,NaN,2021-12-31 23:30:21,NaN,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]anel0004, 1-1-2022 17:07:17[[ENDINFO]][[STARTTEXT]]Svært forgiftet pt: Telemetri i minimum 12 timer, eller indtil der kun har været lette forgiftningssymptomer i 6 timer. Lette symptomer er mild sedation.[[ENDTEXT]]803246",2022-01-01 16:52:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 17:07:17[[ENDINFO]][[STARTTEXT]]Har for 17,5 time siden indtaget ukendt dosis Quetiapin. Blev indlagt i morges kl 5 med GCS 3, kom på intensiv og blev intuberet. EKGer er taget hv. 2 time alle har været i.a., har ligget i Telemetri. Er nu vågnet op og kun let sløv har det ellers godt. Hvor længe skal han overvåges med Telemetri/EKG, afgørende for hvor han kan overflyttes til.[[ENDTEXT]]803246",7000,Fredericia,46.0,"Quetiapin \1A Farma\""""",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,15
66,NaN,QUETIAPIN FUMARAT,25,70,2022-01-02 11:11:04,1750,NaN,NaN,NaN,ZZMED,NaN,2022-01-02 11:10:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kolding Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 2-1-2022 11:17:22[[ENDINFO]][[STARTTEXT]]2 opkald se sag 386486[[ENDTEXT]]803368",7000,Fredericia,46.0,QUETIAPIN FUMARAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,15

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
23,NaN,PARACETAMOL,NaN,NaN,2022-01-01 18:18:18,NaN,NaN,NaN,NaN,MED,"[[STARTINFO]]rlar0142, 1-1-2022 18:19:15[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 38651[[ENDTEXT]]803267",2022-01-01 18:12:38,Alkohol,NaN,NaN,NaN,NaN,NaN,Ethanol,NaN,NaN,NaN,DIVERSE,Sygehus Viborg,Fortamol,"CODEINPHOSPHATHEMIHYDRAT, PARACETAMOL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7870,Roslev,15.0,Panodil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,21
25,NaN,PARACETAMOL,665,9,2021-12-31 20:00:27,5985,NaN,NaN,NaN,ZZMED,NaN,2022-01-01 18:23:35,Alkohol,NaN,NaN,NaN,NaN,NaN,Ethanol,NaN,NaN,NaN,DIVERSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 19:34:33[[ENDINFO]][[STARTTEXT]]3. opkald fra læge Stewen Viborg sygehus tlf 78449681. Koblet til 386521.[[ENDTEXT]]803271",7870,Roslev,15.0,paracetamol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,21

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
37,Risiko for livstruende forgiftning,Ethanol,NaN,NaN,2022-01-01 19:30:21,NaN,Indlæggelse,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]anel0004, 1-1-2022 21:18:05[[ENDINFO]][[STARTTEXT]]Toxiak dosis depot > 4mg/kg; Alm tbl > 3mg/kg. Symptomer takykardi, svimmelhed, agitation, brystsmerter, mavesmerter, muskelrykninger og tremor, kramper og hypertermi. På hospital til behandling med kul og til symptomatisk behandling med fokus på respiration, cirkulation og kramper.[[ENDTEXT]]803299[[STARTINFO]]rlar0142, 1-1-2022 22:32:34[[ENDINFO]][[STARTTEXT]]2. Opkald Som ovenstående. Har taget solid toksisk dosis og depotformuleret. Fint med kul nu, gentag også om 2 timer atter ½ portion kul. Risiko er overstimulation med muskeluro, agitation evt. kramper. Ved symptomer, da Diazepam 5-10 mg iv, der efter 2 minutter kan gentages til respons. Tæt obs af vitalparametre. Ad EKG : QTc forlængelse ikke helt typisk for Methylphenidat-indtag. Gentag EKG og ved fortsat påvirkning, da telemetri. Ved brystsmerter coronarenzymer. Syrebase-status obs. Ved muskeluro/kramper, da rhabdomyolyse-tal. Obs i 12 timer. Alkohol promille kan dæmpe overstimulation. Velkommen til at kontakte GL ved yderligere. [[ENDTEXT]]803308[[STARTINFO]]rlar0142, 2-1-2022 10:52:16[[ENDINFO]][[STARTTEXT]]3. Opkald. Nu > 12 timer fra indtag. Kan fortsætte obs i psyk. regi. [[ENDTEXT]]803363",2022-01-01 21:00:35,METHYLPHENIDATHYDROCHLORID,NaN,mg,NaN,NaN,NaN,METHYLPHENIDATHYDROCHLORID,27,29,783,ZZMED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 21:18:05[[ENDINFO]][[STARTTEXT]]Opkald fra ambulance der er på vej til kvinde, som skulle have indtaget 100 stk Ritalin ukendt dosis, tid og om det er fast medicin. Ved ikke hvilke symptomer borger har. Hvad skal de være opmærksomme på?[[ENDTEXT]]803299[[STARTINFO]]rlar0142, 1-1-2022 22:32:34[[ENDINFO]][[STARTTEXT]]2. Opkald fra læge Roskilde sygehus 61922550 Modtaget ovenstående, der havde taget 29 tabletter af egne - ikke 100 stk (rettet i giftstof). Endvidere drukket alkohol ( Tilføjes i giftstof). Får ikke anden medicin. Man har givet 1 portion kul nu. Vågen og kan bidrage til anamnese i baggrunden. BT 146/107, p. 88, tp 36,0, rf i.a., EKG med QTc 510 p. 97. Der er taget relevant biokemi samt s-ethanol, s-salicylat, s-pcm. Behandling ? [[ENDTEXT]]803308[[STARTINFO]]rlar0142, 2-1-2022 10:52:16[[ENDINFO]][[STARTTEXT]]3. Opkald fra Roskilde sygehus 61922550 Haft ovenstående til observation natten igennem. Senere EKG med QTc i.a. Upåvirket . Ikke haft behov for Diazepam. Fik de 2 portioner kul. Yderligere nu ? [[ENDTEXT]]803363",4000,Roskilde,44.0,Alkohol,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,54
41,NaN,Ethanol,NaN,NaN,2022-01-01 22:32:43,NaN,NaN,NaN,NaN,DIVERSE,"[[STARTINFO]]rlar0142, 1-1-2022 22:33:12[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 386562[[ENDTEXT]]803307",2022-01-01 22:05:33,METHYLPHENIDATHYDROCHLORID,NaN,NaN,NaN,NaN,NaN,METHYLPHENIDATHYDROCHLORID,NaN,NaN,NaN,ZZMED,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000,Roskilde,44.0,Alkohol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,54

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
42,Uafklaret risiko,LEVOTHYROXINNATRIUM,NaN,NaN,2022-01-01 22:26:13,NaN,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]anel0004, 1-1-2022 22:32:08[[ENDINFO]][[STARTTEXT]]Toxisk dosis Mere end eller lig 2000 mikrogram. Symptomdebut generelt efter 24 timer og varighed er ca 12-48 timer. Symptomer Tremor, varmefornemmelse/svedtendens, hypertermi, Ændret mentaltilstand også agitation, kramper, svær hypertension og arytmier. Kul kan gives op til 4 timer efter indtag. Vurdere om det er en akut eller kronisk forgiftning, obs blandingsforgiftninger feks BZD.[[ENDTEXT]]803310",2022-01-01 22:18:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 22:32:08[[ENDINFO]][[STARTTEXT]]Ambulance på vej til ovenstående. Har fået meldt, borger har indtaget Eltroxin kender ikke dosis eller tid. Borger skulle være agiteret og have låst sig inde. Hvad er toxisk dosis og symptomer?[[ENDTEXT]]803310",2620,Albertslund,25.0,Eltroxin,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,60
52,Risiko for manifest forgiftning,LEVOTHYROXINNATRIUM,50,100,2022-01-01 21:45:53,5000,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]mhen0054, 2-1-2022 01:26:41[[ENDINFO]][[STARTTEXT]]Mild/moderat forgiftning. Indlæggelse/observation afhænger af symptomer. Der kan komme symptomer (milde) med latens op til flere dage. Såfremt kun milde, efter 8 timer, kan observation afsluttes, men med opfølgning op til 2 uger, evt. via EL. [[ENDTEXT]]803331",2022-01-02 01:15:26,NaN,mikrogram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kbh. Amts Sygehus i Glostrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mhen0054, 2-1-2022 01:26:41[[ENDINFO]][[STARTTEXT]]Egen medicin. Får også Sertralin, ikke OD med dette. VKO, fri resp, upåvirket. A-pkt ia. Fået kul.Taget relevante blpr og Ekg. Hvor længe observation ?[[ENDTEXT]]803331",2620,Albertslund,25.0,Eltroxin,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,60

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
66865,Risiko for livstruende forgiftning,Cocain,NaN,10,2021-12-28 03:09:41,NaN,Indlæggelse,NaN,Akut forgiftning,RUS,"[[STARTINFO]]cdit0001, 28-12-2021 04:55:42[[ENDINFO]][[STARTTEXT]]Indtil den er ude tæt overvågning af vitalparametre. Ved tegn på læk da dillaterede pupiller, takykardi, hypertension, stigende tp. BZD, aktiv køling. Symptomatisk behandling.[[ENDTEXT]]802183",2021-12-28 04:35:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hvidovre Hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 28-12-2021 04:55:42[[ENDINFO]][[STARTTEXT]]For 1½ time siden var han hjemme og så bankede det på døren. Han skyndte sig at proppe en pose op i endetarmen med 10 gram kokain. Tog heroin og er kommet ind. Er meget nervøs og sveder. Er i tvivl om hvor godt posen er lukket og har ikke kunne få den ud. Der er kaldt en gas.kir for at hjælpe med proceduren med at forsøge at få den ud. Er overvåget på telemetri. BT normalt.[[ENDTEXT]]802183",2450,København SV,49.0,Kokain,NaN,NaN,NaN,Misbrug,NaN,NaN,NaN,NaN,True,22
65,NaN,Cocain,NaN,NaN,2022-01-02 11:10:52,NaN,NaN,NaN,NaN,RUS,"[[STARTINFO]]rlar0142, 2-1-2022 11:11:22[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 386551[[ENDTEXT]]803365",2022-01-02 11:00:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hvidovre Hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2450,København SV,49.0,Kokain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,22

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
85,Risiko for manifest forgiftning,stærk base,NaN,NaN,2022-01-02 14:18:35,NaN,Skadestue,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]rlar0142, 2-1-2022 14:28:10[[ENDINFO]][[STARTTEXT]]Ætsende base. Risiko for alvorlige og dybe skader på grund af forsæbning. Skyl atter kontinuerligt. Langvarig skylning kan være påkrævet. Skylning skal pågå til der kan måles neutral surhedsgrad i huden - på skadestuen. [[ENDTEXT]]803411[[STARTINFO]]anel0004, 2-1-2022 15:25:43[[ENDINFO]][[STARTTEXT]]Gentager ovenstående.[[ENDTEXT]]803428",2022-01-02 14:21:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 2-1-2022 14:28:10[[ENDINFO]][[STARTTEXT]]Kommet til at spilde nogle dråber over fingre. Kunne med det samme mærke det. Skyllede grundigt med det samme, men lidt fedtet, der hvor han har ramt. Farligt ? [[ENDTEXT]]803411[[STARTINFO]]anel0004, 2-1-2022 15:25:43[[ENDINFO]][[STARTTEXT]]2 opkald fra Frederik på 1813. Har nu skyllet finger en time, har kontaktet 1813, hvad har GL anbefalet af videre plan.[[ENDTEXT]]803428",2300,København S,23.0,Afløbsrens,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,104
91,NaN,stærk base,NaN,NaN,2022-01-02 14:18:06,NaN,NaN,NaN,NaN,KEMI,NaN,2022-01-02 15:13:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 2-1-2022 15:26:12[[ENDINFO]][[STARTTEXT]]2 opkald fra Frederik på 1813. Koblet til 386615.[[ENDTEXT]]803425",2300,København S,23.0,Afløbsrens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,104

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
115,Risiko for manifest forgiftning,QUETIAPIN FUMARAT,25,20,2022-01-02 19:15:54,500,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,"[[STARTINFO]]nhan0003, 2-1-2022 20:23:17[[ENDINFO]][[STARTTEXT]]Skal indlægges til behandling[[ENDTEXT]]803483[[STARTINFO]]nhan0003, 2-1-2022 22:24:34[[ENDINFO]][[STARTTEXT]]2 opkald Sympt 1-6 timer efter tbl indtag. CNS påvirkning, anticholinerge symptomer, EPS Aktivt kul Symptomatisk beh. OBs vitalparametre med fokus på CNS, BT; P, resp, SAT, tp. Kontrol EKG hv 2 time / mindst 6 timer / Telemetri ved QTc > 500 ms Biokemi: elektrolytter, lever- nyretal, Mg, Ca, pcm, salicylat, A.pkt Ved lette / ingen forgiftningssymptomer i mindst 6 timer kan obs afsluttes.[[ENDTEXT]]803516",2022-01-02 20:16:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 2-1-2022 20:23:17[[ENDINFO]][[STARTTEXT]]Taget i suicidal øjemed. Udskrevet i formiddags efter at have taget sovemedicin d 01-01 Ringede til søn umiddelbart efter indtag Vanlig Tbl Quetiapin 25 mg pn x 1[[ENDTEXT]]803483[[STARTINFO]]nhan0003, 2-1-2022 22:24:34[[ENDINFO]][[STARTTEXT]]2 opkald Indlagt på Randers sygehus / acutmodt. Læge Maria Tlf: 78420320 Udskrevet kl 12.25 efter psyk tilsyn. Er vågen og klar, ked af det. Medvirker ikke til anamnese. BT: 155/ P: 89 Afebril. Opkastning x 1 EKG: QTc: 406 ms / frekvens: 83[[ENDTEXT]]803516",8920,Randers NV,49.0,QUETIAPIN FUMARAT,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,56
129,NaN,QUETIAPIN FUMARAT,NaN,NaN,2022-01-02 22:19:13,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-02 22:09:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Randers Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 2-1-2022 22:19:26[[ENDINFO]][[STARTTEXT]]2 opkald se sag 386647[[ENDTEXT]]803515",8920,Randers NV,49.0,QUETIAPIN FUMARAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,56

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
134,Risiko for manifest forgiftning,"ACETYLSALICYLSYRE, CODEINPHOSPHATHEMIHYDRAT, Magne",500,40,2022-01-02 17:00:48,20000,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]mann0002, 2-1-2022 23:48:44[[ENDINFO]][[STARTTEXT]]Pt har indtaget 260 mg/kg, vejledende vil dette give en moderat forgiftning, MEN forgiftningen skal vurderes samlet udfra syrebase, symptomer og se-salicylat. Der kan ses Tinitus kvalme, opkastning, sløvhed, kramper, metabolisk acidose, koagulationsforstyrrelser. Obs at hver tbl indeholder kodein 9,6 mg, indtaget svarer til et indtag på 384 mg kodein. Se-salicylat skal tages nu og hver 2. time til faldende niveau > 1,5 mmol/l. Pt skal have en dobbeltportion kul. Forebyggende gives K-vitamin 10 mg iv. Evt videre eliminering vha alkalinisering og hæmodialyse, dette udfra se-salicylat. Spørger guides frem til Instruks på Acetylsalicylsyre. Ring meget igen ang videre behandling. Symptomatisk behandling. [[ENDTEXT]]803529[[STARTINFO]]mann0002, 3-1-2022 00:39:43[[ENDINFO]][[STARTTEXT]]2. opkald. Hurtigt inf. som ovenstående. Spørger også guidet frem til instruks. Alkalinisering af urin ska påbegyndes. Se-salicylat hver 2. time til < 1,5 mmol/l. Øvrige blodprøver i flg instruks. Konf. m. sboe0017 [[ENDTEXT]]803535",2022-01-02 23:23:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Herlev,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 2-1-2022 23:48:44[[ENDINFO]][[STARTTEXT]]Indtaget for 6 1/2 time siden. Pt er træt, har tinnitus. Oplyser at han hjemme har haft en mørk, måske kaffegrumslignende opkastning. [[ENDTEXT]]803529[[STARTINFO]]mann0002, 3-1-2022 00:39:43[[ENDINFO]][[STARTTEXT]]2. opkald. Spørger har netop overtaget pt. Der er givet kul og Konakion. Se-salicylat 4,3 mmol/l. Se-ka og se.Na ia. Leucocytter 19,5, CRP ia, pt afebril[[ENDTEXT]]803535",2860,Søborg,18.0,"Kodimagnyl Ikke-stoppende \DAK\""""",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,163
135,NaN,"ACETYLSALICYLSYRE, CODEINPHOSPHATHEMIHYDRAT, Magne",NaN,NaN,2022-01-03 00:40:13,NaN,NaN,NaN,NaN,MED,NaN,2022-01-03 00:19:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Herlev,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 3-1-2022 00:40:30[[ENDINFO]][[STARTTEXT]]Reg. af 2. opkald på sag nr 386667[[ENDTEXT]]803534",2860,Søborg,18.0,"Kodimagnyl Ikke-stoppende \DAK\""""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,163

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
138,Uafklaret risiko,Cocain,NaN,NaN,2021-12-31 02:10:55,NaN,Skadestue,NaN,Akut forgiftning,RUS,"[[STARTINFO]]mann0002, 3-1-2022 02:13:33[[ENDINFO]][[STARTTEXT]]Skal ses af læge.[[ENDTEXT]]803531[[STARTINFO]]sgre0034, 3-1-2022 17:18:47[[ENDINFO]][[STARTTEXT]]Symptomer på kronisk misbrug af lattergas ses typisk ved at pt får neurologiske symptomer, feks i form af følesforstyrrelser. Skal sættes i behandling B12 vitamin, startes med 1 mg im, herefter feks. Betolvex og Folsyre. Evt konf. neurologisk afd. Observation afhængig af symptomer. Kan evt følges op af egen læge, hvis det vurderes at pt kan udskrives i dag![[ENDTEXT]]803705",2022-01-03 01:49:04,Lattergas,NaN,NaN,NaN,NaN,NaN,Dinitrogenoxid 100%,NaN,NaN,NaN,RUS,NaN,Alkohol,Ethanol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DIVERSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 3-1-2022 02:13:33[[ENDINFO]][[STARTTEXT]]Har d. 31/12/21 indtaget alkohol, cocain og lattergas. I døgnet efter hjertebanken, i dag episoder med panikangst og huden i den ene siden af ansigtet er følelsesløs. Er ikke hyppig bruger af lattergas, har prøvet det 4-5 x tidligere, med lange intervaller. [[ENDTEXT]]803531[[STARTINFO]]sgre0034, 3-1-2022 17:18:47[[ENDINFO]][[STARTTEXT]]2. opkald fra BBH akutlæge Andre 30527293: Pt nu indlagt. Har et misbrug af lattergas, angiver at have tage høje doser 12-13 gange tidligere, måske mere! Har ikke indtaget noget siden nytårsaften Har føleforstyrrelser, men er ikke udtalte, og følelsen af angstprovokeret åndenød. Har ikke neuropati[[ENDTEXT]]803705",9999,Ukendt,22.0,Kokain,NaN,NaN,NaN,Misbrug,NaN,NaN,NaN,NaN,True,167
181,NaN,Dinitrogenoxid 100%,NaN,NaN,2022-01-03 17:12:14,NaN,NaN,NaN,NaN,RUS,NaN,2022-01-03 17:03:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bispebjerg Hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 17:18:58[[ENDINFO]][[STARTTEXT]]koblet 386668[[ENDTEXT]]803702",9999,Ukendt,22.0,Lattergas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,167

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
140,Risiko for begrænset forgiftning,PROPRANOLOLHYDROCHLORID,10,14,2022-01-02 21:18:04,140,Psykiatrisk afdeling,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]tvan0009, 3-1-2022 08:27:41[[ENDINFO]][[STARTTEXT]]ikke toksisk indtag, anbefaler at pt får målt P og BT via egen læge eller skadestue[[ENDTEXT]]803546[[STARTINFO]]tvan0009, 3-1-2022 11:41:30[[ENDINFO]][[STARTTEXT]]ingen grund til yderligere tiltag[[ENDTEXT]]803625",2022-01-03 08:17:51,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 3-1-2022 08:27:41[[ENDINFO]][[STARTTEXT]]indtaget ovenstående i går aftes har fået det ordineret mod eksamensangst[[ENDTEXT]]803546[[STARTINFO]]tvan0009, 3-1-2022 11:41:30[[ENDINFO]][[STARTTEXT]]2 opkald se på akutmodtagelsen P BT normalt tager afstand fra hændelsen. der er etableret kontakt til psyk[[ENDTEXT]]803625",4300,Holbæk,21.0,PROPRANOLOLHYDROCHLORID,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,169
154,NaN,PROPRANOLOLHYDROCHLORID,NaN,NaN,2022-01-02 23:30:00,NaN,NaN,NaN,Akut forgiftning,ZZMED,NaN,2022-01-03 11:38:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sygehus Vestsjælland, Holbæk",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 3-1-2022 11:42:41[[ENDINFO]][[STARTTEXT]]se koblede sag[[ENDTEXT]]803624",4300,Holbæk,21.0,PROPRANOLOLHYDROCHLORID,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,169

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
150,NaN,Blandede ikke chlorerede kulbrinter,NaN,NaN,2022-01-03 11:14:51,NaN,NaN,NaN,NaN,KEMI,NaN,2022-01-03 11:06:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 3-1-2022 11:15:32[[ENDINFO]][[STARTTEXT]]se koblede sag[[ENDTEXT]]803599",2630,Taastrup,28.0,Tændvæske,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,171
171,Risiko for begrænset forgiftning,Blandede ikke chlorerede kulbrinter,NaN,NaN,2022-01-03 10:00:58,NaN,Observeres hjemme,Psykiatriske sygdomme,Akut forgiftning,KEMI,"[[STARTINFO]]KERI0026, 3-1-2022 15:37:40[[ENDINFO]][[STARTTEXT]]Tændvæske, Kulbrinter, simple alifatiske. Hoste? nej Ufarligt at indtag. risiko er kemisk pneumoni OBS på bosted et par timer endnu for tp stigning, almen påvirkning, vejrtræknings besvær. ved symptomer så indl. med det samme. [[ENDTEXT]]803677",2022-01-03 15:28:42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Praksis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 3-1-2022 15:37:40[[ENDINFO]][[STARTTEXT]]Har ved 10 tiden i dag på et beskyttet værksted smagt på Tændvæske. Pædagog der er med hos lægen, ved ikke hvor meget. Fik lidt hurtig vejrtrækning lige efter. ved 12 tiden lidt bøvsen. Ligner sig selv nu. Farligt?[[ENDTEXT]]803677",2630,Taastrup,28.0,Tændvæske,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN,True,171

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
172,Risiko for livstruende forgiftning,PROMETHAZINHYDROCHLORID,NaN,20,2022-01-03 12:00:47,NaN,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]KERI0026, 3-1-2022 15:53:41[[ENDINFO]][[STARTTEXT]]AD Sertralin: beh ind >1000mg, ikke muligt med 5 tabletter. AD Phenergan: OBS takycardi, hypotension, væske behandling. Sedation, antikolignert: Flushing, mundtørhed, mydriasis, urinretention obs EPS/ akut og tardiv dystoni beh med Biperiden EKG/ 2time/ hvis hun forsat er upåvirket/ kun træt han EKG afsluttes efter 6 timer. [[ENDTEXT]]803679[[STARTINFO]]sgre0034, 4-1-2022 14:29:48[[ENDINFO]][[STARTTEXT]]Konf HHOR: Skal afslutte NAC behandlingen. levertal kan gentages om 12 timer[[ENDTEXT]]803914",2022-01-03 15:39:54,SERTRALIN,mg,mg,mg,NaN,NaN,SERTRALIN,NaN,5,NaN,ZZMED,Randers Centralsygehus,Panodil,PARACETAMOL,500,NaN,NaN,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 3-1-2022 15:53:41[[ENDINFO]][[STARTTEXT]]OD kl 12. Får ingen fast medicin selv. Kender ikke styrke på sertralin eller Phenergan- De opstarter NAC behandling. Er upåvirket. Behandling?[[ENDTEXT]]803679[[STARTINFO]]sgre0034, 4-1-2022 14:29:48[[ENDINFO]][[STARTTEXT]]2. opkald fra Randers 29464288: Har kørt NAC behandling efter instruks indtil 1. syopregel. ALAT 19, INR 0,83, Bilirubin 28, P-PCM kan ikke måles grundet forhøjet bilirubin. Igår blev der taget en P-PCM kl 17.23 (5,5 timer efter indtag) som var 364 mikromol/l Skal NAC fortsættes?[[ENDTEXT]]803914",8960,Randers SØ,41.0,Phenergan,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,201
250,NaN,PARACETAMOL,NaN,NaN,2022-01-04 14:29:55,NaN,NaN,NaN,NaN,MED,NaN,2022-01-04 14:07:37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Randers Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 4-1-2022 14:43:15[[ENDINFO]][[STARTTEXT]]koblet 386710[[ENDTEXT]]803913",8960,Randers SØ,41.0,Panodil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,201

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
175,Risiko for manifest forgiftning,Pregabalin,75,120,2022-01-03 13:15:01,9000,Indlæggelse,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]sgre0034, 3-1-2022 15:59:25[[ENDINFO]][[STARTTEXT]]Toksisk dosis indtag >1200 mg Særligt for pregabalin kan der forkomme kramper, som beandles med BZD. Derudover kan ses sløvhed og GI symptomer. OBS EKG, risiko for arytmier.[[ENDTEXT]]803685[[STARTINFO]]sgre0034, 3-1-2022 16:18:21[[ENDINFO]][[STARTTEXT]]Ovenstående gentages. Risiko for hypotension, og bevidsthedspåvirkning, intubation kan i svære tilfælde blive nødvendigt. Grundet risiko for arytmier skal pt i telemetri, OBS EKG ved siden af. Behandles med 2 port kul, symptomatisk og understøttende behandling. Væske, sikre TD >50 ml/time OBS bevidsthedsniveau, resp. neurologiske symptomer Observeres indtil klinisk bedring Biokemi iht instruks, samt syre-base status, og rhabdomyolyse prøver Ny henvendelse ved yderligere [[ENDTEXT]]803690[[STARTINFO]]sgre0034, 4-1-2022 11:44:13[[ENDINFO]][[STARTTEXT]]Videregivet til HHOR: Ingen sammenhæng med forgiftning.[[ENDTEXT]]803890",2022-01-03 15:53:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 15:59:25[[ENDINFO]][[STARTTEXT]]Har taget mellem 100-120 kapsler Pregabalin, som han er i fast behandling med. Indtaget er sket omkring kl 13. Pt er vågen, men falder let hen, kan vækkes uden problemer. Har stabile værdier, men en frekvens på 140 Har 20 min til sygehuset Observation?[[ENDTEXT]]803685[[STARTINFO]]sgre0034, 3-1-2022 16:18:21[[ENDINFO]][[STARTTEXT]]med BV Randers sygehus 78423252: Har fået meldt pt. Behandling?[[ENDTEXT]]803690[[STARTINFO]]sgre0034, 4-1-2022 11:44:13[[ENDINFO]][[STARTTEXT]]3. opkald fra Randers sygehus, intensiv læge 78423252: Ringer ang pt der i dag er hyperterm med en TP 39.5, P: 120. CRP 26 Kan det være en del af forgidtnbingen?[[ENDTEXT]]803890",8410,Rønde,32.0,Pregabalin,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,203
177,NaN,Pregabalin,NaN,NaN,2022-01-03 16:18:28,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-03 16:12:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,randers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 16:18:40[[ENDINFO]][[STARTTEXT]]koblet 386713[[ENDTEXT]]803689",8410,Rønde,32.0,Pregabalin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,203

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
182,Risiko for manifest forgiftning,SERTRALIN,100,19,2022-01-03 17:19:28,1900,Indlæggelse,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]sgre0034, 3-1-2022 17:21:31[[ENDINFO]][[STARTTEXT]]Ja. Skal indlægges til behandling! Ring 112[[ENDTEXT]]803709[[STARTINFO]]sgre0034, 3-1-2022 18:50:18[[ENDINFO]][[STARTTEXT]]Symptomer ses indenfor 12 timer i form af opkastninger, svimmelhed. Der kan ses enten agitation eller træthed. Der kan både ses hypo- og hypertension, takykardi. Risiko for serotonergt syndrom (konfusion, hyperrefleksi, hypertermi) og kramper behandles med BZD. Evt risiko for EKG forandringer, anbefaler EKG nu, som gentages efter 4 timer eller ved forværring Behandles med 1 port kul, symptomatisk behandling Observeres i 12 timer for udvikling af symptomer[[ENDTEXT]]803728",2022-01-03 17:19:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 17:21:31[[ENDINFO]][[STARTTEXT]]Ringer fordi kæresten har taget hendes medicin. Farligt?[[ENDTEXT]]803709[[STARTINFO]]sgre0034, 3-1-2022 18:50:18[[ENDINFO]][[STARTTEXT]]2. opkald: Modtaget på Slagelse akutmodtagelse 93576522: lidt træt men ellers upåvirket, normale værdier. Virker depressiv. Er i gang med at indtage kul. Behandling?[[ENDTEXT]]803728",4200,Slagelse,21.0,SERTRALIN,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,211
190,NaN,SERTRALIN,NaN,NaN,2022-01-03 18:39:39,1900,NaN,NaN,NaN,ZZMED,NaN,2022-01-03 18:39:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sygehus Vestsjælland, Slagelse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 18:50:35[[ENDINFO]][[STARTTEXT]]koblet 386724[[ENDTEXT]]803727",4200,Slagelse,21.0,SERTRALIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,211

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
191,Risiko for begrænset forgiftning,Levetiracetam,250,2,2022-01-03 18:30:06,500,Observeres hjemme,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]sgre0034, 3-1-2022 19:05:37[[ENDINFO]][[STARTTEXT]]Ingen tiltag. Kan observeres hjemme. Kan evt blive mere træt end vanligt. Hvis barnet er meget træt i morgen tidlig må forældre kontakte behandlende afd. mhp om der skal gives normal morgendosis eller om dosis skal halveres eller springes over![[ENDTEXT]]803732[[STARTINFO]]KERI0026, 3-1-2022 19:54:31[[ENDINFO]][[STARTTEXT]]2 opkald: ovenstående gentages. og AD Acetylsalicylsyre: ikke risiko for BL.propper. ikke forgiftnings dosis har fået svarende til 5mg/kg AD Påvirkning af Ofiril: interaktions databasen: ikke risiko i denne dosis (Suzi) [[ENDTEXT]]803748",2022-01-03 18:52:39,Levetiracetam,NaN,NaN,NaN,NaN,NaN,Levetiracetam,250,1,250,ZZMED,NaN,Hjertemagnyl,ACETYLSALICYLSYRE,75,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 19:05:37[[ENDINFO]][[STARTTEXT]]112 viderestiller til forældre: Har Sturge-Weber syndrom og derfor i behandling med ovenstående. Forældre har ved fejl givet barnet dobbeltdosis af Letiracetam og hjertemagnyl. Barnet er upåvirket. Farligt?[[ENDTEXT]]803732[[STARTINFO]]KERI0026, 3-1-2022 19:54:31[[ENDINFO]][[STARTTEXT]]2 opkald: Vagtlæge 1813. far har nu læst indlægs seddel. Risiko for blod propper? er der risiko for at hjertemagnyl påvirker virkning af Valproat ? Får også fast Ofiril 3,15ml, a 60mg /ml. har ikke fået dobbelt dosis af denne. [[ENDTEXT]]803748",2300,København S,3.0,Levetiracetam,NaN,NaN,NaN,NaN,NaN,NaN,Fejldosering,NaN,True,243
196,NaN,ACETYLSALICYLSYRE,NaN,NaN,2022-01-03 19:47:24,NaN,NaN,NaN,NaN,MED,NaN,2022-01-03 19:39:13,Levetiracetam,NaN,NaN,NaN,NaN,NaN,Levetiracetam,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 3-1-2022 19:48:18[[ENDINFO]][[STARTTEXT]]2 opkald kobles 386734[[ENDTEXT]]803746",2300,København S,3.0,Hjertemagnyl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,243

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
201,Risiko for livstruende forgiftning,IBUPROFEN,600,20,2022-01-03 19:00:46,12000,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]KERI0026, 3-1-2022 21:07:04[[ENDINFO]][[STARTTEXT]]Han skal indl. til behandling på sygehus. ring 112. [[ENDTEXT]]803759[[STARTINFO]]KERI0026, 3-1-2022 22:12:26[[ENDINFO]][[STARTTEXT]]2 opkald: Aktiv kul 2 portioner AD PCM: NAC behandling efter vanlig guideline AD Ibumetin: behandlings krævende OD OBS GI blødning, Giv PPI 40mg iv svimmelhed, hovedpine, tinnitus, somnolens. forbigående nyre og lever påvirkning giv væske, OBS Hyperventilation/ metabolisk acidose vitalparametre Kontrol EKG Biokemi: Hgb, leuco, diff, Trombocytter, Na, K, crea, carbamid, ALAT, INR, A,pkt sPCM; s- Salicylat ved tiltagende symptomer gentages Biokemi [[ENDTEXT]]803774",2022-01-03 21:00:41,paracetamol,mg,NaN,NaN,NaN,NaN,PARACETAMOL,500,2024-03-02 00:00:00,håndfulde,ZZMED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 3-1-2022 21:07:04[[ENDINFO]][[STARTTEXT]]Hendes mand har for ca 2 timer siden taget 2-3 håndfulde PCM og nok to ark Ibumetin hver a 10 stk 600mg tabletter. står nu og kaster op Hun ved ikke hvad hun skal gøre?[[ENDTEXT]]803759[[STARTINFO]]KERI0026, 3-1-2022 22:12:26[[ENDINFO]][[STARTTEXT]]2 opkald Slagelse sygehus, AM, læge akut forvagt. Nashir. tlf Mand ankommet. Behandling?[[ENDTEXT]]803774",4200,Slagelse,38.0,Ibumetin,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,256
208,NaN,PARACETAMOL,NaN,NaN,2022-01-03 22:12:52,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-03 22:01:19,Ibumetin,NaN,NaN,NaN,NaN,NaN,IBUPROFEN,NaN,NaN,NaN,MED,"Sygehus Vestsjælland, Slagelse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 3-1-2022 22:13:26[[ENDINFO]][[STARTTEXT]]2 opkald kobles 386746[[ENDTEXT]]803773",4200,Slagelse,38.0,paracetamol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,256

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
214,Risiko for manifest forgiftning,QUETIAPIN FUMARAT,25,20,2022-01-03 23:00:16,500,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,"[[STARTINFO]]mann0002, 4-1-2022 00:13:47[[ENDINFO]][[STARTTEXT]]Antipsykotika, behandlingskrævende ved indtag > 5 x vanlige enkeltdosis. Dette passeret, men svære forgiftningssymptomer forventes ikke. Der kan ses bla. sedation og takycardi[[ENDTEXT]]803786[[STARTINFO]]sgre0034, 4-1-2022 09:30:00[[ENDINFO]][[STARTTEXT]]Pt observeres indtil symptomfrihed i min 6 timer[[ENDTEXT]]803839",2022-01-04 00:07:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 4-1-2022 00:13:47[[ENDINFO]][[STARTTEXT]]Egen medicin, får vanligt 50 mg x 1, vist til natten. Har ikke sovet i 3 døgn og derfor indtaget 20 tbl. Er lidt træt ellers ingen symptomer.[[ENDTEXT]]803786[[STARTINFO]]sgre0034, 4-1-2022 09:30:00[[ENDINFO]][[STARTTEXT]]2. opkald Hvidovre akutmodtagelse læge Mette 20527260: Har nu været indlagt siden igår. EKG og telemetri har været upåvirket, og pt er asymptomatisk. Hvor længe skal pt observeres[[ENDTEXT]]803839",2650,Hvidovre,37.0,QUETIAPIN FUMARAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,266
231,NaN,QUETIAPIN FUMARAT,25,NaN,2022-01-04 09:22:29,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-04 08:39:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 4-1-2022 09:30:16[[ENDINFO]][[STARTTEXT]]koblet 386759[[ENDTEXT]]803826",2650,Hvidovre,37.0,QUETIAPIN FUMARAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,266

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
255,Risiko for manifest forgiftning,OXAZEPAM,15,30,2022-01-04 15:00:25,450,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]nhan0003, 4-1-2022 15:21:22[[ENDINFO]][[STARTTEXT]]Vil ikke forvente svære symptomer efter Quetiapin: CNS påvirkning, anticholinerge symptomer Oxapax: CNS påvirkning, resp. depression Symptomatisk beh. Hyppig kontrol af vitalparametre med fokus på CNS, BT, P, resp SAT, tp. Kontrol EKG hv 2 time i mindst 6 timer Obs rebound effekt efter Flumazenil. Kan gives i refrakte doser ved resp. depression. Dog nedsat krampetærskel efter indtag af Quetiapin Biokemi: elektrolytter, lever- nyretal, Mg, Ca, A.pkt, pcm, salicicylat. A.pkt Obs til lette symptomer i mindst 6 timer[[ENDTEXT]]803926[[STARTINFO]]KERI0026, 4-1-2022 22:28:45[[ENDINFO]][[STARTTEXT]]2 opkald : OBS til der kun har været lette symptomer i 6 timer. Sover formentlig på oxapax nu. EKG kan afsluttes. De beholder hende til i moregn. Har hun fået aktiv kul? nej- det kan han ikke se. ( Læge mener at kul tager stof ud af blodbanen; kort information om kuls virkning)[[ENDTEXT]]804032",2022-01-04 14:59:41,QUETIAPIN FUMARAT,mg,mg,NaN,NaN,NaN,QUETIAPIN FUMARAT,25,10,250,ZZMED,Hvidovre Hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 4-1-2022 15:21:22[[ENDINFO]][[STARTTEXT]]Indlagt på psyk afd. Meningen at hun skulle udskrives i dag. Gemt / haft adgang til ovenstående, taget i løbet af dagen. Lige modtaget i acut modtagelsen. Er vågen men sløv. ligger med lukkede øjne og ønsker ikke at samarbejde. Der er givet Flumazenil 3 mg på psyk afd kl 14. Ved ikke om det er givet iv / im EKG ved at blive kontrolleret Ifølge FMK: Ikke i behandling med Quetiapin[[ENDTEXT]]803926[[STARTINFO]]KERI0026, 4-1-2022 22:28:45[[ENDINFO]][[STARTTEXT]]2 opkald; hun er træt og sover, ikke andet, er stabil og EKG er forsat ia. Hvor længe skal de tages?[[ENDTEXT]]804032[[STARTINFO]]KERI0026, 4-1-2022 22:31:19[[ENDINFO]][[STARTTEXT]]2 opkald: Hvidovre, Søren, læge bagvagt AM tlf 20425395[[ENDTEXT]]804033",2450,København SV,29.0,Oxapax,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,314
301,NaN,OXAZEPAM,NaN,NaN,2022-01-04 22:29:33,NaN,NaN,NaN,NaN,MED,NaN,2022-01-04 22:22:38,QUETIAPIN FUMARAT,NaN,NaN,NaN,NaN,NaN,QUETIAPIN FUMARAT,NaN,NaN,NaN,ZZMED,Hvidovre Hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 4-1-2022 22:31:21[[ENDINFO]][[STARTTEXT]]2 opkald kobles 386805[[ENDTEXT]]804031",2450,København SV,29.0,Oxapax,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,314

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
260,Risiko for manifest forgiftning,CYCLIZINHYDROCHLORID,50,10,2022-01-04 13:45:35,500,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]nhan0003, 4-1-2022 15:33:21[[ENDINFO]][[STARTTEXT]]Tox dosis. Skal indlægges til behandling[[ENDTEXT]]803937[[STARTINFO]]KERI0026, 4-1-2022 19:01:02[[ENDINFO]][[STARTTEXT]]vægt 90- 100kg Indtag 6-5 mg/kg Ikke aktiv kul, OBS en time endnu, OBS vandladning evt EKG gentages. Hvis forsat upåvirket kan hun udskr til psykiatrisk vurdering. [[ENDTEXT]]803989",2022-01-04 15:30:11,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 4-1-2022 15:33:21[[ENDINFO]][[STARTTEXT]]Bosted ringet til vagtcentral. Beboer taget ovenstående[[ENDTEXT]]803937[[STARTINFO]]KERI0026, 4-1-2022 19:01:02[[ENDINFO]][[STARTTEXT]]2 opkald Svendborg sygehus. Læge Steen Nielsen. Am Pt er ankommet, OD taget i frustration, har en åben indl. til Psyk. men de har afvist hende i dag da der er overbelægning. Er velbef, har haft let tremor og kvalme men aftaget. P 98-103, Bt 145/96/ er vanlig lidt højt. Ikke træt. EKG ia. Pupillet lidt dilateret. Indtag kl 13.45 og ikke 14.30. Behandling? [[ENDTEXT]]803989",5800,Nyborg,49.0,Gotur,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,316
283,NaN,CYCLIZINHYDROCHLORID,NaN,NaN,2022-01-04 19:02:02,NaN,NaN,NaN,NaN,MED,NaN,2022-01-04 18:50:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus Fyn Svendborg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 4-1-2022 19:02:33[[ENDINFO]][[STARTTEXT]]2 opkald kobles 386810[[ENDTEXT]]803988",5800,Nyborg,49.0,Gotur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,316

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
265,Risiko for manifest forgiftning,NaN,NaN,NaN,2022-01-04 16:15:15,NaN,Indlæggelse,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]KERI0026, 4-1-2022 16:31:07[[ENDINFO]][[STARTTEXT]]OBS aspirations risiko kemisk pneumoni OBS på sygehus i 6 timer Lægevagt indl. på Skejby[[ENDTEXT]]803950[[STARTINFO]]nhan0003, 4-1-2022 18:07:52[[ENDINFO]][[STARTTEXT]]2 opkald Ovenstående gentaget[[ENDTEXT]]803979",2022-01-04 16:24:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 4-1-2022 16:31:07[[ENDINFO]][[STARTTEXT]]Barn har drukket af afspænings middel. Hoster under indtag. behandling?[[ENDTEXT]]803950[[STARTINFO]]nhan0003, 4-1-2022 18:07:52[[ENDINFO]][[STARTTEXT]]2 opkald Pt modtaget på Skejby. Læge Niels: Tlf: 20316856 Frembyder ingen symptomer[[ENDTEXT]]803979",8471,Sabro,1.0,Afspændingsmiddel til maskinopvask,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN,True,318
279,NaN,NaN,NaN,NaN,2022-01-04 18:05:31,NaN,NaN,NaN,NaN,KEMI,NaN,2022-01-04 18:03:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Skejby Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 4-1-2022 18:06:36[[ENDINFO]][[STARTTEXT]]2 opkald se sag 386816[[ENDTEXT]]803978",8471,Sabro,1.0,Afspændingsmiddel til maskinopvask,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,318

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
5,Risiko for manifest forgiftning,LITHIUMCITRAT,6,2,2022-01-03 16:28:40,12,Indlæggelse,Psykiatriske sygdomme,Kronisk forgiftning,ZZMED,"[[STARTINFO]]sgre0034, 3-1-2022 16:51:24[[ENDINFO]][[STARTTEXT]]S-konc. følges hver 4. time, skal ligge <1,0 mmol/L Har symptomer på forgiftning., samt påvirket nyrefunktion. Litarex sep. Skal behandles med væske, sikre diureser 2 ml/kg/time, OBS dehydrering. Der kan hæmodialyseres, men dette kun i tilfælde af s-lithium >0,4 mmol/ hos pt med nedsat nyrefunktion. Risiko for arytmier, skal lægges i telemetri, OBS EKG. Risiko for metabolisk acidose (er en lille smule sur), kan kompensere respiratorisk (har mistanke om pneumoni, rtg. af thorax er rekv.), da der er risiko for lungeødem eller ARDS Korrektion af elektrolytter Biokemi, samt syre-base status er taget Instruks mailes, må ringe ved yderligere Observeres 24 timer efter normalisering af biokemi[[ENDTEXT]]803694[[STARTINFO]]mhen0054, 5-1-2022 09:55:38[[ENDINFO]][[STARTTEXT]]Ja, bør pausere propranolol. Måle s-lithium i hver vagt indtil denne under 1,0 ,mmol/l. Konf FSOE001.[[ENDTEXT]]804093",2022-01-03 16:28:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 16:51:24[[ENDINFO]][[STARTTEXT]]Er i fast behandling med Litarex 2 tbl til aften. Hjemmespl har igennem de sidste 2 dage observeret at pt har været noget konfus, har tremor og hyperrefleksi. Har ikke haft GI symptomer! Er indlagt via egen læge. Der er ingen s-konc. endnu, men den er taget. Pt er noget dehydreret, og nedsat nyrefunktion, ikke kendt med dette fra tidligere, creatinin 190, Kalium 5,9, har forhøjede infektionstal. Har ikke mistanke om akut forgiftning. Pt er i behandling med ACE-hæmmer samt centyl. Behandling?[[ENDTEXT]]803694[[STARTINFO]]mhen0054, 5-1-2022 09:55:38[[ENDINFO]][[STARTTEXT]]2.opkald læge Moska Køge sgh. Klaret op, fortsat meget træt. S-lithium ved ankomst 2,1, falder samme dag til 1,9, igår 1,7. Afventer s-lithium idag. Haft SB ned til 37. Normale inf. tal. Bør hun også pausere propranolol ? Hvor ofte tage S-lihtium ? [[ENDTEXT]]804093",4600.0,Køge,79,LITHIUMCITRAT,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,0
12,NaN,LITHIUMCITRAT,NaN,NaN,2022-01-05 09:56:41,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-05 09:26:25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mhen0054, 5-1-2022 09:57:38[[ENDINFO]][[STARTTEXT]]2.opkald i koblet sag. [[ENDTEXT]]804092",4600.0,Køge,79,LITHIUMCITRAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,0

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
28,Risiko for manifest forgiftning,OLANZAPIN,10,14,2022-01-09 13:30:31,140,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,"[[STARTINFO]]cdit0001, 9-1-2022 13:45:07[[ENDINFO]][[STARTTEXT]]Obs BT og hvis det er så højt skal pt på sygehus så hurtigt som muligt. Vanligvis ses hypotension, tackykardi og CNS depression. Indlægges mhp observation og symptomatisk behandling.[[ENDTEXT]]805045[[STARTINFO]]cdit0001, 9-1-2022 14:40:28[[ENDINFO]][[STARTTEXT]]Kul vha anæstesien evt. EKG hver anden time i 6 timer. Obs antikolinerge symptomer, Behandlingen er symptomatisk Er der kun lette eller ingen symptomer i 6 timer kan somatisk obs afsluttes.[[ENDTEXT]]805054",2022-01-09 13:30:14,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 9-1-2022 13:45:07[[ENDINFO]][[STARTTEXT]]Har hentet ovenstående. Indtaget egen medicin . Får 10 mg til natten og tidspunktet for indtag kendes ikke. Kan svare på tiltale men er meget sløv. Puls 113. Der måles et blodtryk på 211/160 men kunne være fejlmåling.[[ENDTEXT]]805045[[STARTINFO]]cdit0001, 9-1-2022 14:40:28[[ENDINFO]][[STARTTEXT]]2 opkald: Mark Jacobsen. Er kommet BT er nu 145/80, puls 106. QTc er 446 msek. Er lidt træt/sløv. Har ildelugtende urin og de anlægger KAD[[ENDTEXT]]805054",3700.0,Rønne,71,OLANZAPIN,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,3
29,NaN,OLANZAPIN,NaN,NaN,2022-01-09 14:25:34,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-09 14:23:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bornholms Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mhen0054, 9-1-2022 14:26:11[[ENDINFO]][[STARTTEXT]]2.opkald i koblet sag. [[ENDTEXT]]805053",3700.0,Rønne,71,OLANZAPIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,3

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
30,Risiko for manifest forgiftning,DONEPEZIL,10,7,2022-01-09 16:06:03,70,Indlæggelse,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]msoe0664, 9-1-2022 16:37:06[[ENDINFO]][[STARTTEXT]]Donepezil kan give kolignert syndrom, som hun også har en del symptomer på. evt også haft store vandladninger og deraf hyponatriæmi. Har fået over toksisk dosis og da donepezil har en t½ på 70 timer er påvirkningen på ingen måde overstået. stadig risiko for elektrolytforstyrrelse, hypotention mm. Anbefaler at ringe til lægevagten mhp at indlægge hende igen. [[ENDTEXT]]805060[[STARTINFO]]msoe0664, 9-1-2022 17:32:58[[ENDINFO]][[STARTTEXT]]Forklaret ovenstående omkring kolignergt syndrom. Diarre, opkast, sved, savlen, tåreflod, store diureser kan ses. desuden via parasympaticus bradykardi, AV blok. kontrol af ekg og hvis forandringer telemetri, atropin er antidot, men bruges kun ved svære symptomer. Ellers symptomatisk behandling med korrigering af elektrolyttter og væske til symptomer ophører. Kan også give muskelpåvirkning og man kontrollerer for rhabdomyolyse. Borger er også beskrevet ridig/stiv og har måske ikke fået sin levodopa så meget som hun skulle.[[ENDTEXT]]805088[[STARTINFO]]nhan0003, 10-1-2022 10:09:30[[ENDINFO]][[STARTTEXT]]3 opkald Konf jwan0009 Pause Donepezil i 14 dage, man kan evt opstarte med 5 mg Donepezil. Opfølgning hos praktiserende læge[[ENDTEXT]]805198",2022-01-09 15:30:10,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]msoe0664, 9-1-2022 16:37:06[[ENDINFO]][[STARTTEXT]]Søn som også er læge: Opdaget at han mor har fået for meget Donepezil. Får vanligt 10mg x 1, men hans far har fejdoseret i hendes dosetæsker så hun har fået 20 20 20 10 mg daglig. Han ved ikke hvor længe men sandsynligvis en uge. Hun har været dårlig den sidste uge med opkast, diarre, ikke kunnet komme ud af sengen, en enkelt dag hallucinationer og desuden mere regid/stiv - evt ikke fået sin vanlige levodopa og får også Eldepryl. Ved ikke hvordan det har været doseret. Været indlagt i nat hvor hun blev elektrolytkorrigeret og fik væke. Havde hyponatriæmi og har også haft hypokaliæmi. Han har lige nu efter hun er kommet hjem opdaget at der er fejl i doseringen af hendes medicin. Risiko? Hun vil helst ikke på sygehuset igen. [[ENDTEXT]]805060[[STARTINFO]]msoe0664, 9-1-2022 17:11:14[[ENDINFO]][[STARTTEXT]]Søn ringer igen, fået 70mg daglig minimum i 3 dage og måske længere. Vir kan ikke redegøre for det.[[ENDTEXT]]805083[[STARTINFO]]msoe0664, 9-1-2022 17:32:58[[ENDINFO]][[STARTTEXT]]læge Esbjerg med.afd: Talt med datter som har forklaret hisorie og vil bare lige høre nærmere angående Donepezil. [[ENDTEXT]]805088[[STARTINFO]]nhan0003, 10-1-2022 10:09:30[[ENDINFO]][[STARTTEXT]]3 opkald Læge Ann Tlf: 79185705 Pt frembyder ingen symptomer. Sovet godt i nat. BT: 122/75 P: 57 Na: 132 Tænker at pt skal udskr. Aftalt at hjemmeplejen overtager medicin håndtering[[ENDTEXT]]805198",6710.0,Esbjerg V,71,DONEPEZIL,NaN,NaN,NaN,NaN,NaN,NaN,Fejldosering,NaN,True,5
32,NaN,DONEPEZIL,NaN,NaN,2022-01-09 17:22:11,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-09 17:07:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Esbjerg Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]msoe0664, 9-1-2022 17:33:36[[ENDINFO]][[STARTTEXT]]koblet til 387256[[ENDTEXT]]805082",6710.0,Esbjerg V,71,DONEPEZIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,5
35,NaN,DONEPEZIL,NaN,NaN,2022-01-10 09:43:13,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-10 09:41:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Esbjerg Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 10-1-2022 10:09:15[[ENDINFO]][[STARTTEXT]]3 opkald se sag 387256[[ENDTEXT]]805189",6710.0,Esbjerg V,71,DONEPEZIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,5

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
37,Uafklaret risiko,OLANZAPIN,NaN,NaN,2022-01-10 11:45:02,NaN,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,"[[STARTINFO]]nhan0003, 10-1-2022 12:28:52[[ENDINFO]][[STARTTEXT]]Da der ringes tilbage: CT-scan: ia der er givet Flumazenil med god effekt- vågnet lidt op, ligger og hvisker Ville umiddelbart forvente øvrige symptomer hvis der er taget Olanzapin ( forlænget QTc, anticholinerge sympt) Symptomatisk beh: Forhøre hvad hustru har af vanlig medicin Biokemi: pcm, salicylat, ethanol, rhabdomyolyse Ny henvendelse ved behov[[ENDTEXT]]805232[[STARTINFO]]tvan0009, 10-1-2022 18:02:02[[ENDINFO]][[STARTTEXT]]anbefaler kul stille og roligt over en times tid hvis luftvejene kan forsvares følge godt med med flumazenil derudover symptomatisk observation EKG/2 time (konf SBOE)[[ENDTEXT]]805300",2022-01-10 11:43:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hillerød Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 10-1-2022 12:28:52[[ENDINFO]][[STARTTEXT]]Pt fundet bevidstløs af hustru og datter til morgen og indlægges. Har d 09-01 fortalt datter at han ikke ønsker at leve mere. Pt sovende GCS: 8. Muskelstivhed, mistænker om han kan have taget Olanzapin, pga muskelstivhed ? Pt varetager selv sin medicin. Usikkerhed om der mangler tbl hjemme. Sidst indløst recept april 2021 EKG: QTc: 408 ms Frekvens: 50 CT- scan: bestilt Vandl x 2 i buksene. KAD anlagt 100 ml urin udtømt Vanlig medicin: Olanzapion 2.5 mg x 1, Alfuzosin 10 mg, Amlodipin 5 mg, Cloipidogrel 75 mg x 1, Simvastatin 10 mg Drug test: Pos benzodiazepin Der er givet Naloxon -> Ingen effekt[[ENDTEXT]]805232[[STARTINFO]]tvan0009, 10-1-2022 18:02:02[[ENDINFO]][[STARTTEXT]]2 opkald stabiliseret sig med P 45 BT165 der gives løbende flumazenil ca 0,2mg /time som han vågner op på har fortsat små pupiller der er ikke givet kul opstartet olanzapin kan have taget 35mg er der noget man skal være opmærksom på[[ENDTEXT]]805300",3200.0,Helsinge,81,OLANZAPIN,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,7
39,NaN,OLANZAPIN,2.5,14,2022-01-10 17:40:38,35,NaN,NaN,NaN,ZZMED,NaN,2022-01-10 17:21:20,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hillerød Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 10-1-2022 18:01:34[[ENDINFO]][[STARTTEXT]]se koblede sag[[ENDTEXT]]805297",3200.0,Helsinge,81,OLANZAPIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,7

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
48,Risiko for manifest forgiftning,VENLAFAXINHYDROCHLORID,75,8,2022-01-13 01:45:20,600,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]nhan0003, 13-1-2022 03:50:57[[ENDINFO]][[STARTTEXT]]Indtaget tox dosis mhp Lamotrigin. Skal indlægges til behandling[[ENDTEXT]]805840[[STARTINFO]]nhan0003, 13-1-2022 06:15:26[[ENDINFO]][[STARTTEXT]]2 opkald Lamotrigin: Tox dosis > 1000 mg. CNS påvirkning, Kvalme, opkastning, tremor Venlafaxin: Atoxisk. Tox dosis > 900 mg. Evt svimmelhed, kvalme Topimax: Symptomer indenfor 4 timer. CNS påvirkning, kvalme, opkastning Aktivt kul Symptomatisk beh. Obs vitalparametre med fokus på CNS, BT, P, resp, SAT, tp. KOntrol EKG om 2 timer Ilt på næsekat Biokemi: elektrolytter, lever- nyretal, A.pkt, Pcm, salicylat Hvis fortsat ingen symptomer, kan observation afsluttes om 6 timer[[ENDTEXT]]805843",2022-01-13 01:45:54,Topimax,NaN,NaN,NaN,NaN,NaN,TOPIRAMAT,100,8,800,MED,NaN,LAMOTRIGIN,LAMOTRIGIN,200.0,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZZMED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 13-1-2022 03:50:57[[ENDINFO]][[STARTTEXT]]Skulle tage sin vanlige aftenmedicin. Taget døgndosis x 8, kan ikke helt forklare hvordan det skete. Er vågen, klar og relevant[[ENDTEXT]]805840[[STARTINFO]]nhan0003, 13-1-2022 06:15:26[[ENDINFO]][[STARTTEXT]]2 opkald Pt modtaget på Viborg sygehus. LÆge Ida Tlf: 78445053 Taget doseringsposer og åbnet dem. Fortæller tbl er indtaget i affekt. Har doseringsposerne med og taget 8 døgndosering samt åbnet 2 yderligere hvor Lamotrigin er taget. Nægter at have taget Paracetamol Drukket 2 Guldøl Fortsat ingen symptomer EKG: Sinusrytme / Smalle komplekser BT: 115/51 P: 88 Tp: 37 Resp: 16 SAT: 92 ( storryger)[[ENDTEXT]]805843",8883.0,Gjern,70,"Venlafaxin \Hexal\""""",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,10
49,NaN,TOPIRAMAT,NaN,NaN,2022-01-13 06:06:30,NaN,NaN,NaN,NaN,MED,NaN,2022-01-13 03:51:47,VENLAFAXINHYDROCHLORID,NaN,NaN,NaN,NaN,NaN,VENLAFAXINHYDROCHLORID,NaN,NaN,NaN,ZZMED,Sygehus Viborg,LAMOTRIGIN,LAMOTRIGIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZZMED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 13-1-2022 06:06:56[[ENDINFO]][[STARTTEXT]]2 opkald se sag 387567[[ENDTEXT]]805842",8883.0,Gjern,70,Topimax,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,10

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
55,Risiko for manifest forgiftning,til høreapparat.,NaN,6,2022-01-13 12:30:26,NaN,Skadestue,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]cdit0001, 13-1-2022 18:01:47[[ENDINFO]][[STARTTEXT]]RTG mhp lokalisering for at sikre at der ikke sidder et i oesofagus eller svælg. Hvis batteriet ligger i ventriklen, informeres pt. om at søge læge på ny, hvis der opstår GI-symptomer.[[ENDTEXT]]806006[[STARTINFO]]cdit0001, 13-1-2022 18:15:23[[ENDINFO]][[STARTTEXT]]Som ovenstående. De skal ikke forvente noget akut.[[ENDTEXT]]806011",2022-01-13 17:52:37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 13-1-2022 18:01:47[[ENDINFO]][[STARTTEXT]]Der stod et medicinbæger med 5-6 batterier til høreapparatet. Dem slugte ovenstående ved middagstid.[[ENDTEXT]]806006[[STARTINFO]]cdit0001, 13-1-2022 18:15:23[[ENDINFO]][[STARTTEXT]]Er på vej ud og hente ovenstående.[[ENDTEXT]]806011",8210.0,Aarhus V,78,Knapcelle,NaN,NaN,NaN,NaN,Forveksling,NaN,NaN,NaN,True,11
56,NaN,NaN,NaN,NaN,2022-01-13 18:13:16,NaN,NaN,NaN,NaN,DIVERSE,NaN,2022-01-13 18:02:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 13-1-2022 18:15:32[[ENDINFO]][[STARTTEXT]]Koblet 387630[[ENDTEXT]]806010",8210.0,Aarhus V,78,Knapcelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,11

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
63,Risiko for livstruende forgiftning,OXYCODONHYDROCHLORID,5,7,2022-01-14 14:40:57,35,Indlæggelse,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]KERI0026, 15-1-2022 04:31:40[[ENDINFO]][[STARTTEXT]]Stor dosis, er klinisk påvirket, virkning mindst 24 timer skal indl. med det samme. fokus Bevidsthed og resp, kald AMK læge ved tvivl.[[ENDTEXT]]806267[[STARTINFO]]KERI0026, 15-1-2022 05:33:44[[ENDINFO]][[STARTTEXT]]2 opkald: Kramper ses efter Dolol indtag, beh med BZD Kald anæstesi for vurdering af pt/ understøttende behandling, justering af pH Naloxon kan gives som infusion, ex 2mg Naloxon i 500ml isoton Nacl/Glucose, svarende til 4microg/ml. infusions hastighed efter klinik, start f.ex med 10 microg/kg /t . (der er max givet 75 mg /døgn til voksen uden bivirkninger). OBS serotonergt syndrom.tp.måling. OBS Rhabdomyolyse, s-PCM, s-salicylat ring igen ved tvivl Opioid instruks tilbudt. Konf: Krampe profylakse? afvente om kramper forsætter. aktiv kul nu? nej lægges i kaffe kop for opfølgning., [[ENDTEXT]]806268",2022-01-15 04:25:03,Dolol,mg,mg,NaN,NaN,NaN,TRAMADOLHYDROCHLORID,50,130,6500,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 15-1-2022 04:31:40[[ENDINFO]][[STARTTEXT]]OD kl 15, fundet bevidstheds påvirket og overfladisk resp. de har givet naloxon. Behandling? nu det er mere end 15 timer hun har taget det?[[ENDTEXT]]806267[[STARTINFO]]KERI0026, 15-1-2022 05:33:44[[ENDINFO]][[STARTTEXT]]2 opkald Glostrup sygehus, AM,læge Niklas, tlf 38630470. Pt ankommet der er givet Naloxon x 5, med kort effekt, har lige krampet. Har foruden Dolol også taget 35mg Oxycodon. A.pkt efter kramper: pH 7,17, CO2 7,28, Po2 32 Bicarbonat 16,7, Laktat 11. Puls 90, BT ia. Naloxon som infusion?[[ENDTEXT]]806268",2635.0,Ishøj,86,OXYCODONHYDROCHLORID,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,13
64,NaN,OXYCODONHYDROCHLORID,NaN,NaN,2022-01-15 05:12:55,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-15 05:09:16,Dolol,NaN,NaN,NaN,NaN,NaN,TRAMADOLHYDROCHLORID,NaN,NaN,NaN,MED,Kbh. Amts Sygehus i Glostrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 15-1-2022 05:14:01[[ENDINFO]][[STARTTEXT]]2 opkald kobles 387741[[ENDTEXT]]806270",2635.0,Ishøj,86,OXYCODONHYDROCHLORID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,13

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
65,Risiko for manifest forgiftning,ZOLPIDEM TARTRAT,10,10,2022-01-15 08:41:17,100,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]anel0004, 15-1-2022 08:51:48[[ENDINFO]][[STARTTEXT]]Toxisk dosis 5-10 gange terapeutisk dosis. Tolerancen er varierende ALLE personer med mere end milde symptomer bør almindeligvis observeres i hospitalsregi el. lign. Symptomdebut indenfor en time. Vurdering: Borger er Tungt sovende og skal indlægges til behandling og observation. Symptomer bevidsthedssvækkelse, respiratorisk depression, hypotension og takykardi. [[ENDTEXT]]806276[[STARTINFO]]anel0004, 15-1-2022 10:28:51[[ENDINFO]][[STARTTEXT]]Symptomdebut normalt indenfor én time. Spontan restitution indenfor et døgn. Symptomatisk behandling - sikring af vejrtrækning og cirkulation. Indtag i går, for sent til kul. Flumazenil antidot ved respirationsinsufficiens, men obs kontraindikationer, pt har lav krampetærskel. Bl.pr også S-Paracetamol og S-Salicylat. EKG ved mistanke om blandingsforgiftning. Obs på om der er anden årsag til pts. tilstand. Ring igen ved behov.[[ENDTEXT]]806291",2022-01-15 08:40:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 15-1-2022 08:51:48[[ENDINFO]][[STARTTEXT]]Ovenstående har på ukendt tidspunkt indtaget formentlig max 10 stk Zolpidem, dosis er vurderet ud fra pakning, er usikkert. Ambulanceredder finder borger tungt sovende reagerer på smertestimuli, oplysning fra hjemmeplejen er, at hun normalt er helt vågen. Vir er også tilstede. Er det toxisk dosis, skal hun på hospital?[[ENDTEXT]]806276[[STARTINFO]]anel0004, 15-1-2022 10:28:51[[ENDINFO]][[STARTTEXT]]2 opkald fra Læge Sidsel Slagelse sygehus 93566991. Tungt sovende kan få reaktion og øjnene åbnes ved kraftig smertestimuli. BT 174/79, p 85, Tp 35.5, RF 14, SAT 97. Information om indtag af 8-10 Zolpidem, taget i går aftes, men usikkert. Zolpidem skulle ligge i et glas sammen med Panodil. Ved ankomst faldt der en tbl ud fra pts tøj. Pt har Apoplexi med hø sidig hemiparese og Afasi. Har lav krampetærskel. Hvad skal behandles og hvor længe?[[ENDTEXT]]806291",4700.0,Næstved,79,"Zolpidem \Hexal\""""",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,14
67,NaN,ZOLPIDEM TARTRAT,NaN,NaN,2022-01-15 10:29:20,NaN,NaN,NaN,NaN,MED,NaN,2022-01-15 10:09:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sygehus Vestsjælland, Slagelse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 15-1-2022 10:29:44[[ENDINFO]][[STARTTEXT]]2 opkald fra Læge Sidsel Slagelse sygehus 93566991. Koblet til 387745.[[ENDTEXT]]806290",4700.0,Næstved,79,"Zolpidem \Hexal\""""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,14

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
71,Uafklaret risiko,NaN,NaN,NaN,2022-01-15 19:30:08,NaN,Observeres hjemme,NaN,Akut forgiftning,BIO,"[[STARTINFO]]KERI0026, 16-1-2022 02:47:56[[ENDINFO]][[STARTTEXT]]Kontakt til veninde : hvilken slags mener hun det er? og hvor er de plukket? og har hun spist af den samme portion? Symptomer efter 3-4 timer tyder på fordærvet svamp. Guidet til GL hj.s: mener at kunne udelukke de 5. der sendes billeder af svampe hvor stuvning er skyllet af. Aftale af hun ringer igen hvis diarre forsætter og at Vi tales ved til morgen, uanset, Billeder sendes til svampe telefonen. afventer til i morgen tidlig med at sende foto til ID. [[ENDTEXT]]806461[[STARTINFO]]KERI0026, 16-1-2022 06:22:30[[ENDINFO]][[STARTTEXT]]konf: Hvis der forsat kun har været enkelstående diarre, ikke grund til yderligere. [[ENDTEXT]]806476[[STARTINFO]]KERI0026, 16-1-2022 07:23:35[[ENDINFO]][[STARTTEXT]]opfølgning som aftalt: Har ikke har diarre igen, ingen opkaastning, ikke mavesmerter. Føler sig lidt kvalm og lidt koldsved. er ikke selv bekymret. Har ikke talt med veninde endnu. Rettelse: veninde underviser ikke prof. men private ture for bekendte, er erfaren svampe plukker. Plukker i DK og Sverige. Aftalt at de ringer tilbage til GL når der er talt med veninde. se ovenfor. [[ENDTEXT]]806482[[STARTINFO]]rlar0142, 16-1-2022 11:59:41[[ENDINFO]][[STARTTEXT]]2. Opkald Symptomer forenelige med evt enkelt fordærvet svamp eller ikke længe nok tilberedning af enkelte indigo-svampe. Ikke mistanke om cytotoksisk indtag. Ej yderligere. [[ENDTEXT]]806522",2022-01-16 02:14:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 16-1-2022 02:47:56[[ENDINFO]][[STARTTEXT]]Har fået tørrede svampe af veninde, 2 slags. Kan ikke huske hvad de hedder. Veninde er erfaren svampe plukker, underviser i det. Lavet stuvning til aften af svampe, spist af dem både hende og vir. kl 19.30. Efter 3-4 timer får hun kvalme og diarre x 1. ingen opkastning. har det bedre igen, noget rumlen i mave og let kvalme. Han har det fint. igen mavetarm gener. Farligt? [[ENDTEXT]]806461[[STARTINFO]]KERI0026, 16-1-2022 07:47:35[[ENDINFO]][[STARTTEXT]]Veninde tørrer svampe i en maskine, så det går hurtigt. [[ENDTEXT]]806485[[STARTINFO]]rlar0142, 16-1-2022 11:59:41[[ENDINFO]][[STARTTEXT]]2. Opkald fra Jytte Har ikke haft flere opkastninger eller diarréer, men fortsat lidt utilpas i maven. Ægtefælle ingen symptomer. Veninde, der har virkelig styr på svampeplukkeri og læser alt om samme, havde plukket : Indigosvampe - der dog skal tilberedes i længere tid ( hvilket ikke helt var tilfældet her), tragtkantareller, Karl Johan og rør-hatte. Har med sikkerhed ikke plukket giftige svampe. Veninde og dennes ægtefælle har selv spist flere gange af samme portioner, uden gener - men det har været tilberedt i længere tid (risotto fx). Yderligere ? [[ENDTEXT]]806522",3460.0,Birkerød,74,Svampe - ukendte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Levnedsmiddel,True,15
72,NaN,NaN,NaN,NaN,2022-01-16 11:59:47,NaN,NaN,NaN,NaN,BIO,"[[STARTINFO]]rlar0142, 16-1-2022 12:00:19[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 387830[[ENDTEXT]]806521",2022-01-16 11:41:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3460.0,Birkerød,74,Svampe - ukendte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,15

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
73,Risiko for manifest forgiftning,PARACETAMOL,500,12,2022-01-16 12:05:59,6000,Skadestue,NaN,Akut forgiftning,MED,"[[STARTINFO]]rlar0142, 16-1-2022 12:10:48[[ENDINFO]][[STARTTEXT]]Da der muligvis er nedsat nyrefunktion, og indtag i > 48 timer er > 4 gram/døgn, da anbefales akutte blodprøver. Stillet igennem til vagtlæge region midt. [[ENDTEXT]]806524[[STARTINFO]]rlar0142, 16-1-2022 13:57:22[[ENDINFO]][[STARTTEXT]]2. Opkald Ikke nødvendigt at opstarte NAC med det samme. S-pcm og ALAT tages som hasteprøver og ses indenfor 2 timer, Hvis ALAT i.a. og s-pcm < 0,1mmol/l, da ej yderligere. [[ENDTEXT]]806543[[STARTINFO]]rlar0142, 16-1-2022 14:42:55[[ENDINFO]][[STARTTEXT]]3. Opkald Konf tpet0025. Ej yderligere. Indskærpes max 4 g Panodil/døgn. [[ENDTEXT]]806556",2022-01-16 12:00:32,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 16-1-2022 12:10:48[[ENDINFO]][[STARTTEXT]]Ringer da hendes far for et par dage siden er faldet og har bøjet nogle ribben. Grundet smerter har han i hvert fald hv. 4 time døgnet rundt - de seneste 2-3 dage taget 2 tabletter. Får ca. hver 3. måned fast kontrolleret sin nyrefunktion, men lidt usikker på hvorfor. Farligt ? [[ENDTEXT]]806524[[STARTINFO]]rlar0142, 16-1-2022 13:57:22[[ENDINFO]][[STARTTEXT]]2. Opkald fra Josephine, læge, Herning 78432183 Skal han have NAC-drop ? [[ENDTEXT]]806543[[STARTINFO]]rlar0142, 16-1-2022 14:42:55[[ENDINFO]][[STARTTEXT]]3. Opkald fra Josefine, læge Herning 78432183 Sidst taget 1 g klokken 8 i morges. Kl. 13.20 : ALAT : 27 og S-pcm 33 mikromol/l ( 0,033 mmol/l). Yderligere ?[[ENDTEXT]]806556",7500.0,Holstebro,79,Panodil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,16
74,NaN,PARACETAMOL,NaN,NaN,2022-01-16 13:57:46,NaN,NaN,NaN,NaN,MED,"[[STARTINFO]]rlar0142, 16-1-2022 13:58:15[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 387851[[ENDTEXT]]806542",2022-01-16 13:52:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Herning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7500.0,Holstebro,79,Panodil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,16

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
81,Risiko for manifest forgiftning,NATRIUMVALPROAT,300,2,2022-01-17 17:48:38,600,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]msoe0664, 17-1-2022 18:00:01[[ENDINFO]][[STARTTEXT]]Risikopatient pga hjertesygdom. Desuden fået over toksisk dosis af både sotalol og quetiapin. Nødt til at indlægges til observation og aktivt kul. Bosted ringer efter transport. [[ENDTEXT]]806871[[STARTINFO]]msoe0664, 17-1-2022 21:20:00[[ENDINFO]][[STARTTEXT]]1 portion aktivt kul. telemetri og tage ekg som gentages. risiko for forlænget QTc og QRS både pga sotalol og quetiapin. obs på rytmeforstyrrelser. desuden risiko for let hypotention og bradykardi / takykardi. Quetiapin antikolignerg virkning herunder obs urinretention. Pga sotalol obs min 12 timer som forlænges ved symptomer. [[ENDTEXT]]806937",2022-01-17 17:11:13,"Sotalol \Mylan\""""",mg,NaN,NaN,NaN,NaN,SOTALOLHYDROCHLORID,80,1,80,MED,NaN,"Quetiapin \STADA\""""",QUETIAPIN FUMARAT,100.0,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]msoe0664, 17-1-2022 18:00:01[[ENDINFO]][[STARTTEXT]]Personale bosted: givet anden beboers medicin til den forkert som er ovenstående. Vanligt får hun Clopixol inj hv 14 dag, og aripiprazol 15mg x 1 dgl, desuden carvedilol, trandolapril, simvastatin, magnyl, furix, mirtazapin. [[ENDTEXT]]806871[[STARTINFO]]msoe0664, 17-1-2022 21:20:00[[ENDINFO]][[STARTTEXT]]Læge Amager hospital: Modtaget patient som er rimelig upåvirket da hun så hende for lidt siden. Tiltag?[[ENDTEXT]]806937",2300.0,København S,76,Delepsine Retard,NaN,NaN,NaN,NaN,NaN,NaN,Fejldosering,NaN,True,18
85,NaN,QUETIAPIN FUMARAT,NaN,NaN,2022-01-17 21:20:07,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-17 21:03:57,"Sotalol \Mylan\""""",NaN,NaN,NaN,NaN,NaN,SOTALOLHYDROCHLORID,NaN,NaN,NaN,MED,Amager hospital,Delepsine Retard,NATRIUMVALPROAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]msoe0664, 17-1-2022 21:20:57[[ENDINFO]][[STARTTEXT]]koblet til 387989[[ENDTEXT]]806936",2300.0,København S,76,QUETIAPIN FUMARAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,18

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
82,Risiko for manifest forgiftning,Ethanol,NaN,70,2022-01-17 14:12:42,NaN,Indlæggelse,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]cdit0001, 17-1-2022 18:20:20[[ENDINFO]][[STARTTEXT]]Symptomatisk behandling. Obs hovedtraume. Størst risiko pga alkoholindtaget.[[ENDTEXT]]806883[[STARTINFO]]cdit0001, 17-1-2022 19:18:02[[ENDINFO]][[STARTTEXT]]Zonoct: ikke risiko for symptomer og slet ikke nu. Se-ethanol. Symptomatisk beh.[[ENDTEXT]]806904",2022-01-17 18:10:43,Zonoct,NaN,mg,NaN,NaN,NaN,ZOLPIDEM TARTRAT,10,3,30,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 17-1-2022 18:20:20[[ENDINFO]][[STARTTEXT]]Har været oppe og skændes med sin kone. Fortæller at han drikker i smug. Tilkaldes fordi han er faldet på badeværelset og slået hovedet. Får en halv Zonoct dagligt[[ENDTEXT]]806883[[STARTINFO]]cdit0001, 17-1-2022 19:18:02[[ENDINFO]][[STARTTEXT]]Er kommet ind. Er vågen og rimelig klar. Har været bevidstløs efter faldet så de vil CTC ham.[[ENDTEXT]]806904",8500.0,Grenaa,83,Alkohol,NaN,NaN,Suicidal/Affekt,Misbrug,NaN,NaN,NaN,NaN,True,19
83,NaN,Ethanol,NaN,NaN,2022-01-17 19:12:39,NaN,NaN,NaN,NaN,DIVERSE,NaN,2022-01-17 19:09:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Randers Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 17-1-2022 19:18:13[[ENDINFO]][[STARTTEXT]]Koblet 387993[[ENDTEXT]]806903",8500.0,Grenaa,83,Alkohol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,19

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
100,Risiko for manifest forgiftning,PARACETAMOL,500,15,2022-01-20 17:46:06,7500,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]anel0004, 20-1-2022 17:59:52[[ENDINFO]][[STARTTEXT]]Toxisk dosis > 4g (risikopatient). Har indtaget toxisk dosis og skal indlægges til behandling kul hvis < end 4 timer siden indtag. NAC behandling efter procedure. [[ENDTEXT]]807719[[STARTINFO]]anel0004, 20-1-2022 21:37:58[[ENDINFO]][[STARTTEXT]]Konf. med MCHR0064. Hold pause 1-2 timer, herefter opstarte næste bolus 16 timer med dråbetæller.[[ENDTEXT]]807755",2022-01-20 17:38:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 20-1-2022 17:59:52[[ENDINFO]][[STARTTEXT]]Er tidligere pillemisbruger, bor nu på plejecenter. Har i eftermiddag (ukendt tid) fået skaffet 13 stk Paracetamol a 500mg og har derudover fået sin vanlige dosis Paracetamol 2 stk. Har også fået 2 stk a 500 mg i morges. Føler hun ryster på hænderne og hun har kvalme. Er det toxisk dosis og skal hun indlægges til behandling.[[ENDTEXT]]807719[[STARTINFO]]anel0004, 20-1-2022 21:37:58[[ENDINFO]][[STARTTEXT]]2 opkald fra spl Andrea Ålborg Sygehus tlf 26135200. Ved en fejl er der givet 1. bolus NAC behandling uden dråvetæller og over en time i stedet for 4 timer. Har fået kvalme, ingen opkastning eller allergisk reaktion. Er der noget der skal gøres? Hvornår kan næste bolus 16 timer startes op?[[ENDTEXT]]807755",2200.0,København N,79,"Paracetamol \Teva\""""",NaN,NaN,NaN,Misbrug,NaN,NaN,NaN,NaN,True,21
101,NaN,PARACETAMOL,NaN,NaN,2022-01-20 21:38:34,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-01-20 21:13:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aalborg Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 20-1-2022 21:38:52[[ENDINFO]][[STARTTEXT]]2 opkald fra spl Andrea Ålborg Sygehus tlf 26135200. Koblet til 388305.[[ENDTEXT]]807753",2200.0,København N,79,paracetamol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,21

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
108,Risiko for begrænset forgiftning,didecyldimethylammoniumchlorid,NaN,NaN,2022-01-21 14:50:16,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]mann0002, 21-1-2022 15:26:24[[ENDINFO]][[STARTTEXT]]Sikkerhedsdatablad fundet. Produktet indeholder bla. didecyldimethylammoniumchlorid < 0,25%. Ufarligt, kan evt få lette GI-gener.[[ENDTEXT]]807875[[STARTINFO]]nhan0003, 21-1-2022 16:36:49[[ENDINFO]][[STARTTEXT]]2 opkald Kan give irritation med kvalme og opkastning. Vil ikke forvente diarre Ved fortsat gener -> ses af vagtlæge Sikre suff væske indtag[[ENDTEXT]]807888",2022-01-21 15:16:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 21-1-2022 15:26:24[[ENDINFO]][[STARTTEXT]]Dement borger på pj.hj. Har indtaget et par mundfulde 'BioCid Desinficering' fra BiGroup.[[ENDTEXT]]807875[[STARTINFO]]nhan0003, 21-1-2022 16:36:49[[ENDINFO]][[STARTTEXT]]2 opkald Beboer haft opkastning x 2 samt diarre x 1 Spiser og drikker uden problemer. Er helt som han plejer at være - sidder oppe i stol [[ENDTEXT]]807888",8310.0,Tranbjerg J,88,Desinfektionsmiddel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,23
109,NaN,NaN,NaN,NaN,2022-01-21 16:30:02,NaN,NaN,NaN,NaN,KEMI,NaN,2022-01-21 16:27:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 21-1-2022 16:32:36[[ENDINFO]][[STARTTEXT]]2 opkald se sag 388373[[ENDTEXT]]807887",8310.0,Tranbjerg J,88,Desinfektionsmiddel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,23

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
110,Ingen risiko,NaN,NaN,NaN,2022-01-22 15:02:33,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]mann0002, 22-1-2022 16:03:00[[ENDINFO]][[STARTTEXT]]Mange malinger indeholder et eller flere opløsningsmidler, dette produkt acetone. Ufarligt at få maling, eller ren acetone for den sags skyld, på en finger. Mon ikke symptomerne skyldes overbelastning i forbindelse med tryk på spraydysen.[[ENDTEXT]]808064[[STARTINFO]]rlar0142, 24-1-2022 12:08:56[[ENDINFO]][[STARTTEXT]]2. Opkald Kan skyldes tryk på finger, blære-dannelse evt. Skal ses og vurderes af egen læge. [[ENDTEXT]]808424",2022-01-22 15:48:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 22-1-2022 16:03:00[[ENDINFO]][[STARTTEXT]]Malet et hegn. Brugte en spraymaling, 'outdoor outdoor' fra Sam Partner. Fået maling på en fingerspids og nu føles denne 'død', i øvrigt samme finger, som han har brugt til at trykke spraydysen. Produktet indeholder acetone, som jo kan optages over huden, hvad nu?[[ENDTEXT]]808064[[STARTINFO]]rlar0142, 24-1-2022 12:08:56[[ENDINFO]][[STARTTEXT]]2. Opkald fra samme 27154011 Nu er det 2 dage siden, og fingerspidsen på pegefingeren virker helt død. Der er også ligesom en væskedannelse under huden. Hvad skal man gøre ved dette ? [[ENDTEXT]]808424",2100.0,København Ø,78,Maling og lak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,24
120,NaN,NaN,NaN,NaN,2022-01-24 12:09:03,NaN,NaN,NaN,NaN,KEMI,"[[STARTINFO]]rlar0142, 24-1-2022 12:10:01[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 388459[[ENDTEXT]]808421",2022-01-24 12:02:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2100.0,København Ø,78,Maling og lak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,24

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
171,Uafklaret risiko,mablet,360,1,2022-02-06 22:32:03,360,Indlæggelse,NaN,Akut forgiftning,SPECIALDONOTDELETE,"[[STARTINFO]]tvan0009, 6-2-2022 22:39:43[[ENDINFO]][[STARTTEXT]]rådes til at kontakte thorax kirurgerne, det vil være dem der skal fiske den op. vi har ingen erfaring med hvad den vil gøre der[[ENDTEXT]]811524[[STARTINFO]]sgre0034, 6-2-2022 23:11:10[[ENDINFO]][[STARTTEXT]]videregivet til nrei0002[[ENDTEXT]]811531[[STARTINFO]]nrei0002, 6-2-2022 23:29:01[[ENDINFO]][[STARTTEXT]]Tlf kontakt til Birgitte, vagthavende ITA, Slagelse, der har taget kontakt til Thoraxkir, der gerne vil hjælpe med at hente tabletten op, er dog betænkelig ved at flytte patienten, da der har været lejringsafhængig desaturation. Vurderer at det er tabletten, der flytter sig rundt i luftvejene. Vurdering: det kan ikke udelukkes at tabletten vil give lokalirritation/affektion af slimhinden i luftvejene. Det anbefales fortsat at tabletten fjernes ved skopisk assistance. Man må klinisk vurdere om patienten er transportabel eller om indgrebet bør udskydes til i morgen, hvor man kan få kirurgisk assistance mhp skopi på stedet.[[ENDTEXT]]811532[[STARTINFO]]sboe0017, 7-2-2022 14:35:20[[ENDINFO]][[STARTTEXT]]#@@@# Opfølgning vi SP opslag mhp yderligere rådgivning: FRA SP: Pt med tab. mablet i venstre hovedbronchus. Er indlagt på intensiv afd,Slagelse ,intuberet. Der blev spurgt indtil om ØNH afd vil stå for bronchoskopi på pt i Slagelse. Plan: Pt diskuteres på ØNH morgen konf og plannen er ØNH vil ikke stå for bronschoskopi i Slagelse.Hvis der er behov for bronchoskopi kan intensiv afdeling kontakt lungemedicinsk afd.Hvis pt kan flyttes til ØNH afd,Køge da, er det muligt for bronkoskopi ved ØNH. UT har kontaktet intensiv overlæge på Slagelse og han er orienteret om ovenstående plan. og fra ITA notat kl 13.30 dd 75 årig kvinde indlagt med respirations besvær efter fejlsynkning af tablet mablet. Nu stabilliseret. Tabletten delvist suget, delvist hostet til tuben i delvist opslemmet form, Ekstuberet uden problemer. Kon formentlig udskrives til stamafd. i morgen. Synkefuntion bør inden endelig udskrivelse vurderes af ergoterapeut. [[ENDTEXT]]811700",2022-02-06 22:29:27,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sygehus Vestsjælland, Slagelse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 6-2-2022 22:39:43[[ENDINFO]][[STARTTEXT]]har pt der har fået tablet galt i lungerne er stabilliseret lungemæssigt tabletten befinder sig i venstre hovedbronchie kan den gøre skade her?[[ENDTEXT]]811524[[STARTINFO]]sgre0034, 6-2-2022 23:11:10[[ENDINFO]][[STARTTEXT]]2. opkald: Vil flytte pt, men er bekymret for om Mablet kan give en ætsende reaktion, og risiko for større skade.[[ENDTEXT]]811531",4200.0,Slagelse,75,mablet,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,31
172,NaN,mablet,NaN,NaN,2022-02-06 23:11:17,NaN,NaN,NaN,NaN,SPECIALDONOTDELETE,NaN,2022-02-06 23:00:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sygehus Vestsjælland, Slagelse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 6-2-2022 23:11:31[[ENDINFO]][[STARTTEXT]]koblet 389827[[ENDTEXT]]811530",4200.0,Slagelse,75,mablet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,31

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
177,Risiko for manifest forgiftning,MORPHINHYDROCHLORID (trihydrate),10,20,2022-02-07 20:58:16,200,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]nhen0047, 8-2-2022 13:25:32[[ENDINFO]][[STARTTEXT]]- Hvis PT skulle blive bevidstheds påvirket, svær og vække eller RF skulle falde, da gives naloxon, startende med 0,3 mg. - PT skal symptomatisk observeres de næste 24 timer, og hvis der gives naloxon da yderligere 6 timer fra sidste indgift. Helst en afd. der kan observere tæt. Kan herefter udskrives eller gå til psyk. - Obs. peristaltik, da morfin kan virke hæmmende og pt har en anal cancer. - Behandling af AfLi. De er velkommen til og ringe igen, ved yderligere udvikling. [[ENDTEXT]]811902[[STARTINFO]]nhen0047, 9-2-2022 10:27:02[[ENDINFO]][[STARTTEXT]]Konf. med hhor0004. utænkeligt det er den morfin der stadig spøger. Forslår de kigger ind i andre årsager, som morfin plaster. nævner de evt. kunne sep. pt's håndtaske, med mistanke om hun kunne selvmedicinere. [[ENDTEXT]]812075[[STARTINFO]]nhen0047, 9-2-2022 11:09:38[[ENDINFO]][[STARTTEXT]]Ud fra instruks oplyser jeg om at de ikke kan give for meget naloxon, dof vis de når til og havde givet 10 mg, da er det tvivlsomt det er opioid forgiftning. og her skal de overveje andre årsager (CNS, CT-C) De kan ved god effekt af naloxon, overveje og hænge et naloxon drop op i stedet, 2-4mg/70kg/timen. De er velkommen til og ringe tilbage ved tvivl. [[ENDTEXT]]812083",2022-02-08 12:46:03,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kbh. Amts Sygehus i Glostrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhen0047, 8-2-2022 13:25:32[[ENDINFO]][[STARTTEXT]]Terminal cancer patient, bringes til hospital, da forsøgt suicidere med 20 tbl. af 10 mg morfin i går aftes. Afstår fra og havde indtaget andet. S-PCM normal. Sidder nu op og spiser mad, let sløv men kan vækkes, når falder hen. Hvornår gives naloxon? Får vanligt quetiapin 50mg depot 2 tbl. til natten, Miazepam 15 mg, 2 tbl til natten, Selo-Zok, PCM. [[ENDTEXT]]811902[[STARTINFO]]nhen0047, 9-2-2022 10:27:02[[ENDINFO]][[STARTTEXT]]2. opkald. kardi. mellem vagt ringer, da PT ved 10 tiden har haft en desat til 72, med blårcyanotiske læber og bevidstheds påvirkning. De giver naloxon 0,4 mg, og pt vågner herefter op og nu SAT på 96 uden O2. Kan det være morfinen der er taget for 2 døgn siden der stadig spøger?[[ENDTEXT]]812075[[STARTINFO]]nhen0047, 9-2-2022 11:09:38[[ENDINFO]][[STARTTEXT]]3. opkald. De er i tvivl om hvor meget naloxon de må give i alt, er fortsat bevidsthedspåvirket, vågner forsat op af naloxon, der er nu givet 0.8 mg naloxon. [[ENDTEXT]]812083",2630.0,Taastrup,85,"Morfin \SAD\""""",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,32
179,NaN,MORPHINHYDROCHLORID (trihydrate),10,NaN,2022-02-09 10:14:16,NaN,NaN,NaN,Akut forgiftning,MED,NaN,2022-02-09 10:01:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kbh. Amts Sygehus i Glostrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhen0047, 9-2-2022 10:17:03[[ENDINFO]][[STARTTEXT]]Se koblede sag. [[ENDTEXT]]812073",2630.0,Taastrup,85,"Morfin \SAD\""""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,32

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
201,Risiko for livstruende forgiftning,OXYCODONHYDROCHLORID,NaN,NaN,2022-02-13 15:45:08,NaN,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]mhen0054, 13-2-2022 16:02:29[[ENDINFO]][[STARTTEXT]]Potentiel livstruende forgiftning, med god prognose, dels kort tid siden indtag, gode behandlingsmuligheder med kul, NAC, antidoter NLX FLZ. Vejledt til brug af NLX, obs rebound effekt contalgin. Tilbageholdenhed med FLZ. Vejledt til indgift max. dosis kul, eller så meget han kan klare, obs bezoar-risiko. Ilt på næsekat. Løbende A-pkt afhængig af klinik. Alm. blodpr. lever-nyretal, tox. Ekg, evt. telemetri. Ring endelig igen ved behov. [[ENDTEXT]]812951[[STARTINFO]]pnie0076, 13-2-2022 17:45:19[[ENDINFO]][[STARTTEXT]]opfølgfende kontakt til anæstesi FV (79406123): stadig uklart hvor mange tbl der kan være indtaget. Vågnede lidt mere op ved yderligere naloxon, men falder hurtigt hen. Hustruen, som er på vej for at uddybe anamnesen, har registreret samtlige piller i torsdags, da pt fyldte sin medicinæske. Vanlig medicin: contalgin, saroten, lyrica, mirtazapin, pamol, lamotrigin, propranolol. Det er uvist om pt har indtaget overdosis af andet end pamol og contalgin. OBS for risiko for udtalt kardiel påvirkning grundet propranolol, hvilket lægen er klar over. Kardiologen i huset er kontaktet mhp akut ekko og evt overflytning til center med ECMO. Pt får vist propranolol mod bradykardi uden anden somatisk sygdom. er hverken lever- eller nyresyg. negativ salicylat og ethanol, s-pcm foreligger ikke endnu. fortsat upåfaldende a-gas udover forhøjet laktat på 5. Ny kontakt ved behov, har fået mit direkte nr. [[ENDTEXT]]812982[[STARTINFO]]pnie0076, 13-2-2022 18:32:10[[ENDINFO]][[STARTTEXT]]opkald fra anæstesi FV (79406123): s-pcm på 6.000micromol/L 4-6 timer efter indtag (dog ukendt indtagelsestidspunkt). Det bekræfter blot overdosering. Fortsat NAC, og s-pcm hver 4. time. Hvis familien bekræfter indtag af 300tbl og især hvis propranolol også er indtaget, kan man overveje gastroskopi for at fjerne evt bezoar. Selv om pillerne ikke er rtg fast, vil den monstrøser mængde tbl kunne ses som en stor klump i maven, alternativt kan en CT overvejes inden evt gastroskopi. [[ENDTEXT]]813001[[STARTINFO]]pnie0076, 13-2-2022 23:42:19[[ENDINFO]][[STARTTEXT]]kl 20.30 opkald fra anæstesi FV (79406123): s-pcm på 4.600micromol/L nu 6-8 timer efter formodet indtag. fortsat GCS 10, spontan vejrtrækning, fortsat normal a-gas undtagen laktat på 5,4, normal blodsukker, normal nyrefunktion, ALAT steg fra 40 til 70, ikke kendt med alkoholmisbrug, har pacemaker, EKG uændret ift tidligere og normal ekko. Har fået lavet OOA uden tegn på store klumper i ventriklen/duodenum. Selv om tbl ikke er røntgen faste, ville et evt bezoar med 300 tbl kunne ses. Fortsat NAC i vanlige dosis og s-pcm hver 4. time, vi kan ikke sige med sikkerhed endnu at koncentrationen er sikkert faldende grundet sandsynlig pågående og uregelmæssig absorption. ny kontakt ved behov og opfølgning i morgen.[[ENDTEXT]]813039[[STARTINFO]]nhan0003, 14-2-2022 00:04:10[[ENDINFO]][[STARTTEXT]]4 opkald Ovenstående gentaget[[ENDTEXT]]813049[[STARTINFO]]hhor0004, 14-2-2022 12:13:41[[ENDINFO]][[STARTTEXT]]Lige på grænsen til dialyse på paracetamol, anbefaler man dobler NAC dosis. Fornyet kontakt ved behov[[ENDTEXT]]813131[[STARTINFO]]nhan0003, 15-2-2022 07:20:29[[ENDINFO]][[STARTTEXT]]5 opkald Sag videregives til HHOR[[ENDTEXT]]813314[[STARTINFO]]hhor0004, 15-2-2022 07:33:08[[ENDINFO]][[STARTTEXT]]Påfaldende lav ALAT på 116, INR 1,8 men er i NAC behandling. Nyretal OK lidt febril. Bliver enige om at kontinuere NAC regime [[ENDTEXT]]813316",2022-02-13 15:31:25,ZOLPIDEM TARTRAT,NaN,mg,mg,NaN,NaN,ZOLPIDEM TARTRAT,10,10,100,ZZMED,Vejle Sygehus,Panodil,PARACETAMOL,500.0,NaN,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mhen0054, 13-2-2022 16:02:29[[ENDINFO]][[STARTTEXT]]Med. akut kald Randers AKM. Set af pårørende ved middagstid, uvist hvem der finder ham senere. Skrevet afskedsbrev. Reddere vurderet at der er indtaget ca. 300 tbl PCM, 100 mg Zolpidem, ukendt mængde Contalgin. Kastet op i ambulance, med 25.-30 tbl PCM. GCS 8 ved ankomst, stiger til GCS 11 efter 3 x 0,2 mg NLX. Er ved at få kul på sonde, NAC iværksættes. Pupiller reager for lys, miotiske 3mm. A-pkt laktat 5,5, øvrige ia. Anæstesi til stede. Får dagligt Lamotrigin, Mirtazapin, samt TCA-præparat. Ønsker råd. [[ENDTEXT]]812951[[STARTINFO]]nhan0003, 14-2-2022 00:04:10[[ENDINFO]][[STARTTEXT]]4 opkald Med bagvagt Frederiks. Vil gerne høre hvad der er blevet sagt kl 20.30, da det ikke er skrevet i journal[[ENDTEXT]]813049[[STARTINFO]]nhan0003, 15-2-2022 07:20:29[[ENDINFO]][[STARTTEXT]]5 opkald Anæst bagvagt Lisa: 79406122 Pt tiltagende dårlig' Febril: 39.8 P: 160[[ENDTEXT]]813314",5500.0,Middelfart,77,OxyContin,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,38
204,NaN,PARACETAMOL,NaN,NaN,2022-02-14 00:01:54,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-02-13 23:57:52,OXYCODONHYDROCHLORID,NaN,NaN,NaN,NaN,NaN,OXYCODONHYDROCHLORID,NaN,NaN,NaN,ZZMED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 14-2-2022 00:03:13[[ENDINFO]][[STARTTEXT]]4 opkald se sag 390405[[ENDTEXT]]813048",5500.0,Middelfart,77,paracetamol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,38

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
224,Risiko for manifest forgiftning,PARACETAMOL,500,12,2022-02-17 17:30:20,6000,Skadestue,NaN,Kronisk forgiftning,MED,"[[STARTINFO]]nhan0003, 17-2-2022 19:51:35[[ENDINFO]][[STARTTEXT]]Indlægges til acut biokemi: P-pcm, ALAT, INR mhp evt videre tiltag[[ENDTEXT]]813957[[STARTINFO]]nhan0003, 17-2-2022 21:25:39[[ENDINFO]][[STARTTEXT]]2 opkald Acut biokemi som ovenstående Smerteplan[[ENDTEXT]]813969",2022-02-17 19:47:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 17-2-2022 19:51:35[[ENDINFO]][[STARTTEXT]]Har pga smerter dagligt indtaget 1 g Paracetamol hver 4 time, sidst indtaget kl 17.30, men kan måske have taget flere Ingen abdominal smerter[[ENDTEXT]]813957[[STARTINFO]]nhan0003, 17-2-2022 21:25:39[[ENDINFO]][[STARTTEXT]]2 opkald Læge Elena. Hillerød hospital Tlf: 70803919 Pt ændret forklaring mener Paracetamol er indtaget x 3 daglig, men er lidt usikker på hvormeget hun reelt har indtaget[[ENDTEXT]]813969",3550.0,Slangerup,74,Panodil,NaN,NaN,NaN,NaN,NaN,NaN,Fejldosering,NaN,True,41
225,NaN,PARACETAMOL,NaN,NaN,2022-02-17 21:24:33,NaN,NaN,NaN,NaN,ZZMED,NaN,2022-02-17 21:03:56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hillerød Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 17-2-2022 21:24:43[[ENDINFO]][[STARTTEXT]]2 opkald se sag 390798[[ENDTEXT]]813968",3550.0,Slangerup,74,paracetamol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,41

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],is_duplicate,dup_case_id
235,Risiko for livstruende forgiftning,NaN,NaN,1,2022-02-19 21:27:19,NaN,Indlæggelse,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]anel0004, 19-2-2022 21:39:41[[ENDINFO]][[STARTTEXT]]Enhver udsættelse for koncentrerede stærke syre er potentielt farlig, hovedrisikoen er skader i svælget med påvirkning af luftveje evt. aspiration til luftveje og ætsning af ventrikel og spiserør. Sikring af luftveje. Skylning af munden. Skal til hospital med ØNH eller Thoraxkir. Hospital ringe til GL. [[ENDTEXT]]814419[[STARTINFO]]anel0004, 19-2-2022 22:06:12[[ENDINFO]][[STARTTEXT]]Gentager ovenstående. Der kan være fravær af ætsning i mund. Aktivt kul og ventrikelaspiration er ikke mulig behandling. Hvis der ikke er Thoraxkir, så kontakte Rigshospital Thorax kir. Ved risiko for ætsning af mave-tarm kanal: Hæmoglobin, hæmatokrit, kreatinin, koagulationsfaktorer, syre-basestatus og elektrolyter, blodtype og forlig. Ring igen ved behov når pt er modtaget og der vides mere.[[ENDTEXT]]814438[[STARTINFO]]lhoe0021, 19-2-2022 23:05:50[[ENDINFO]][[STARTTEXT]]4. opkald. Giv gerne et glas væske at drikke. Pt er undersøgt og vurderet sufficient i somatisk regi. Psykiatrisk opfølgning.[[ENDTEXT]]814452",2022-02-19 21:21:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 19-2-2022 21:39:41[[ENDINFO]][[STARTTEXT]]Ambulance på vej til borger, der skulle have drukket 1 liter toiletrens. De har ikke yderligere oplysninger pt. Hvad skal de være opmærksom på?[[ENDTEXT]]814419[[STARTINFO]]anel0004, 19-2-2022 21:41:19[[ENDINFO]][[STARTTEXT]]2 opkald fra Læge på Køge sygehus. Forsøger gentagne gange at ringe retur, men får ikke kontakt tmed lægen.[[ENDTEXT]]814428[[STARTINFO]]anel0004, 19-2-2022 22:06:12[[ENDINFO]][[STARTTEXT]]3. opkald fra læge Køge sygehus 21560260. Har ikke modtaget pt, men vil høre hvad behandling er. Der er muligvis ikke tale om en hel liter, produktet kendes ikke. Hvad skal behandles?[[ENDTEXT]]814438[[STARTINFO]]lhoe0021, 19-2-2022 23:05:50[[ENDINFO]][[STARTTEXT]]4. opkald. Tony læge, Køge akutmodtagelse. 47321499 Pt beskriver selv at have indtaget 1 mundfuld men straks spyttet ud for han kunne ikke synke væsken da den smagte dårligt. Eksponering er dermed reduceret betragteligt ift initialt. Meget snakkende pt, multi-morbid med lungesygdom. ØNH har tilset pt, og ingen fund sv.t ætsning i mundhulen. Pt er asymptomatisk. Psykiatrisk opfølgning.Ved ikke om pt har fået væske at drikke efter eksponering.[[ENDTEXT]]814452",4652.0,Hårlev,73,Toiletrengøring,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,42
236,NaN,NaN,NaN,NaN,2022-02-19 21:59:50,NaN,NaN,NaN,Akut forgiftning,KEMI,NaN,2022-02-19 21:53:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 19-2-2022 22:01:10[[ENDINFO]][[STARTTEXT]]3. opkald fra læge Køge sygehus 21560260. Koblet til 390985.[[ENDTEXT]]814435",4652.0,Hårlev,73,Toiletrengøring,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,True,42
237,NaN,NaN,NaN,NaN,2022-02-19 23:00:46,NaN,NaN,NaN,NaN,KEMI,NaN,2022-02-19 22:55:36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]lhoe0021, 19-2-2022 23:02:45[[ENDINFO]][[STARTTEXT]]4. opkald 390985[[ENDTEXT]]814451",4652.0,Hårlev,73,Toiletrengøring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,42

Merging the duplicate cases:
- Collapses every duplicate cluster (same dup_case_id) into a single row  
- Concatenates all textual information, but for any non-string column simply keeps the first non-blank value that occurs in the cluster  
- Removes the original duplicate rows from young_filtered / old_filtered and appends the merged rows instead (so the variables young_filtered and old_filtered now contain one row per case)  
- Shows the first 20 merged cases from each sheet

In [5]:
from IPython.display import display, HTML
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# column name used for chronological ordering inside a cluster
# (needed only if you want the “first non-blank value” to come
#  from the earliest row)
# ------------------------------------------------------------
DATE_COL = '[today(oprettelse)]'


def _merge_one_cluster(grp: pd.DataFrame,
                       prototype: pd.DataFrame) -> dict:
    """
    Collapse *grp* (all rows of one dup_case_id) into one dict
    that later becomes a single dataframe row.
    """
    # sort by date so “first non-blank” really means earliest
    if DATE_COL in grp.columns:
        grp = grp.sort_values(DATE_COL)

    row = {}
    for col in prototype.columns:        # use dtypes of the full data-frame
        ser = grp[col].dropna()

        if ser.empty:                    # everything is NaN
            row[col] = np.nan
            continue

        if prototype[col].dtype == object or pd.api.types.is_string_dtype(
                prototype[col].dtype):

            # collect unique non-blank strings and glue them together
            vals = [str(v) for v in ser.unique() if str(v).strip() != ""]
            row[col] = " | ".join(vals) if vals else np.nan
        else:
            # numeric / bool / datetime  → first non-blank value
            row[col] = ser.iloc[0]

    # keep the duplicate-tracking columns
    row["dup_case_id"]  = grp["dup_case_id"].iloc[0]
    row["is_duplicate"] = True
    return row


def merge_duplicate_cases(df: pd.DataFrame, dup_df: pd.DataFrame) -> pd.DataFrame:
    """
    Return *df* where every cluster of duplicate rows found in *dup_df*
    has been replaced by one merged row.
    """
    if dup_df.empty:
        return df

    # build one merged row per duplicate case ----------------------------
    merged_rows = [
        _merge_one_cluster(grp, df)
        for _, grp in dup_df.groupby("dup_case_id", sort=False)
    ]
    merged_df = pd.DataFrame(merged_rows, columns=df.columns.tolist()
                                               + ["dup_case_id", "is_duplicate"])

    # remove all original duplicate rows and append the merged ones -------
    df_no_dups = df.drop(index=dup_df.index)
    result = pd.concat([df_no_dups, merged_df], ignore_index=True)

    return result


# -----------------------------------------------------------------------
# apply to both age groups
# -----------------------------------------------------------------------
young_filtered = merge_duplicate_cases(young_filtered, young_dups)
old_filtered   = merge_duplicate_cases(old_filtered,   old_dups)

In [6]:
# -----------------------------------------------------------------------
# show the first 20 merged cases from each sheet
# -----------------------------------------------------------------------
def show_merged_cases(df: pd.DataFrame, label: str, n: int = 20):
    mask = df.get("is_duplicate", False)

    # make sure the mask is a proper Boolean Series
    if not isinstance(mask, pd.Series):
        mask = pd.Series(mask, index=df.index)
    mask = mask.fillna(False).astype(bool)

    subset = df[mask].head(n)          # only merged rows
    if subset.empty:
        display(HTML(f"<h3>{label}: no merged cases</h3>"))
    else:
        display(HTML(f"<h3>{label} – first {len(subset)} merged cases</h3>"))
        with pd.option_context("display.max_columns", None,
                               "display.max_colwidth", None,
                               "display.width", None):
            display(subset)


show_merged_cases(young_filtered, "YOUNG SHEET", n=20)
show_merged_cases(old_filtered,   "OLD SHEET",   n=20)

C:\Users\danam\AppData\Local\Temp\ipykernel_5020\2127935295.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  mask = mask.fillna(False).astype(bool)

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],dup_case_id,is_duplicate
133137,Risiko for livstruende forgiftning,QUETIAPIN FUMARAT,25,70,2021-12-31 23:30:21 | 2022-01-02 11:11:04,1750,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED | ZZMED,"[[STARTINFO]]anel0004, 1-1-2022 17:07:17[[ENDINFO]][[STARTTEXT]]Svært forgiftet pt: Telemetri i minimum 12 timer, eller indtil der kun har været lette forgiftningssymptomer i 6 timer. Lette symptomer er mild sedation.[[ENDTEXT]]803246",2022-01-01 16:52:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kolding Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 17:07:17[[ENDINFO]][[STARTTEXT]]Har for 17,5 time siden indtaget ukendt dosis Quetiapin. Blev indlagt i morges kl 5 med GCS 3, kom på intensiv og blev intuberet. EKGer er taget hv. 2 time alle har været i.a., har ligget i Telemetri. Er nu vågnet op og kun let sløv har det ellers godt. Hvor længe skal han overvåges med Telemetri/EKG, afgørende for hvor han kan overflyttes til.[[ENDTEXT]]803246 | [[STARTINFO]]nhan0003, 2-1-2022 11:17:22[[ENDINFO]][[STARTTEXT]]2 opkald se sag 386486[[ENDTEXT]]803368",7000,Fredericia,46.0,"Quetiapin \1A Farma\"""" | QUETIAPIN FUMARAT",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,15.0,True
133138,NaN,PARACETAMOL,665,9,2022-01-01 18:18:18 | 2021-12-31 20:00:27,5985,NaN,NaN,NaN,MED | ZZMED,"[[STARTINFO]]rlar0142, 1-1-2022 18:19:15[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 38651[[ENDTEXT]]803267",2022-01-01 18:12:38,Alkohol,NaN,NaN,NaN,NaN,NaN,Ethanol,NaN,NaN,NaN,DIVERSE,Sygehus Viborg,Fortamol,"CODEINPHOSPHATHEMIHYDRAT, PARACETAMOL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus | Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 19:34:33[[ENDINFO]][[STARTTEXT]]3. opkald fra læge Stewen Viborg sygehus tlf 78449681. Koblet til 386521.[[ENDTEXT]]803271",7870,Roslev,15.0,Panodil | paracetamol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,True
133139,Risiko for livstruende forgiftning,Ethanol,NaN,NaN,2022-01-01 19:30:21 | 2022-01-01 22:32:43,NaN,Indlæggelse,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]anel0004, 1-1-2022 21:18:05[[ENDINFO]][[STARTTEXT]]Toxiak dosis depot > 4mg/kg; Alm tbl > 3mg/kg. Symptomer takykardi, svimmelhed, agitation, brystsmerter, mavesmerter, muskelrykninger og tremor, kramper og hypertermi. På hospital til behandling med kul og til symptomatisk behandling med fokus på respiration, cirkulation og kramper.[[ENDTEXT]]803299[[STARTINFO]]rlar0142, 1-1-2022 22:32:34[[ENDINFO]][[STARTTEXT]]2. Opkald Som ovenstående. Har taget solid toksisk dosis og depotformuleret. Fint med kul nu, gentag også om 2 timer atter ½ portion kul. Risiko er overstimulation med muskeluro, agitation evt. kramper. Ved symptomer, da Diazepam 5-10 mg iv, der efter 2 minutter kan gentages til respons. Tæt obs af vitalparametre. Ad EKG : QTc forlængelse ikke helt typisk for Methylphenidat-indtag. Gentag EKG og ved fortsat påvirkning, da telemetri. Ved brystsmerter coronarenzymer. Syrebase-status obs. Ved muskeluro/kramper, da rhabdomyolyse-tal. Obs i 12 timer. Alkohol promille kan dæmpe overstimulation. Velkommen til at kontakte GL ved yderligere. [[ENDTEXT]]803308[[STARTINFO]]rlar0142, 2-1-2022 10:52:16[[ENDINFO]][[STARTTEXT]]3. Opkald. Nu > 12 timer fra indtag. Kan fortsætte obs i psyk. regi. [[ENDTEXT]]803363 | [[STARTINFO]]rlar0142, 1-1-2022 22:33:12[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 386562[[ENDTEXT]]803307",2022-01-01 21:00:35,METHYLPHENIDATHYDROCHLORID,NaN,mg,NaN,NaN,NaN,METHYLPHENIDATHYDROCHLORID,27,29,783,ZZMED,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 21:18:05[[ENDINFO]][[STARTTEXT]]Opkald fra ambulance der er på vej til kvinde, som skulle have indtaget 100 stk Ritalin ukendt dosis, tid og om det er fast medicin. Ved ikke hvilke symptomer borger har. Hvad skal de være opmærksomme på?[[ENDTEXT]]803299[[STARTINFO]]rlar0142, 1-1-2022 22:32:34[[ENDINFO]][[STARTTEXT]]2. Opkald fra læge Roskilde sygehus 61922550 Modtaget ovenstående, der havde taget 29 tabletter af egne - ikke 100 stk (rettet i giftstof). Endvidere drukket alkohol ( Tilføjes i giftstof). Får ikke anden medicin. Man har givet 1 portion kul nu. Vågen og kan bidrage til anamnese i baggrunden. BT 146/107, p. 88, tp 36,0, rf i.a., EKG med QTc 510 p. 97. Der er taget relevant biokemi samt s-ethanol, s-salicylat, s-pcm. Behandling ? [[ENDTEXT]]803308[[STARTINFO]]rlar0142, 2-1-2022 10:52:16[[ENDINFO]][[STARTTEXT]]3. Opkald fra Roskilde sygehus 61922550 Haft ovenstående til observation natten igennem. Senere EKG med QTc i.a. Upåvirket . Ikke haft behov for Diazepam. Fik de 2 portioner kul. Yderligere nu ? [[ENDTEXT]]803363",4000,Roskilde,44.0,Alkohol,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,54.0,True
133140,Uafklaret risiko | Risiko for manifest forgiftning,LEVOTHYROXINNATRIUM,50,100,2022-01-01 22:26:13 | 2022-01-01 21:45:53,5000,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]anel0004, 1-1-2022 22:32:08[[ENDINFO]][[STARTTEXT]]Toxisk dosis Mere end eller lig 2000 mikrogram. Symptomdebut generelt efter 24 timer og varighed er ca 12-48 timer. Symptomer Tremor, varmefornemmelse/svedtendens, hypertermi, Ændret mentaltilstand også agitation, kramper, svær hypertension og arytmier. Kul kan gives op til 4 timer efter indtag. Vurdere om det er en akut eller kronisk forgiftning, obs blandingsforgiftninger feks BZD.[[ENDTEXT]]803310 | [[STARTINFO]]mhen0054, 2-1-2022 01:26:41[[ENDINFO]][[STARTTEXT]]Mild/moderat forgiftning. Indlæggelse/observation afhænger af symptomer. Der kan komme symptomer (milde) med latens op til flere dage. Såfremt kun milde, efter 8 timer, kan observation afsluttes, men med opfølgning op til 2 uger, evt. via EL. [[ENDTEXT]]803331",2022-01-01 22:18:13,NaN,mikrogram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kbh. Amts Sygehus i Glostrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 1-1-2022 22:32:08[[ENDINFO]][[STARTTEXT]]Ambulance på vej til ovenstående. Har fået meldt, borger har indtaget Eltroxin kender ikke dosis eller tid. Borger skulle være agiteret og have låst sig inde. Hvad er toxisk dosis og symptomer?[[ENDTEXT]]803310 | [[STARTINFO]]mhen0054, 2-1-2022 01:26:41[[ENDINFO]][[STARTTEXT]]Egen medicin. Får også Sertralin, ikke OD med dette. VKO, fri resp, upåvirket. A-pkt ia. Fået kul.Taget relevante blpr og Ekg. Hvor længe observation ?[[ENDTEXT]]803331",2620,Albertslund,25.0,Eltroxin,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,60.0,True
133141,Risiko for livstruende forgiftning,Cocain,NaN,10,2021-12-28 03:09:41 | 2022-01-02 11:10:52,NaN,Indlæggelse,NaN,Akut forgiftning,RUS,"[[STARTINFO]]cdit0001, 28-12-2021 04:55:42[[ENDINFO]][[STARTTEXT]]Indtil den er ude tæt overvågning af vitalparametre. Ved tegn på læk da dillaterede pupiller, takykardi, hypertension, stigende tp. BZD, aktiv køling. Symptomatisk behandling.[[ENDTEXT]]802183 | [[STARTINFO]]rlar0142, 2-1-2022 11:11:22[[ENDINFO]][[STARTTEXT]]Se koblet sag nummer : 386551[[ENDTEXT]]803365",2021-12-28 04:35:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hvidovre Hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 28-12-2021 04:55:42[[ENDINFO]][[STARTTEXT]]For 1½ time siden var han hjemme og så bankede det på døren. Han skyndte sig at proppe en pose op i endetarmen med 10 gram kokain. Tog heroin og er kommet ind. Er meget nervøs og sveder. Er i tvivl om hvor godt posen er lukket og har ikke kunne få den ud. Der er kaldt en gas.kir for at hjælpe med proceduren med at forsøge at få den ud. Er overvåget på telemetri. BT normalt.[[ENDTEXT]]802183",2450,København SV,49.0,Kokain,NaN,NaN,NaN,Misbrug,NaN,NaN,NaN,NaN,22.0,True
133142,Risiko for manifest forgiftning,stærk base,NaN,NaN,2022-01-02 14:18:35 | 2022-01-02 14:18:06,NaN,Skadestue,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]rlar0142, 2-1-2022 14:28:10[[ENDINFO]][[STARTTEXT]]Ætsende base. Risiko for alvorlige og dybe skader på grund af forsæbning. Skyl atter kontinuerligt. Langvarig skylning kan være påkrævet. Skylning skal pågå til der kan måles neutral surhedsgrad i huden - på skadestuen. [[ENDTEXT]]803411[[STARTINFO]]anel0004, 2-1-2022 15:25:43[[ENDINFO]][[STARTTEXT]]Gentager ovenstående.[[ENDTEXT]]803428",2022-01-02 14:21:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger | Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 2-1-2022 14:28:10[[ENDINFO]][[STARTTEXT]]Kommet til at spilde nogle dråber over fingre. Kunne med det samme mærke det. Skyllede grundigt med det samme, men lidt fedtet, der hvor han har ramt. Farligt ? [[ENDTEXT]]803411[[STARTINFO]]anel0004, 2-1-2022 15:25:43[[ENDINFO]][[STARTTEXT]]2 opkald fra Frederik på 1813. Har nu skyllet finger en time, har kontaktet 1813, hvad har GL anbefalet af videre plan.[[ENDTEXT]]803428 | [[STARTINFO]]anel0004, 2-1-2022 15:26:12[[ENDINFO]][[STARTTEXT]]2 opkald fra Frederik på 1813. Koblet til 386615.[[ENDTEXT]]803425",2300,København S,23.0,Afløbsrens,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,True
133143,Risiko for manifest forgiftning,QUETIAPIN FUMARAT,25,20,2022-01-02 19:15:54 | 2022-01-02 22:19:13,500,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,"[[STARTINFO]]nhan0003, 2-1-2022 20:23:17[[ENDINFO]][[STARTTEXT]]Skal indlægges til behandling[[ENDTEXT]]803483[[STARTINFO]]nhan0003, 2-1-2022 22:24:34[[ENDINFO]][[STARTTEXT]]2 opkald Sympt 1-6 timer efter tbl indtag. CNS påvirkning, anticholinerge symptomer, EPS Aktivt kul Symptomatisk beh. OBs vitalparametre med fokus på CNS, BT; P, resp, SAT, tp. Kontrol EKG hv 2 time / mindst 6 timer / Telemetri ved QTc > 500 ms Biokemi: elektrolytter, lever- nyretal, Mg, Ca, pcm, salicylat, A.pkt Ved lette / ingen forgiftningssymptomer i mindst 6 timer kan obs afsluttes.[[ENDTEXT]]803516",2022-01-02 20:16:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Randers Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 2-1-2022 20:23:17[[ENDINFO]][[STARTTEXT]]Taget i suicidal øjemed. Udskrevet i formiddags efter at have taget sovemedicin d 01-01 Ringede til søn umiddelbart efter indtag Vanlig Tbl Quetiapin 25 mg pn x 1[[ENDTEXT]]803483[[STARTINFO]]nhan0003, 2-1-2022 22:24:34[[ENDINFO]][[STARTTEXT]]2 opkald Indlagt på Randers sygehus / acutmodt. Læge Maria Tlf: 78420320 Udskrevet kl 12.25 efter psyk tilsyn. Er vågen og klar, ked af det. Medvirker ikke til anamnese. BT: 155/ P: 89 Afebril. Opkastning x 1 EKG: QTc: 406 ms / frekvens: 83[[ENDTEXT]]803516 | [[STARTINFO]]nhan0003, 2-1-2022 22:19:26[[ENDINFO]][[STARTTEXT]]2 opkald se sag 386647[[ENDTEXT]]803515",8920,Randers NV,49.0,QUETIAPIN FUMARAT,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,56.0,True
133144,Risiko for manifest forgiftning,"ACETYLSALICYLSYRE, CODEINPHOSPHATHEMIHYDRAT, Magne",500,40,2022-01-02 17:00:48 | 2022-01-03 00:40:13,20000,Indlæggelse,NaN,Akut forgiftning,MED,"[[STARTINFO]]mann0002, 2-1-2022 23:48:44[[ENDINFO]][[STARTTEXT]]Pt har indtaget 260 mg/kg, vejledende vil dette give en moderat forgiftning, MEN forgiftningen skal vurderes samlet udfra syrebase, symptomer og se-salicylat. Der kan ses Tinitus kvalme, opkastning, sløvhed, kramper, metabolisk acidose, koagulationsforstyrrelser. Obs at hver tbl indeholder kodein 9,6 mg, indtaget svarer til et indtag på 384 mg kodein. Se-salicylat skal tages nu og hver 2. time til faldende niveau > 1,5 mmol/l. Pt skal have en dobbeltportion kul. Forebyggende gives K-vitamin 10 mg iv. Evt videre eliminering vha alkalinisering og hæmodialyse, dette udfra se-salicylat. Spørger guides frem til Instruks på Acetylsalicylsyre. Ring meget igen ang videre behandling. Symptomatisk behandling. [[ENDTEXT]]803529[[STARTINFO]]mann0002, 3-1-2022 00:39:43[[ENDINFO]][[STARTTEXT]]2. opkald. Hurtigt inf. som ovenstående. Spørger også guidet frem til instruks. Alkalinisering af urin ska påbegyndes. Se-salicylat hver 2. time til < 1,5 mmol/l. Øvrige blodprøver i flg instruks. Konf. m. sboe0017 [[ENDTEXT]]803535",2022-01-02 23:23:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Herlev,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 2-1-2022 23:48:44[[ENDINFO]][[STARTTEXT]]Indtaget for 6 1/2 time siden. Pt er træt, har tinnitus. Oplyser at han hjemme har haft en mørk, måske kaffegrumslignende opkastning. [[ENDTEXT]]803529[[STARTINFO]]mann0002, 3-1-2022 00:39:43[[ENDINFO]][[STARTTEXT]]2. opkald. Spørger har netop overtaget pt. Der er givet kul og Konakion. Se-salicylat 4,3 mmol/l. Se-ka og se.Na ia. Leucocytter 19,5, CRP ia, pt afebril[[ENDTEXT]]803535 | [[STARTINFO]]mann0002, 3-1-2022 00:40:30[[ENDINFO]][[STARTTEXT]]Reg. af 2. opkald på sag nr 386667[[ENDTEXT]]803534",2860,Søborg,18.0,"Kodimagnyl Ikke-stoppende \DAK\""""",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,163.0,True
133145,Uafklaret risiko,Cocain | Dinitrogenoxid 100%,NaN,NaN,2021-12-31 02:10:55 | 2022-01-03 17:12:14,NaN,Skadestue,NaN,Akut forgiftning,RUS,"[[STARTINFO]]mann0002, 3-1-2022 02:13:33[[ENDINFO]][[STARTTEXT]]Skal ses af læge.[[ENDTEXT]]803531[[STARTINFO]]sgre0034, 3-1-2022 17:18:47[[ENDINFO]][[STARTTEXT]]Symptomer på kronisk misbrug af lattergas ses typisk ved at pt får neurologiske symptomer, feks i form af følesforstyrrelser. Skal sættes i behandling B12 vitamin, startes med 1 mg im, herefter feks. Betolvex og Folsyre. Evt konf. neurologisk afd. Observation afhængig af symptomer. Kan evt følges op af egen læge, hvis det vurderes at pt kan udskrives i dag![[ENDTEXT]]803705",2022-01-03 01:49:04,Lattergas,NaN,NaN,NaN,NaN,NaN,Dinitrogenoxid 100%,NaN,NaN,NaN,RUS,Bispebjerg Hospital,Alkohol,Ethanol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DIVERSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 3-1-2022 02:13:33[[ENDINFO]][[STARTTEXT]]Har d. 31/12/21 indtaget alkohol, cocain og lattergas. I døgnet efter hjertebanken, i dag episoder med panikangst og huden i den ene siden af ansigtet er følelsesløs. Er ikke hyppig bruger af lattergas, har prøvet det 4-5 x tidligere, med lange intervaller. [[ENDTEXT]]803531[[STARTINFO]]sgre0034, 3-1-2022 17:18:47[[ENDINFO]][[STARTTEXT]]2. opkald fra BBH akutlæge Andre 30527293: Pt nu indlagt. Har et misbrug af lattergas, angiver at have tage høje doser 12-13 gange tidligere, måske mere! Har ikke indtaget noget siden nytårsaften Har føleforstyrrelser, men er ikke udtalte, og følelsen af angstprovokeret åndenød. Har ikke neuropati[[ENDTEXT]]803705 | [[STARTINFO]]sgre0034, 3-1-2022 17:18:58[[ENDINFO]][[STARTTEXT]]koblet 386668[[ENDTEXT]]803702",9999,Ukendt,22.0,Kokain | Lattergas,NaN,NaN,NaN,Misbrug,NaN,NaN,NaN,NaN,167.0,True

C:\Users\danam\AppData\Local\Temp\ipykernel_5020\2127935295.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  mask = mask.fillna(False).astype(bool)

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)],dup_case_id,is_duplicate
7355,Risiko for manifest forgiftning,LITHIUMCITRAT,6,2,2022-01-03 16:28:40 | 2022-01-05 09:56:41,12,Indlæggelse,Psykiatriske sygdomme,Kronisk forgiftning,ZZMED,"[[STARTINFO]]sgre0034, 3-1-2022 16:51:24[[ENDINFO]][[STARTTEXT]]S-konc. følges hver 4. time, skal ligge <1,0 mmol/L Har symptomer på forgiftning., samt påvirket nyrefunktion. Litarex sep. Skal behandles med væske, sikre diureser 2 ml/kg/time, OBS dehydrering. Der kan hæmodialyseres, men dette kun i tilfælde af s-lithium >0,4 mmol/ hos pt med nedsat nyrefunktion. Risiko for arytmier, skal lægges i telemetri, OBS EKG. Risiko for metabolisk acidose (er en lille smule sur), kan kompensere respiratorisk (har mistanke om pneumoni, rtg. af thorax er rekv.), da der er risiko for lungeødem eller ARDS Korrektion af elektrolytter Biokemi, samt syre-base status er taget Instruks mailes, må ringe ved yderligere Observeres 24 timer efter normalisering af biokemi[[ENDTEXT]]803694[[STARTINFO]]mhen0054, 5-1-2022 09:55:38[[ENDINFO]][[STARTTEXT]]Ja, bør pausere propranolol. Måle s-lithium i hver vagt indtil denne under 1,0 ,mmol/l. Konf FSOE001.[[ENDTEXT]]804093",2022-01-03 16:28:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 3-1-2022 16:51:24[[ENDINFO]][[STARTTEXT]]Er i fast behandling med Litarex 2 tbl til aften. Hjemmespl har igennem de sidste 2 dage observeret at pt har været noget konfus, har tremor og hyperrefleksi. Har ikke haft GI symptomer! Er indlagt via egen læge. Der er ingen s-konc. endnu, men den er taget. Pt er noget dehydreret, og nedsat nyrefunktion, ikke kendt med dette fra tidligere, creatinin 190, Kalium 5,9, har forhøjede infektionstal. Har ikke mistanke om akut forgiftning. Pt er i behandling med ACE-hæmmer samt centyl. Behandling?[[ENDTEXT]]803694[[STARTINFO]]mhen0054, 5-1-2022 09:55:38[[ENDINFO]][[STARTTEXT]]2.opkald læge Moska Køge sgh. Klaret op, fortsat meget træt. S-lithium ved ankomst 2,1, falder samme dag til 1,9, igår 1,7. Afventer s-lithium idag. Haft SB ned til 37. Normale inf. tal. Bør hun også pausere propranolol ? Hvor ofte tage S-lihtium ? [[ENDTEXT]]804093 | [[STARTINFO]]mhen0054, 5-1-2022 09:57:38[[ENDINFO]][[STARTTEXT]]2.opkald i koblet sag. [[ENDTEXT]]804092",4600.0,Køge,79,LITHIUMCITRAT,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,True
7356,Risiko for manifest forgiftning,OLANZAPIN,10,14,2022-01-09 13:30:31 | 2022-01-09 14:25:34,140,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,"[[STARTINFO]]cdit0001, 9-1-2022 13:45:07[[ENDINFO]][[STARTTEXT]]Obs BT og hvis det er så højt skal pt på sygehus så hurtigt som muligt. Vanligvis ses hypotension, tackykardi og CNS depression. Indlægges mhp observation og symptomatisk behandling.[[ENDTEXT]]805045[[STARTINFO]]cdit0001, 9-1-2022 14:40:28[[ENDINFO]][[STARTTEXT]]Kul vha anæstesien evt. EKG hver anden time i 6 timer. Obs antikolinerge symptomer, Behandlingen er symptomatisk Er der kun lette eller ingen symptomer i 6 timer kan somatisk obs afsluttes.[[ENDTEXT]]805054",2022-01-09 13:30:14,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bornholms Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 9-1-2022 13:45:07[[ENDINFO]][[STARTTEXT]]Har hentet ovenstående. Indtaget egen medicin . Får 10 mg til natten og tidspunktet for indtag kendes ikke. Kan svare på tiltale men er meget sløv. Puls 113. Der måles et blodtryk på 211/160 men kunne være fejlmåling.[[ENDTEXT]]805045[[STARTINFO]]cdit0001, 9-1-2022 14:40:28[[ENDINFO]][[STARTTEXT]]2 opkald: Mark Jacobsen. Er kommet BT er nu 145/80, puls 106. QTc er 446 msek. Er lidt træt/sløv. Har ildelugtende urin og de anlægger KAD[[ENDTEXT]]805054 | [[STARTINFO]]mhen0054, 9-1-2022 14:26:11[[ENDINFO]][[STARTTEXT]]2.opkald i koblet sag. [[ENDTEXT]]805053",3700.0,Rønne,71,OLANZAPIN,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,3.0,True
7357,Risiko for manifest forgiftning,DONEPEZIL,10,7,2022-01-09 16:06:03 | 2022-01-09 17:22:11 | 2022-01-10 09:43:13,70,Indlæggelse,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]msoe0664, 9-1-2022 16:37:06[[ENDINFO]][[STARTTEXT]]Donepezil kan give kolignert syndrom, som hun også har en del symptomer på. evt også haft store vandladninger og deraf hyponatriæmi. Har fået over toksisk dosis og da donepezil har en t½ på 70 timer er påvirkningen på ingen måde overstået. stadig risiko for elektrolytforstyrrelse, hypotention mm. Anbefaler at ringe til lægevagten mhp at indlægge hende igen. [[ENDTEXT]]805060[[STARTINFO]]msoe0664, 9-1-2022 17:32:58[[ENDINFO]][[STARTTEXT]]Forklaret ovenstående omkring kolignergt syndrom. Diarre, opkast, sved, savlen, tåreflod, store diureser kan ses. desuden via parasympaticus bradykardi, AV blok. kontrol af ekg og hvis forandringer telemetri, atropin er antidot, men bruges kun ved svære symptomer. Ellers symptomatisk behandling med korrigering af elektrolyttter og væske til symptomer ophører. Kan også give muskelpåvirkning og man kontrollerer for rhabdomyolyse. Borger er også beskrevet ridig/stiv og har måske ikke fået sin levodopa så meget som hun skulle.[[ENDTEXT]]805088[[STARTINFO]]nhan0003, 10-1-2022 10:09:30[[ENDINFO]][[STARTTEXT]]3 opkald Konf jwan0009 Pause Donepezil i 14 dage, man kan evt opstarte med 5 mg Donepezil. Opfølgning hos praktiserende læge[[ENDTEXT]]805198",2022-01-09 15:30:10,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Esbjerg Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]msoe0664, 9-1-2022 16:37:06[[ENDINFO]][[STARTTEXT]]Søn som også er læge: Opdaget at han mor har fået for meget Donepezil. Får vanligt 10mg x 1, men hans far har fejdoseret i hendes dosetæsker så hun har fået 20 20 20 10 mg daglig. Han ved ikke hvor længe men sandsynligvis en uge. Hun har været dårlig den sidste uge med opkast, diarre, ikke kunnet komme ud af sengen, en enkelt dag hallucinationer og desuden mere regid/stiv - evt ikke fået sin vanlige levodopa og får også Eldepryl. Ved ikke hvordan det har været doseret. Været indlagt i nat hvor hun blev elektrolytkorrigeret og fik væke. Havde hyponatriæmi og har også haft hypokaliæmi. Han har lige nu efter hun er kommet hjem opdaget at der er fejl i doseringen af hendes medicin. Risiko? Hun vil helst ikke på sygehuset igen. [[ENDTEXT]]805060[[STARTINFO]]msoe0664, 9-1-2022 17:11:14[[ENDINFO]][[STARTTEXT]]Søn ringer igen, fået 70mg daglig minimum i 3 dage og måske længere. Vir kan ikke redegøre for det.[[ENDTEXT]]805083[[STARTINFO]]msoe0664, 9-1-2022 17:32:58[[ENDINFO]][[STARTTEXT]]læge Esbjerg med.afd: Talt med datter som har forklaret hisorie og vil bare lige høre nærmere angående Donepezil. [[ENDTEXT]]805088[[STARTINFO]]nhan0003, 10-1-2022 10:09:30[[ENDINFO]][[STARTTEXT]]3 opkald Læge Ann Tlf: 79185705 Pt frembyder ingen symptomer. Sovet godt i nat. BT: 122/75 P: 57 Na: 132 Tænker at pt skal udskr. Aftalt at hjemmeplejen overtager medicin håndtering[[ENDTEXT]]805198 | [[STARTINFO]]msoe0664, 9-1-2022 17:33:36[[ENDINFO]][[STARTTEXT]]koblet til 387256[[ENDTEXT]]805082 | [[STARTINFO]]nhan0003, 10-1-2022 10:09:15[[ENDINFO]][[STARTTEXT]]3 opkald se sag 387256[[ENDTEXT]]805189",6710.0,Esbjerg V,71,DONEPEZIL,NaN,NaN,NaN,NaN,NaN,NaN,Fejldosering,NaN,5.0,True
7358,Uafklaret risiko,OLANZAPIN,2.5,14,2022-01-10 11:45:02 | 2022-01-10 17:40:38,35,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,"[[STARTINFO]]nhan0003, 10-1-2022 12:28:52[[ENDINFO]][[STARTTEXT]]Da der ringes tilbage: CT-scan: ia der er givet Flumazenil med god effekt- vågnet lidt op, ligger og hvisker Ville umiddelbart forvente øvrige symptomer hvis der er taget Olanzapin ( forlænget QTc, anticholinerge sympt) Symptomatisk beh: Forhøre hvad hustru har af vanlig medicin Biokemi: pcm, salicylat, ethanol, rhabdomyolyse Ny henvendelse ved behov[[ENDTEXT]]805232[[STARTINFO]]tvan0009, 10-1-2022 18:02:02[[ENDINFO]][[STARTTEXT]]anbefaler kul stille og roligt over en times tid hvis luftvejene kan forsvares følge godt med med flumazenil derudover symptomatisk observation EKG/2 time (konf SBOE)[[ENDTEXT]]805300",2022-01-10 11:43:45,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hillerød Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 10-1-2022 12:28:52[[ENDINFO]][[STARTTEXT]]Pt fundet bevidstløs af hustru og datter til morgen og indlægges. Har d 09-01 fortalt datter at han ikke ønsker at leve mere. Pt sovende GCS: 8. Muskelstivhed, mistænker om han kan have taget Olanzapin, pga muskelstivhed ? Pt varetager selv sin medicin. Usikkerhed om der mangler tbl hjemme. Sidst indløst recept april 2021 EKG: QTc: 408 ms Frekvens: 50 CT- scan: bestilt Vandl x 2 i buksene. KAD anlagt 100 ml urin udtømt Vanlig medicin: Olanzapion 2.5 mg x 1, Alfuzosin 10 mg, Amlodipin 5 mg, Cloipidogrel 75 mg x 1, Simvastatin 10 mg Drug test: Pos benzodiazepin Der er givet Naloxon -> Ingen effekt[[ENDTEXT]]805232[[STARTINFO]]tvan0009, 10-1-2022 18:02:02[[ENDINFO]][[STARTTEXT]]2 opkald stabiliseret sig med P 45 BT165 der gives løbende flumazenil ca 0,2mg /time som han vågner op på har fortsat små pupiller der er ikke givet kul opstartet olanzapin kan have taget 35mg er der noget man skal være opmærksom på[[ENDTEXT]]805300 | [[STARTINFO]]tvan0009, 10-1-2022 18:01:34[[ENDINFO]][[STARTTEXT]]se koblede sag[[ENDTEXT]]805297",3200.0,Helsinge,81,OLANZAPIN,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,7.0,True
7359,Risiko for manifest forgiftning,VENLAFAXINHYDROCHLORID | TOPIRAMAT,75,8,2022-01-13 01:45:20 | 2022-01-13 06:06:30,600,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,MED,"[[STARTINFO]]nhan0003, 13-1-2022 03:50:57[[ENDINFO]][[STARTTEXT]]Indtaget tox dosis mhp Lamotrigin. Skal indlægges til behandling[[ENDTEXT]]805840[[STARTINFO]]nhan0003, 13-1-2022 06:15:26[[ENDINFO]][[STARTTEXT]]2 opkald Lamotrigin: Tox dosis > 1000 mg. CNS påvirkning, Kvalme, opkastning, tremor Venlafaxin: Atoxisk. Tox dosis > 900 mg. Evt svimmelhed, kvalme Topimax: Symptomer indenfor 4 timer. CNS påvirkning, kvalme, opkastning Aktivt kul Symptomatisk beh. Obs vitalparametre med fokus på CNS, BT, P, resp, SAT, tp. KOntrol EKG om 2 timer Ilt på næsekat Biokemi: elektrolytter, lever- nyretal, A.pkt, Pcm, salicylat Hvis fortsat ingen symptomer, kan observation afsluttes om 6 timer[[ENDTEXT]]805843",2022-01-13 01:45:54,Topimax | VENLAFAXINHYDROCHLORID,NaN,NaN,NaN,NaN,NaN,TOPIRAMAT | VENLAFAXINHYDROCHLORID,100,8,800,MED | ZZMED,Sygehus Viborg,LAMOTRIGIN,LAMOTRIGIN,200.0,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZZMED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 13-1-2022 03:50:57[[ENDINFO]][[STARTTEXT]]Skulle tage sin vanlige aftenmedicin. Taget døgndosis x 8, kan ikke helt forklare hvordan det skete. Er vågen, klar og relevant[[ENDTEXT]]805840[[STARTINFO]]nhan0003, 13-1-2022 06:15:26[[ENDINFO]][[STARTTEXT]]2 opkald Pt modtaget på Viborg sygehus. LÆge Ida Tlf: 78445053 Taget doseringsposer og åbnet dem. Fortæller tbl er indtaget i affekt. Har doseringsposerne med og taget 8 døgndosering samt åbnet 2 yderligere hvor Lamotrigin er taget. Nægter at have taget Paracetamol Drukket 2 Guldøl Fortsat ingen symptomer EKG: Sinusrytme / Smalle komplekser BT: 115/51 P: 88 Tp: 37 Resp: 16 SAT: 92 ( storryger)[[ENDTEXT]]805843 | [[STARTINFO]]nhan0003, 13-1-2022 06:06:56[[ENDINFO]][[STARTTEXT]]2 opkald se sag 387567[[ENDTEXT]]805842",8883.0,Gjern,70,"Venlafaxin \Hexal\"""" | Topimax",NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,10.0,True
7360,Risiko for manifest forgiftning,til høreapparat.,NaN,6,2022-01-13 12:30:26 | 2022-01-13 18:13:16,NaN,Skadestue,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]cdit0001, 13-1-2022 18:01:47[[ENDINFO]][[STARTTEXT]]RTG mhp lokalisering for at sikre at der ikke sidder et i oesofagus eller svælg. Hvis batteriet ligger i ventriklen, informeres pt. om at søge læge på ny, hvis der opstår GI-symptomer.[[ENDTEXT]]806006[[STARTINFO]]cdit0001, 13-1-2022 18:15:23[[ENDINFO]][[STARTTEXT]]Som ovenstående. De skal ikke forvente noget akut.[[ENDTEXT]]806011",2022-01-13 17:52:37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger | Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 13-1-2022 18:01:47[[ENDINFO]][[STARTTEXT]]Der stod et medicinbæger med 5-6 batterier til høreapparatet. Dem slugte ovenstående ved middagstid.[[ENDTEXT]]806006[[STARTINFO]]cdit0001, 13-1-2022 18:15:23[[ENDINFO]][[STARTTEXT]]Er på vej ud og hente ovenstående.[[ENDTEXT]]806011 | [[STARTINFO]]cdit0001, 13-1-2022 18:15:32[[ENDINFO]][[STARTTEXT]]Koblet 387630[[ENDTEXT]]806010",8210.0,Aarhus V,78,Knapcelle,NaN,NaN,NaN,NaN,Forveksling,NaN,NaN,NaN,11.0,True
7361,Risiko for livstruende forgiftning,OXYCODONHYDROCHLORID,5,7,2022-01-14 14:40:57 | 2022-01-15 05:12:55,35,Indlæggelse,NaN,Akut forgiftning,ZZMED,"[[STARTINFO]]KERI0026, 15-1-2022 04:31:40[[ENDINFO]][[STARTTEXT]]Stor dosis, er klinisk påvirket, virkning mindst 24 timer skal indl. med det samme. fokus Bevidsthed og resp, kald AMK læge ved tvivl.[[ENDTEXT]]806267[[STARTINFO]]KERI0026, 15-1-2022 05:33:44[[ENDINFO]][[STARTTEXT]]2 opkald: Kramper ses efter Dolol indtag, beh med BZD Kald anæstesi for vurdering af pt/ understøttende behandling, justering af pH Naloxon kan gives som infusion, ex 2mg Naloxon i 500ml isoton Nacl/Glucose, svarende til 4microg/ml. infusions hastighed efter klinik, start f.ex med 10 microg/kg /t . (der er max givet 75 mg /døgn til voksen uden bivirkninger). OBS serotonergt syndrom.tp.måling. OBS Rhabdomyolyse, s-PCM, s-salicylat ring igen ved tvivl Opioid instruks tilbudt. Konf: Krampe profylakse? afvente om kramper forsætter. aktiv kul nu? nej lægges i kaffe kop for opfølgning., [[ENDTEXT]]806268",2022-01-15 04:25:03,Dolol,mg,mg,NaN,NaN,NaN,TRAMADOLHYDROCHLORID,50,130,6500,MED,Kbh. Amts Sygehus i Glostrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen | Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 15-1-2022 04:31:40[[ENDINFO]][[STARTTEXT]]OD kl 15, fundet bevidstheds påvirket og overfladisk resp. de har givet naloxon. Behandling? nu det er mere end 15 timer hun har taget det?[[ENDTEXT]]806267[[STARTINFO]]KERI0026, 15-1-2022 05:33:44[[ENDINFO]][[STARTTEXT]]2 opkald Glostrup sygehus, AM,læge Niklas, tlf 38630470. Pt ankommet der er givet Naloxon x 5, med kort effekt, har lige krampet. Har foruden Dolol også taget 35mg Oxycodon. A.pkt efter kramper: pH 7,17, CO2 7,28, Po2 32 Bicarbonat 16,7, Laktat 11. Puls 90, BT ia. Naloxon som infusion?[[ENDTEXT]]806268 | [[STARTINFO]]KERI0026, 15-1-2022 05:14:01[[ENDINFO]][[STARTTEXT]]2 opkald kobles 387741[[ENDTEXT]]806270",2635.0,Ishøj,86,OXYCODONHYDROCHLORID,NaN,NaN,Suicidal/Affekt,NaN,NaN,NaN,NaN,NaN,13.0,True

Two auxiliary columns are now present in young_filtered and old_filtered:

- is_duplicate – Boolean flag  
  ‑ TRUE for every row that originates from a duplicate cluster (the single merged row that now represents the cluster).  
  ‑ FALSE / NaN for rows that never belonged to a duplicate cluster.

- dup_case_id – Integer identifier  
  ‑ Each duplicate cluster receives a consecutive number (0, 1, 2, …).  
  ‑ Rows that are not part of any duplicate cluster hold NaN in this column.

Together these fields let you
  – recognise which rows were produced by the merging routine, and  
  – see which merged rows belong to the same original case (because they share the same dup_case_id).

After the merge step every former cluster has been collapsed into exactly one row, and that row retains the cluster’s identifier.  
Therefore:

- For each non-null value in dup_case_id there is exactly one row in the dataframe.  
- All other rows (those that never belonged to a duplicate cluster) have dup_case_id = NaN.

So within each sheet the non-null dup_case_id values are unique.

Now we want to count the no. of cases, which have "false" in the duplicated fields, but have "koblet, kobles, opkald, koblede" in "[anamnese(tekst)]" or "[råd(tekst)]".
We do this to get an idea if we have more duplicate cases to find. 

Before updating our code with all poison columns, the duplicate cases were:

```text
Duplicate case size distribution:
  2 rows : 321 case(s)
  3 rows : 32 case(s)
  4 rows : 3 case(s)
  5 rows : 1 case(s)
  total     : 357 cases


Duplicate case size distribution:
  2 rows : 4504 case(s)
  3 rows : 579 case(s)
  4 rows : 87 case(s)
  5 rows : 16 case(s)
  6 rows : 4 case(s)
  7 rows : 2 case(s)
  8 rows : 1 case(s)
  total     : 5193 cases
```

After updating our code:
```text
Duplicate case size distribution:
  2 rows : 511 case(s)
  3 rows : 71 case(s)
  4 rows : 6 case(s)
  6 rows : 1 case(s)
  total     : 589 cases


Duplicate case size distribution:
  2 rows : 8369 case(s)
  3 rows : 1186 case(s)
  4 rows : 191 case(s)
  5 rows : 50 case(s)
  6 rows : 10 case(s)
  7 rows : 2 case(s)
  8 rows : 1 case(s)
  total     : 9809 cases
```