In [1]:
from getpass import getpass
import io
import pandas as pd
import msoffcrypto

file_path =r"C:\Users\danam\OneDrive\Desktop\Bachelorprojekt\Tidligere excel bearbejdninger\Alle Giftlinjen 2018-2022 (anonym) Aldersfordelt - Kopi.xlsx"
password = getpass("Enter Excel password: ")

decrypted = io.BytesIO()
with open(file_path, "rb") as f:
    office = msoffcrypto.OfficeFile(f)
    office.load_key(password=password)
    office.decrypt(decrypted)

# Move back to the start of the stream before reading
decrypted.seek(0)

# Specify the two sheets you want to load
sheet_names = ["Alder<70", "Alder>70"] 
# List the columns you want
keep = [
    '[Indtag tid(gift1)]',
    '[Mand(Patient data)]',
    '[Alder (år)(Patient data)]',
    '[Ingen risiko(Risiko)]',
    '[generisk navn(gift1)]',
    '[navn(gift1)]',
    '[substans type(gift1)]',
    '[Enhed(gift1)]',
    '[Styrke(gift1)]',
    '[antal(gift1)]',
    '[dosis(gift1)]',
    '[generisk navn(gift2)]',
    '[navn(gift2)]',
    '[substans type(gift2)]',
    '[Enhed(gift2)]',
    '[Styrke(gift2)]',
    '[antal(gift2)]',
    '[dosis(gift2)]',
    '[generisk navn(gift3)]',
    '[navn(gift3)]',
    '[substans type(gift3)]',
    '[Enhed(gift3)]',
    '[Styrke(gift3)]',
    '[antal(gift3)]',
    '[dosis(gift3)]',
    '[generisk navn(gift4)]',
    '[navn(gift4)]',
    '[substans type(gift4)]',
    '[Enhed(gift4)]',
    '[Styrke(gift4)]',
    '[antal(gift4)]',
    '[dosis(gift4)]',  
    '[generisk navn(gift5)]',
    '[navn(gift5)]',
    '[substans type(gift5)]',
    '[Enhed(gift5)]',
    '[Styrke(gift5)]',
    '[antal(gift5)]',
    '[dosis(gift5)]',
    '[generisk navn(gift6)]',
    '[navn(gift6)]',
    '[substans type(gift6)]',
    '[Enhed(gift6)]',
    '[Styrke(gift6)]',
    '[antal(gift6)]',
    '[Dosis(gift6)]',
    '[generisk navn(gift7)]',
    '[navn(gift7)]',
    '[substans type(gift7)]',
    '[Enhed(gift7)]',
    '[Styrke(gift7)]',
    '[antal(gift7)]',
    '[Dosis(gift7)]',
    '[generisk navn(gift8)]',
    '[navn(gift8)]',
    '[substans type(gift8)]',
    '[Enhed(gift8)]',
    '[Styrke(gift8)]',
    '[antal(gift8)]',
    '[Dosis(gift8)]',
    '[generisk navn(gift9)]',
    '[navn(gift9)]',
    '[substans type(gift9)]',
    '[Enhed(gift9)]',
    '[Styrke(gift9)]',
    '[antal(gift9)]',
    '[Dosis(gift9)]',
    '[generisk navn(gift10)]',
    '[navn(gift10)]',
    '[substans type(gift10)]',
    '[Enhed(gift10)]',
    '[Styrke(gift10)]',
    '[antal(gift10)]',
    '[Dosis(gift10)]',
    '[generisk navn(gift11)]',
    '[navn(gift11)]',
    '[substans type(gift11)]',
    '[Enhed(gift11)]',
    '[Styrke(gift11)]',
    '[antal(gift11)]',
    '[Dosis(gift11)]',
    '[generisk navn(gift12)]',
    '[navn(gift12)]',
    '[substans type(gift12)]',
    '[Enhed(gift12)]',
    '[Styrke(gift12)]',
    '[antal(gift12)]',
    '[Dosis(gift12)]',
    '[generisk navn(gift13)]',
    '[navn(gift13)]',
    '[substans type(gift13)]',
    '[Enhed(gift13)]',
    '[Styrke(gift13)]',
    '[antal(gift13)]',
    '[Dosis(gift13)]',
    '[generisk navn(gift14)]',
    '[navn(gift14)]',
    '[substans type(gift14)]',
    '[Enhed(gift14)]',
    '[Styrke(gift14)]',
    '[antal(gift14)]',
    '[Dosis(gift14)]',
    '[generisk navn(gift15)]',
    '[navn(gift15)]',
    '[substans type(gift15)]',
    '[Enhed(gift15)]',
    '[Styrke(gift15)]',
    '[antal(gift15)]',
    '[Dosis(gift15)]',
    '[Ingen(Anbefalet obs)]',
    '[Akut forgiftning(Forespørgselsart)]',
    '[Søg Hospital(hospital)]',
    '[Borger(Spørger1)]',
    '[Søg postnummer(postalcode)]',
    '[Søg By(postalcode)]',
    '[Råd(Tekst)]',
    '[Today(Oprettelse)]',
    '[Anamnese(Tekst)]',
    '[Psykiatriske sygdomme(Komorbiditet)]',
    '[Ulykke/uheld(Årsag)]',
    '[Leg(Årsag)]',
    '[Suicidal/Affekt(Årsag)]',
    '[Misbrug(Årsag)]',
    '[Forveksling(Årsag)]',
    '[Omhældning(Årsag)]',
    '[Fejldosering(Årsag)]',
    '[Levnedsmiddel(Årsag)]',
]

dfs = pd.read_excel(
    decrypted,
    sheet_name=sheet_names,
    usecols=keep
)

# All column names are now lowercase:
for sheet in sheet_names:
    dfs[sheet].columns = [c.lower() for c in dfs[sheet].columns]


young = dfs[sheet_names[0]]
old = dfs[sheet_names[1]]

In [2]:
display(young.head())
display(old.head())

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],...,[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)]
0,Risiko for manifest forgiftning,Cannabis,NaN,NaN,2021-12-31 05:00:36,NaN,Indlæggelse,NaN,Akut forgiftning,RUS,...,26.0,Hash,NaN,NaN,NaN,Misbrug,NaN,NaN,NaN,NaN
1,Ingen risiko,NaN,NaN,NaN,2022-01-01 14:03:44,NaN,Ingen,NaN,Akut forgiftning,DIVERSE,...,68.0,Batteri til radio og andet,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Uafklaret risiko,Ukendt,NaN,1,2022-01-01 15:24:37,NaN,Ingen,NaN,Akut forgiftning,RUS,...,1.0,Ukendt bær,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
3,Risiko for begrænset forgiftning,Ukendt rusmiddel,NaN,NaN,2022-01-01 02:00:14,NaN,Observeres hjemme,NaN,Akut forgiftning,RUS,...,16.0,"Noget i drink, Deprimerende",Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ingen risiko,PARACETAMOL,500,1,2022-01-01 15:32:13,500,Ingen,NaN,Akut forgiftning,MED,...,7.0,"Paracetamol \Sandoz\""""",NaN,NaN,NaN,NaN,NaN,NaN,Fejldosering,NaN

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],...,[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)]
0,Risiko for livstruende forgiftning,ZOLPIDEM TARTRAT,10,1,2022-01-02 09:30:34,10,Indlæggelse,Psykiatriske sygdomme,Akut forgiftning,ZZMED,...,79,ZOLPIDEM TARTRAT,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Risiko for begrænset forgiftning,NaN,NaN,NaN,2022-01-02 12:46:42,NaN,Skadestue,NaN,Akut forgiftning,KEMI,...,75,Det standser blodet,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,test fra telefoni,NaN,NaN,2022-01-03 09:55:19,NaN,NaN,NaN,NaN,SPECIALDONOTDELETE,...,85,test fra telefoni,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,0000-00-00 00:00:00,NaN,NaN,NaN,Forkert nummer - sagen afsluttes,NaN,...,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Risiko for manifest forgiftning,"Benserazidhydrochlorid, LEVODOPA",100,12,2022-01-03 16:21:19,1200,Indlæggelse,NaN,Kronisk forgiftning,MED,...,79,Madopar Quick 125,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We are building a list of equvialents for the medicine, so that eg. panodil and paracetamol are not counted twice as two seperate medicines in one row.
See the work in new ipynb notebook "list of equivalent names for medicines.ipynb.ipynb"

In [3]:
# Loading list of equivalent medicine names from generated json file
import json
with open('equivalent_names.json', encoding='utf-8') as f:
    groups = json.load(f)

Checking the dataframe using both lægemiddelstyrelsens list of known and discontinued medicines and our list of equivalent medicine names. 

1. Build a global synonym-to-canonical map once, by scanning all relevant columns of both dataframes and applying the “highest frequency, longest if tie” rule to each synonym group from equivalent_names.json.

2. Keep row_has_medicine exactly as it is (it already finds every synonym, because each one is in medicines).

3. Rewrite medicine_counter so that  
    • for every row we collect all words across the relevant columns,  
    • translate each word through the synonym_to_canonical map (if present),  
    • de-duplicate per canonical name inside that row,  
    • then add 1 count for each distinct canonical name that appears in that row.  
   ⇒ A row that contains both “panodil” and “paracetamol” will contribute exactly one count to “paracetamol”.

 4. filter_and_report stays the same except that it now calls the new medicine_counter, so any Top-50 tables etc. will list only canonical names.

In [4]:
# ---------------------------------------------------------------------------
# 0.  Imports / general setup
# ---------------------------------------------------------------------------
import json
import pandas as pd
from collections import Counter
from IPython.display import display

# unlimited display (unchanged from your original snippet)
pd.set_option('display.max_rows',    None)
pd.set_option('display.max_columns', None)


# ---------------------------------------------------------------------------
# 1.  Load input data that you already have
# ---------------------------------------------------------------------------
with open('unique_medicine_names.txt', encoding='utf-8') as f:
    medicines = set(line.strip().lower() for line in f if line.strip())

with open('equivalent_names.json', encoding='utf-8') as f:
    groups = json.load(f)                 # list[list[str]]

# young  and old dataframes are assumed to be in memory already
# ---------------------------------------------------------------------------
# 2.  Column lists (same as before, but lower-cased once here)
# ---------------------------------------------------------------------------
generisk_cols = [f'[generisk navn(gift{i})]' for i in range(1, 16)]
navn_cols     = [f'[navn(gift{i})]'           for i in range(1, 16)]
extra_cols    = ['[råd(tekst)]', '[anamnese(tekst)]']

all_cols = [*generisk_cols, *navn_cols, *extra_cols]
all_cols = [c.lower() for c in all_cols]


# ---------------------------------------------------------------------------
# 3.  Helper – tokeniser (comma / semicolon / slash are treated as spaces)
# ---------------------------------------------------------------------------
def split_words(text: str):
    """Return a list of lowercase 'words' cut on space, ',', ';', '/'."""
    return (
        text.replace(',', ' ')
            .replace(';', ' ')
            .replace('/', ' ')
            .lower()
            .split()
    )


# ---------------------------------------------------------------------------
# 4.  PRE-SCAN  – build raw frequencies for every word in every sheet
# ---------------------------------------------------------------------------
def build_word_frequencies(dfs, columns) -> Counter:
    """Count every token that occurs (case-folded)."""
    freq = Counter()
    for df in dfs:
        for col in columns:
            if col not in df.columns:
                continue
            for entry in df[col].dropna().astype(str).values:
                for word in split_words(entry):
                    freq[word] += 1
    return freq


raw_freq = build_word_frequencies([young, old], all_cols)


# ---------------------------------------------------------------------------
# 5.  Decide canonical synonym per group
# ---------------------------------------------------------------------------
synonym_to_canonical = {}

for group in groups:
    group = [g.lower() for g in group]          # safety: lower-case once
    
    # 1) highest raw frequency
    best_freq = max(raw_freq.get(g, 0) for g in group)
    candidates = [g for g in group if raw_freq.get(g, 0) == best_freq]
    
    # 2) tie-break with longest string
    canonical = max(candidates, key=len)
    
    # map every member to that canonical spelling
    for g in group:
        synonym_to_canonical[g] = canonical

# Optionally inspect
#print(json.dumps(synonym_to_canonical, indent=2, ensure_ascii=False))

# check exactly what key the code stored for venlafaxin*
for k, v in synonym_to_canonical.items():
    if 'venlafaxin' in k:
        print(repr(k), '→', repr(v))

# ---------------------------------------------------------------------------
# 6.  Revised medicine-counter (row-deduplicated, canonicalised)
# ---------------------------------------------------------------------------
def medicine_counter(df: pd.DataFrame) -> Counter:
    """
    Per row we collect all (canonical) medicine names that appear in any
    relevant column.  Each canonical name is counted *once per row*.
    """
    counter = Counter()
    for _, row in df[all_cols].iterrows():
        seen_this_row = set()
        for col in all_cols:
            if pd.isnull(row[col]):
                continue
            for word in split_words(str(row[col])):
                if word in medicines:                 # only consider medicines
                    word = synonym_to_canonical.get(word, word)  # canonicalise
                    seen_this_row.add(word)
        counter.update(seen_this_row)                 # add each only once/row
    return counter


# ---------------------------------------------------------------------------
# 7.  row_has_medicine is unchanged – still fine because every synonym is in
#     the original 'medicines' list
# ---------------------------------------------------------------------------
def row_has_medicine(row):
    for col in all_cols:
        value = row.get(col)
        if pd.isnull(value):
            continue
        entry = str(value).strip().lower()
        words = split_words(entry)
        if entry in medicines or any(word in medicines for word in words):
            return True
    return False


# ---------------------------------------------------------------------------
# 8.  filter_and_report – uses the new medicine_counter
# ---------------------------------------------------------------------------
def filter_and_report(df, label):
    total_start = len(df)
    mask = df.apply(row_has_medicine, axis=1)

    deleted = df[~mask].copy()
    kept    = df[mask].copy()

    print(f"\nSheet: {label}")
    print(f"  Rows at start:  {total_start}")
    print(f"  Rows deleted:   {len(deleted)}")
    print(f"  Rows remaining: {len(kept)}")

    # --- show up to 100 suspect deleted rows (unchanged logic) --------------
    cols_of_interest = [*generisk_cols, *navn_cols]
    cols_of_interest = [c.lower() for c in cols_of_interest]

    def has_long_entry(r):
        return any(
            pd.notnull(r[col]) and len(str(r[col])) > 20
            for col in cols_of_interest
        )

    candidates = deleted[deleted.apply(has_long_entry, axis=1)]
    sample = (
        candidates.sample(n=min(100, len(candidates)), random_state=42)
        if not candidates.empty else candidates
    )

    print("  Up to 100 random deleted rows with >20 chars in any name/generic column:")
    display(sample)

    # --- Top-50 canonical medicine list -------------------------------------
    print(f"\nTop 50 medicine matches in '{label}' (canonical names):")
    top_50 = medicine_counter(kept).most_common(50)
    top_50_df = pd.DataFrame(top_50, columns=['medicine', 'count'])
    display(top_50_df)

    return kept, deleted


# ---------------------------------------------------------------------------
# 9.  Run on both sheets
# ---------------------------------------------------------------------------
young_filtered, young_deleted = filter_and_report(young, "young")
old_filtered,   old_deleted   = filter_and_report(old,   "old")

'venlafaxin' → 'venlafaxinhydrochlorid'
'venlafaxin sandoz' → 'venlafaxinhydrochlorid'
'venlafaxinhydrochlorid' → 'venlafaxinhydrochlorid'

Sheet: young
  Rows at start:  154529
  Rows deleted:   96799
  Rows remaining: 57730
  Up to 100 random deleted rows with >20 chars in any name/generic column:

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)]
22465,Ingen risiko,Symphoricarpos albus,NaN,1,2022-09-02 08:45:37,NaN,Observeres hjemme,NaN,Akut forgiftning,BIO,"[[STARTINFO]]mhen0054, 2-9-2022 08:57:17[[ENDI...",2022-09-02 08:47:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mhen0054, 2-9-2022 08:57:17[[ENDI...",3550,Slangerup,1.0,Snebær,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
115296,Ingen risiko,NaN,NaN,NaN,2019-07-23 18:00:00,NaN,Ingen,NaN,Akut forgiftning,KEMI,NaN,2019-07-23 18:10:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2650,Hvidovre,4.0,Genanvendelig isterning,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
95502,Risiko for begrænset forgiftning,Ukendt,NaN,NaN,2020-11-09 13:35:33,NaN,Egen læge,NaN,Akut forgiftning,RUS,"[[STARTINFO]]rlar0142, 10-11-2020 10:43:30[[EN...",2020-11-10 10:30:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 10-11-2020 10:43:30[[EN...",6990,Ulfborg,44.0,Aflivningsmedicin til hund,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88198,Ingen risiko,metasilikat,NaN,NaN,2020-08-25 18:35:20,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]sgre0034, 25-8-2020 18:36:41[[END...",2020-08-25 18:35:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 25-8-2020 18:36:41[[END...",7752,Snedsted,1.0,Maskinopvaskemiddel ikke industrielt,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
39394,Risiko for begrænset forgiftning,NaN,NaN,NaN,2021-03-11 20:33:42,NaN,Vagtlæge,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]RLAR0142, 11-3-2021 23:39:03[[END...",2021-03-11 23:31:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]RLAR0142, 11-3-2021 23:39:03[[END...",1361,København K,26.0,Forårsruller og agurker,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24862,Ingen risiko,"Svovl, kaliumchlorat, Manganoxid",NaN,NaN,2022-09-25 11:35:45,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]nhan0003, 25-9-2022 11:53:27[[END...",2022-09-25 11:50:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 25-9-2022 11:53:27[[END...",7700,Thisted,1.0,Tændstikker,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
6564,Risiko for begrænset forgiftning,NaN,NaN,NaN,2022-03-23 07:15:45,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]rlar0142, 23-3-2022 07:26:39[[END...",2022-03-23 07:19:56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 23-3-2022 07:26:39[[END...",6400,Sønderborg,1.0,Skurepulver cif cream,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
110353,Ingen risiko,NaN,NaN,NaN,2019-05-29 06:52:12,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]tvan0009, 29-5-2019 06:53:52[[END...",2019-05-29 06:51:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 29-5-2019 06:53:52[[END...",4000,Roskilde,1.0,Maskinopvaskemiddel ikke industrielt,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
19383,Risiko for begrænset forgiftning,NaN,NaN,NaN,2022-08-04 11:51:58,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]sgre0034, 4-8-2022 11:54:25[[ENDI...",2022-08-04 11:49:55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 4-8-2022 11:54:25[[ENDI...",4660,Store Heddinge,4.0,"Kulbrinter, simple alifatiske",NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
77761,Risiko for begrænset forgiftning,NaN,NaN,NaN,2020-05-11 12:00:38,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]TLAN0003, 11-5-2020 19:00:33[[END...",2020-05-11 18:50:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]TLAN0003, 11-5-2020 19:00:33[[END...",7500,Holstebro,33.0,ECOstyle Insektfri Spruzit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47148,Risiko for begrænset forgiftning,Isopropylalkohol 75 %,NaN,NaN,2021-06-05 19:52:13,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]mhen0054, 5-6-2021 20:17:27[[ENDI...",2021-06-05 19:47:15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mhen0054, 5-6-2021 20:17:27[[ENDI...",2765,Smørum,10.0,Håndsprit,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
128305,Ingen risiko,"Svovl, kaliumchlorat, Manganoxid",NaN,1,2019-12-23 11:06:55,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]tvan0009, 23-12-2019 11:07:37[[EN...",2019-12-23 11:05:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 23-12-2019 11:07:37[[EN...",7500,Holstebro,3.0,Tændstikker,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
81056,Risiko for begrænset forgiftning,NaN,NaN,NaN,2020-06-16 13:09:36,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]rlar0142, 16-6-2020 13:28:10[[END...",2020-06-16 13:18:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 16-6-2020 13:28:10[[END...",2200,København N,9.0,"Desinfektionsmiddel, Divodes FG VT29",NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
82291,Risiko for begrænset forgiftning,NaN,NaN,NaN,2020-06-28 14:51:40,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]mhen0054, 28-6-2020 14:55:54[[END...",2020-06-28 14:47:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mhen0054, 28-6-2020 14:55:54[[END...",8380,Trige,0.0,Domestos Total Blast Gel,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
30343,NaN,NaN,NaN,NaN,2022-11-20 15:37:35,NaN,NaN,NaN,NaN,KEMI,NaN,2022-11-20 15:35:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhen0047, 20-11-2022 15:41:34[[EN...",9330,Dronninglund,3.0,Kvarternære ammoniumforbindelser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42292,Risiko for begrænset forgiftning,"Calciumcarbonat, NATRIUMALGINAT, NATRIUMHYDROG...",250,2,2021-04-14 19:06:19,500,Ingen,NaN,Akut forgiftning,MED,"[[STARTINFO]]cdit0001, 14-4-2021 19:20:32[[END...",2021-04-14 19:15:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 14-4-2021 19:20:32[[END...",2791,Dragør,2.0,Galieve tyggetbl,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
92733,Ingen risiko,NaN,NaN,NaN,2020-10-08 20:15:26,NaN,Ingen,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]nhan0003, 8-10-2020 20:27:28[[END...",2020-10-08 20:24:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 8-10-2020 20:27:28[[END...",7100,Vejle,4.0,Batteri til radio og andet,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
100302,Ingen risiko,NaN,NaN,NaN,2019-01-10 15:30:16,NaN,Ingen,NaN,Akut forgiftning,BIO,"[[STARTINFO]]KERI0026, 10-1-2019 15:50:45[[END...",2019-01-10 15:47:55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 10-1-2019 15:50:45[[END...",2970,Hørsholm,1.0,Svigermors Skarpe Tunge,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
76279,Risiko for manifest forgiftning,NaN,NaN,NaN,2020-04-11 10:00:22,NaN,Skadestue,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]tvan0009, 25-4-2020 10:03:47[[END...",2020-04-25 09:50:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 25-4-2020 10:03:47[[END...",4000,Roskilde,1.0,Batteri til radio og andet,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
71292,Ingen risiko,Multivitamin med Jern,8,15,2020-02-26 17:36:22,120,Ingen,NaN,Akut forgiftning,MED,"[[STARTINFO]]tvan0009, 26-2-2020 17:38:38[[END...",2020-02-26 17:35:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 26-2-2020 17:38:38[[END...",NaN,NaN,5.0,Multivitamin med Jern,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8807,Risiko for manifest forgiftning,NaN,NaN,NaN,2022-04-17 17:45:08,NaN,Skadestue,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]KERI0026, 17-4-2022 18:01:48[[END...",2022-04-17 17:54:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 17-4-2022 18:01:48[[END...",8700,Horsens,49.0,Skibsmaling Kobber VC17,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13490,Ingen risiko,Multivitamin uden Jern,NaN,50 stk,2022-06-06 08:00:09,NaN,Ingen,NaN,Akut forgiftning,MED,"[[STARTINFO]]mann0002, 6-6-2022 13:53:54[[ENDI...",2022-06-06 13:36:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 6-6-2022 13:53:54[[ENDI...",2900,Hellerup,5.0,Multivitamin uden Jern,NaN,Leg,NaN,NaN,NaN,NaN,NaN,NaN
117297,Risiko for begrænset forgiftning,NaN,NaN,NaN,2019-08-14 13:36:41,NaN,Observeres hjemme,NaN,Akut forgiftning,DIVERSE,"[[STARTINFO]]tvan0009, 14-8-2019 13:39:40[[END...",2019-08-14 13:36:21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 14-8-2019 13:39:40[[END...",2650,Hvidovre,24.0,Batteri til radio og andet,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38246,Risiko for begrænset forgiftning,NaN,NaN,1,2021-02-26 07:15:35,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]hjen0284, 26-2-2021 08:05:37[[END...",2021-02-26 07:47:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]hjen0284, 26-2-2021 08:05:37[[END...",4200,Slagelse,64.0,Afkalkningsmiddel minus kalk,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Top 50 medicine matches in 'young' (canonical names):

                      medicine  count
0                  paracetamol  11137
1                    quetiapin   6667
2                    ibuprofen   5199
3                     diazepam   3047
4                    sertralin   2790
5                elektrolytter   2756
6              cholecalciferol   2374
7                     oxazepam   1956
8   methylphenidathydrochlorid   1803
9         tramadolhydrochlorid   1749
10                   olanzapin   1540
11                  lamotrigin   1519
12           acetylsalicylsyre   1502
13                  pregabalin   1477
14                  flumazenil   1436
15                   melatonin   1408
16                    zopiclon   1400
17                      truxal   1268
18                    rivotril   1223
19                  alprazolam   1199
20    codeinphosphathemihydrat   1198
21                     naloxon   1102
22                  mirtazapin   1048
23                     metadon    966
24                   phenergan    965
25      venlafaxinhydrochlorid    921
26                 aripiprazol    912
27                      morfin    892
28                 pantoprazol    836
29        oxycodonhydrochlorid    758
30        cyclizinhydrochlorid    724
31                    akineton    713
32                    zolpidem    711
33                  gabapentin    702
34                    klopoxid    695
35                  citalopram    680
36     cetirizindihydrochlorid    660
37             natriumvalproat    629
38       duloxetinhydrochlorid    584
39                  risperidon    568
40           magnesiumhydroxid    536
41                     elvanse    532
42          metoprololsuccinat    492
43                   contalgin    483
44                ascorbinsyre    483
45                   amlodipin    458
46                   metformin    453
47                    eltroxin    448
48                     ketamin    439
49                     antabus    433

Sheet: old
  Rows at start:  8620
  Rows deleted:   2812
  Rows remaining: 5808
  Up to 100 random deleted rows with >20 chars in any name/generic column:

,[ingen risiko(risiko)],[generisk navn(gift1)],[styrke(gift1)],[antal(gift1)],[indtag tid(gift1)],[dosis(gift1)],[ingen(anbefalet obs)],[psykiatriske sygdomme(komorbiditet)],[akut forgiftning(forespørgselsart)],[substans type(gift1)],[råd(tekst)],[today(oprettelse)],[navn(gift2)],[enhed(gift1)],[enhed(gift2)],[enhed(gift3)],[enhed(gift4)],[enhed(gift5)],[generisk navn(gift2)],[styrke(gift2)],[antal(gift2)],[dosis(gift2)],[substans type(gift2)],[søg hospital(hospital)],[navn(gift3)],[generisk navn(gift3)],[styrke(gift3)],[navn(gift6)],[generisk navn(gift6)],[styrke(gift6)],[antal(gift6)],[enhed(gift6)],[dosis(gift6)],[antal(gift3)],[substans type(gift6)],[navn(gift7)],[generisk navn(gift7)],[styrke(gift7)],[antal(gift7)],[enhed(gift7)],[dosis(gift7)],[substans type(gift7)],[navn(gift8)],[generisk navn(gift8)],[dosis(gift3)],[styrke(gift8)],[antal(gift8)],[enhed(gift8)],[dosis(gift8)],[substans type(gift8)],[navn(gift9)],[generisk navn(gift9)],[styrke(gift9)],[antal(gift9)],[enhed(gift9)],[dosis(gift9)],[substans type(gift9)],[substans type(gift3)],[navn(gift4)],[generisk navn(gift4)],[styrke(gift4)],[antal(gift4)],[dosis(gift4)],[substans type(gift4)],[navn(gift5)],[navn(gift10)],[generisk navn(gift10)],[styrke(gift10)],[antal(gift10)],[enhed(gift10)],[generisk navn(gift5)],[dosis(gift10)],[substans type(gift10)],[navn(gift11)],[generisk navn(gift11)],[styrke(gift11)],[antal(gift11)],[enhed(gift11)],[styrke(gift5)],[dosis(gift11)],[substans type(gift11)],[antal(gift5)],[navn(gift12)],[generisk navn(gift12)],[styrke(gift12)],[antal(gift12)],[enhed(gift12)],[dosis(gift12)],[substans type(gift12)],[dosis(gift5)],[navn(gift13)],[generisk navn(gift13)],[mand(patient data)],[styrke(gift13)],[antal(gift13)],[enhed(gift13)],[dosis(gift13)],[substans type(gift13)],[substans type(gift5)],[navn(gift14)],[generisk navn(gift14)],[styrke(gift14)],[antal(gift14)],[enhed(gift14)],[dosis(gift14)],[substans type(gift14)],[borger(spørger1)],[navn(gift15)],[generisk navn(gift15)],[styrke(gift15)],[antal(gift15)],[enhed(gift15)],[dosis(gift15)],[substans type(gift15)],[anamnese(tekst)],[søg postnummer(postalcode)],[søg by(postalcode)],[alder (år)(patient data)],[navn(gift1)],[ulykke/uheld(årsag)],[leg(årsag)],[suicidal/affekt(årsag)],[misbrug(årsag)],[forveksling(årsag)],[omhældning(årsag)],[fejldosering(årsag)],[levnedsmiddel(årsag)]
1362,Risiko for begrænset forgiftning,NaN,NaN,NaN,2022-08-31 07:39:48,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]rlar0142, 31-8-2022 08:16:12[[END...",2022-08-31 07:55:21,Klorin 5%,NaN,NaN,NaN,NaN,NaN,Hypoklorit,NaN,NaN,NaN,KEMI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 31-8-2022 08:16:12[[END...",5320.0,Agedrup,71,"Klor, Clean tabs Swim and fun",Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1353,NaN,NaN,NaN,NaN,2022-08-30 10:09:33,NaN,NaN,NaN,Forkert nummer - sagen afsluttes,DIVERSE,NaN,2022-08-30 10:08:41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 30-8-2022 10:09:58[[END...",6900.0,Skjern,75,"Batteri, mini, høreapp. Oticon",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4206,Risiko for begrænset forgiftning,NaN,NaN,NaN,2020-02-25 20:45:47,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]TLAN0003, 25-2-2020 21:04:47[[END...",2020-02-25 21:01:12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,plejehjem,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]TLAN0003, 25-2-2020 21:04:47[[END...",4600.0,Køge,91,Opvaskemidler (til håndopvask),NaN,NaN,NaN,NaN,Forveksling,NaN,NaN,NaN
7115,Risiko for begrænset forgiftning,methylrosa niliniumchlorid,NaN,10,2019-12-20 22:05:49,NaN,Ingen,NaN,Akut forgiftning,SPECIALDONOTDELETE,"[[STARTINFO]]cdit0001, 20-12-2019 22:41:54[[EN...",2019-12-20 22:16:14,NaN,ml,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 20-12-2019 22:41:54[[EN...",5700.0,Svendborg,72,methylrosa niliniumchlorid,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2364,Ingen risiko,Hyacinthus orientalis,NaN,NaN,2021-02-23 20:20:22,NaN,Observeres hjemme,Psykiatriske sygdomme,Akut forgiftning,BIO,"[[STARTINFO]]nhan0003, 23-2-2021 20:31:43[[END...",2021-02-23 20:27:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]nhan0003, 23-2-2021 20:31:43[[END...",9990.0,Skagen,83,Hyacint,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8509,Ingen risiko,NaN,NaN,NaN,2018-12-02 23:18:06,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]tchr0287, 2-12-2018 23:19:03[[END...",2018-12-02 23:15:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tchr0287, 2-12-2018 23:19:03[[END...",2750.0,Ballerup,76,Afkalkningsmiddel surt,NaN,NaN,NaN,NaN,Forveksling,NaN,NaN,Levnedsmiddel
2013,Ingen risiko,NaN,NaN,NaN,2022-12-20 09:30:37,NaN,Ingen,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]rlar0142, 20-12-2022 09:42:35[[EN...",2022-12-20 09:26:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 20-12-2022 09:42:35[[EN...",5500.0,Middelfart,87,Afkalkningsmiddel surt,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1426,Risiko for begrænset forgiftning,NaN,NaN,NaN,2022-09-10 14:36:05,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]anel0004, 10-9-2022 15:00:10[[END...",2022-09-10 14:43:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 10-9-2022 15:00:10[[END...",2610.0,Rødovre,82,Opvaskemidler (til håndopvask),Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2073,NaN,Tapetopbløder polyfilla,NaN,NaN,2022-12-27 09:42:38,NaN,NaN,NaN,Teoretisk forespørgsel,SPECIALDONOTDELETE,"[[STARTINFO]]ahan0164, 29-12-2022 09:52:22[[EN...",2022-12-29 09:28:54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]ahan0164, 29-12-2022 09:52:22[[EN...",5953.0,Tranekær,71,Tapetopbløder polyfilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6242,Risiko for manifest forgiftning,NaN,NaN,NaN,2019-05-23 21:51:42,NaN,Skadestue,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]keri0026, 23-5-2019 21:57:46[[END...",2019-05-23 21:48:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]keri0026, 23-5-2019 21:57:46[[END...",2840.0,Holte,82,Ecostyle ukrudts middel,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025,Ingen risiko,NaN,NaN,NaN,2022-12-21 08:19:36,NaN,egen læge,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]rlar0142, 21-12-2022 13:21:59[[EN...",2022-12-21 13:16:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]rlar0142, 21-12-2022 13:21:59[[EN...",8950.0,Ørsted,72,Afkalkningsmiddel surt,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5700,Risiko for begrænset forgiftning,NaN,NaN,NaN,2019-01-11 08:41:34,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]mann0002, 11-1-2019 08:47:43[[END...",2019-01-11 08:39:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]mann0002, 11-1-2019 08:47:43[[END...",7700.0,Thisted,95,Maskinopvaskemiddel ikke industrielt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2087,NaN,metasilikat,NaN,NaN,2022-12-31 04:07:30,NaN,NaN,NaN,NaN,KEMI,"[[STARTINFO]]rlar0142, 31-12-2022 04:08:17[[EN...",2022-12-31 03:55:53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Esbjerg Centralsygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6870.0,Ølgod,70,Maskinopvaskemiddel ikke industrielt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1252,Risiko for begrænset forgiftning,Symphoricarpos albus,NaN,nogle,2022-08-09 12:27:06,NaN,Ingen,NaN,Akut forgiftning,BIO,"[[STARTINFO]]KERI0026, 9-8-2022 12:29:41[[ENDI...",2022-08-09 12:24:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arbejdsplads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 9-8-2022 12:29:41[[ENDI...",3060.0,Espergærde,71,Snebær,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2940,Risiko for begrænset forgiftning,NaN,NaN,1,2021-06-18 07:45:13,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]anel0004, 18-6-2021 08:17:03[[END...",2021-06-18 07:56:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]anel0004, 18-6-2021 08:17:03[[END...",5471.0,Søndersø,90,Opvaskemidler (til håndopvask),Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,Risiko for manifest forgiftning,Blandede ikke chlorerede kulbrinter,NaN,4,2022-02-10 11:23:18,NaN,Indlæggelse,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]msoe0664, 10-2-2022 11:32:25[[END...",2022-02-10 11:22:26,Alkohol,NaN,NaN,NaN,NaN,NaN,Ethanol,NaN,NaN,NaN,DIVERSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Praksis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]msoe0664, 10-2-2022 11:32:25[[END...",6330.0,Padborg,77,Petroleum,NaN,NaN,NaN,NaN,Forveksling,NaN,NaN,NaN
4735,NaN,NaN,NaN,NaN,2020-06-26 17:40:04,NaN,NaN,NaN,NaN,KEMI,NaN,2020-06-26 17:33:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Roskilde Amts Sygehus, Køge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]sgre0034, 26-6-2020 17:40:15[[END...",4671.0,Strøby,81,Kvarternære ammoniumforbindelser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1569,NaN,NaN,NaN,NaN,2022-10-04 09:33:07,NaN,NaN,NaN,NaN,RUS,"[[STARTINFO]]tvan0009, 4-10-2022 09:55:51[[END...",2022-10-04 09:32:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 4-10-2022 09:55:51[[END...",8240.0,Risskov,84,Teoretisk forespørgsel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Risiko for begrænset forgiftning,NaN,NaN,200,2022-02-03 15:00:18,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]cdit0001, 3-2-2022 17:44:14[[ENDI...",2022-02-03 17:25:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,plejehjem,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]cdit0001, 3-2-2022 17:44:14[[ENDI...",4070.0,Kirke Hyllinge,91,Kvarternære ammoniumforbindelser,Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1558,NaN,Paxillus involutus,NaN,NaN,2022-10-02 21:04:25,NaN,NaN,NaN,NaN,BIO,NaN,2022-10-02 21:01:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vejle Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 2-10-2022 21:05:34[[END...",7323.0,Give,78,Almindelig Netbladhat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5389,Ingen risiko,NaN,NaN,NaN,2020-11-01 17:41:02,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]tchr0287, 1-11-2020 17:43:01[[END...",2020-11-01 17:38:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kvinde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tchr0287, 1-11-2020 17:43:01[[END...",2860.0,Søborg,71,Kvarternære ammoniumforbindelser,NaN,NaN,NaN,NaN,Forveksling,NaN,NaN,NaN
3851,Risiko for manifest forgiftning,"aqua, aluminiumschlorid",NaN,NaN,2021-12-05 18:00:20,NaN,Skadestue,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]KERI0026, 5-12-2021 18:41:20[[END...",2021-12-05 18:29:55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vagtlæge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]KERI0026, 5-12-2021 18:41:20[[END...",5270.0,Odense N,82,DSB: det stopper blodet,NaN,NaN,NaN,NaN,Forveksling,NaN,NaN,NaN
7515,Ingen risiko,NaN,NaN,NaN,2018-04-10 08:38:07,NaN,Observeres hjemme,NaN,Akut forgiftning,KEMI,"[[STARTINFO]]GHOE0014, 10-4-2018 08:47:47[[END...",2018-04-10 08:37:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Øvrige sundhedsvæsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]GHOE0014, 10-4-2018 08:47:47[[END...",2650.0,Hvidovre,79,Opvaskemidler (til håndopvask),Ulykke/uheld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3362,NaN,NaN,NaN,NaN,2021-08-31 13:12:04,NaN,NaN,NaN,NaN,RUS,NaN,2021-08-31 13:06:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Åbenrå,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sygehus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[[STARTINFO]]tvan0009, 31-8-2021 13:16:05[[END...",6372.0,Bylderup-Bov,71,Teoretisk forespørgsel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Top 50 medicine matches in 'old' (canonical names):

                    medicine  count
0                paracetamol   1235
1         metoprololsuccinat    372
2                    digoxin    323
3                   zopiclon    305
4              kaliumchlorid    294
5                      furix    274
6          acetylsalicylsyre    273
7             losartankalium    268
8                 mirtazapin    267
9       tramadolhydrochlorid    251
10                 quetiapin    244
11                 amlodipin    242
12               pantoprazol    231
13             elektrolytter    222
14                   eliquis    219
15                flumazenil    216
16                  oxazepam    207
17      oxycodonhydrochlorid    202
18                 donepezil    202
19               clopidogrel    197
20                 sertralin    192
21                   naloxon    180
22                gabapentin    178
23                  zolpidem    169
24                 metformin    168
25                  levodopa    167
26               simvastatin    166
27                 contalgin    162
28              atorvastatin    161
29                   xarelto    156
30                 ibuprofen    156
31                    morfin    155
32                citalopram    155
33               methotrexat    150
34  codeinphosphathemihydrat    150
35                 enalapril    149
36                pregabalin    148
37                  eltroxin    142
38                lamotrigin    135
39                   litarex    116
40                  diazepam    109
41    venlafaxinhydrochlorid    104
42      memantinhydrochlorid    104
43                 olanzapin    102
44                   madopar     88
45                  ramipril     88
46                alendronat     86
47           natriumvalproat     80
48         magnesiumhydroxid     75
49             levetiracetam     72

In [14]:
# Deleting "young" and "old" so we don't accidentally use them
del young, old

We now have data that represents rows, where there is a medicine mentioned. 
It must therefore be assumed, that the rest of the rows are not related to medical poisoning. 
These rows can therefore be deleted, and the new dataset can be reviewed to evaluate the next step in cleaning the data.

In [16]:
# Counting all the unique values in '[substans type(gift#)]'
import pandas as pd

def count_unique_substans_types(df, prefix=""):
    all_types = []
    for i in range(1, 16):
        col_subst = f'[substans type(gift{i})]'.lower()
        if col_subst in df.columns:
            # Drop NAs
            vals = df[col_subst].dropna().tolist()
            all_types.extend(vals)
    # Now count unique values
    type_counts = pd.Series(all_types).value_counts()

    print(f"\n=== {prefix} Unique values in all [substans type(gift#)] columns, counted: ===\n")
    print(type_counts)

# For both sheets:
count_unique_substans_types(young_filtered, "Alder<70")
count_unique_substans_types(old_filtered, "Alder>70")

=== Alder<70 Unique values in all [substans type(gift#)] columns, counted: ===

MED                   48465
ZZMED                 28666
RUS                    5337
DIVERSE                3968
KEMI                   1735
SPECIALDONOTDELETE     1548
BIO                     569
Name: count, dtype: int64

=== Alder>70 Unique values in all [substans type(gift#)] columns, counted: ===

MED                   6372
ZZMED                 3641
SPECIALDONOTDELETE     190
DIVERSE                133
KEMI                    78
BIO                     50
RUS                     49
Name: count, dtype: int64

In [17]:
# Finding all the unique values for RUS, DIVERSE, KEMI, SPECIALDONOTDELETE, BIO 
# To check for mislabeled medicines.
import pandas as pd

def count_special_substances(df, prefix=""):
    include_types = ['RUS', 'DIVERSE', 'KEMI', 'SPECIALDONOTDELETE', 'BIO']
    all_names = []

    for i in range(1, 16):
        col_type = f'[substans type(gift{i})]'.lower()
        col_gn = f'[generisk navn(gift{i})]'.lower()
        col_navn = f'[navn(gift{i})]'.lower()
        
        if all(col in df.columns for col in [col_type, col_gn, col_navn]):
            mask = df[col_type].isin(include_types)
            all_names.extend(df.loc[mask, col_gn].dropna().tolist())
            all_names.extend(df.loc[mask, col_navn].dropna().tolist())

    counts = pd.Series(all_names).value_counts()
    
    # Only show entries with at least 10 occurrences
    counts_10plus = counts[counts >= 10]

    print(f"\n=== {prefix} Combined names (filtered by unique_medicine_names.txt, at least 10 occurrences), counted: ===\n")
    print(counts_10plus)


# For both sheets:
count_special_substances(young_filtered, "Alder<70")
count_special_substances(old_filtered, "Alder>70")

=== Alder<70 Combined names (filtered by unique_medicine_names.txt, at least 10 occurrences), counted: ===

Ethanol                               3765
Alkohol                               3200
Cocain                                1339
Amfetamin                             1177
Kokain                                1039
Cannabis                               607
Hash                                   560
Ketamin                                544
GHB                                    444
Gamma Hydroxy Butyrat                  371
MDMA                                   366
CNS-stimulantia                        357
Methylenedioxymethamphetamine          339
Ukendt                                 335
Spiritus                               335
Dinitrogenoxid 100%                    325
Lattergas                              325
alkohol                                309
Øl                                     242
Ethanol > 75%                          188
Ukendt rusmiddel                       182
Imidacloprid                           174
Myrelokkedåse                          147
Vodka                                  144
Vin                                    142
Heroin                                 139
Diacetylmorfin                         133
Andre rusmidler                        113
Natriumchlorid, urea                   111
Vejsalt                                110
Håndsprit                               94
LSD                                     83
deprimerende                            80
Lysergsyrediethylamid                   79
ukendt                                  75
Caffeine                                71
vodka                                   66
Myresyre                                64
Stimulerende                            57
Koffein                                 54
Methamfetamin                           54
unikalk                                 54
Bitter mandel                           49
brintellix                              45
Ecstacy                                 43
Hypoklorit                              41
Perikon                                 38
Echiichtys draco                        37
Marihuana                               37
Fjæsing                                 37
Hveps                                   37
Acetone                                 36
ozempic                                 35
benzodiazepin                           34
intuniv                                 34
p-piller                                33
Vipera berus                            32
øl                                      32
                                        32
Hugorm                                  31
Teoretisk forespørgsel                  30
Psilocybe semilanceata                  30
Apis mellifera                          29
jardiance                               29
lurasidon                               29
apoquel                                 29
xanax                                   28
latuda                                  28
heroin                                  28
Forespørgsel                            28
Ethylenglykol                           27
Pebermynteolie                          27
Svampe - ukendte                        26
colchicin                               26
Kulilte                                 25
Toiletrengøring                         25
Æteriske olier                          24
Æterisk olie                            24
PCP                                     24
Brintellix                              23
Propan, butan                           22
tecfidera                               22
Methanol                                22
Phencyclidin                            22
Kølervæske                              21
Brandrøg indendørs                      21
vortefri                                21
GBL                                     20
Noget i drink, Deprimerende             20
vin                                     20
Nikotin ( e-cigaret )                   20
Lightergas                              20
Whisky                                  19
Iod                                     18
myresyre                                18
Gamma Butyrolacton                      18
Brandmand                               18
Ozempic                                 18
Cyanea capillata, Cyanea lamarckii      18
Noget i drink, Stimulerende             17
Klorin 5%                               17
Ammoniak                                17
vortioxetin                             17
WC rens                                 17
ethanol                                 16
kosttilskud                             16
Intuniv                                 16
forespørgsel                            16
Deltamethrin                            16
Vortefri                                15
ukendt medicin                          15
medanef                                 15
Myregift                                15
Rødvin                                  15
guanfacin                               14
Afkalkningsmiddel surt                  14
stærk base                              14
Fluortandpasta                          14
Tecfidera                               14
rødvin                                  14
lamotrigen                              14
Psykotomimetisk                         14
Neglelakfjerner                         14
Wodka                                   14
briviact                                13
Svampe - symptomer                      13
Spids Nøgenhat                          13
Opiater                                 13
mdma                                    13
bravecto                                13
Afløbsrens                              13
Unikalk                                 13
Xanax                                   13
valium                                  12
attentin                                12
Crystal Meth                            12
Rengøringsmiddel                        12
Muskatnød                               11
sibutramin                              11
Speed                                   11
 flour                                  11
deltamethrin                            11
Kulbrinter, flygtige                    11
Apoquel                                 11
Joint                                   11
Bravecto                                11
kokain                                  11
lipistad                                11
Denatureret sprit                       11
vitamin c                               10
Isopropylalkohol                        10
Hallucinogene svampe                    10
melatonin                               10
vitaminer                               10
reagila                                 10
Salt                                    10
Klor                                    10
Klorin ukendt konc                      10
Gamma-Hydroxybutyrat (GHB)              10
ketamin                                 10
hostesaft                               10
ghb                                     10
Paravespula vulgaris                    10
Name: count, dtype: int64

=== Alder>70 Combined names (filtered by unique_medicine_names.txt, at least 10 occurrences), counted: ===

Ethanol     118
Alkohol      87
unikalk      36
Ukendt       24
Unikalk      15
alkohol      13
Vin          11
kaleroid     10
Spiritus     10
ozempic      10
Name: count, dtype: int64

In [7]:
# Finding all the unique values for RUS, DIVERSE, KEMI, SPECIALDONOTDELETE, BIO 
# To check for mislabeled medicines.
# Cross checking with the list of medicines from lægemiddelstyrelsen.
# Showing only entries with 10 or more occurences.

import pandas as pd

def load_medicine_names(filename):
    with open(filename, encoding='utf-8') as f:
        meds = {line.strip() for line in f if line.strip()}
    return meds

def count_special_substances_filtered(df, medicine_set, prefix=""):
    include_types = ['RUS', 'DIVERSE', 'KEMI', 'SPECIALDONOTDELETE', 'BIO']
    all_names = []

    for i in range(1, 16):
        col_type = f'[substans type(gift{i})]'.lower()
        col_gn = f'[generisk navn(gift{i})]'.lower()
        col_navn = f'[navn(gift{i})]'.lower()
        
        if all(col in df.columns for col in [col_type, col_gn, col_navn]):
            mask = df[col_type].isin(include_types)
            all_names.extend(df.loc[mask, col_gn].dropna().tolist())
            all_names.extend(df.loc[mask, col_navn].dropna().tolist())

    # Filter names to those present in your medicine list
    filtered_names = [name for name in all_names if name in medicine_set]
    counts = pd.Series(filtered_names).value_counts()

    # Only show entries with at least 10 occurrences
    counts_10plus = counts[counts >= 10]

    print(f"\n=== {prefix} Combined names (filtered by unique_medicine_names.txt, at least 10 occurrences), counted: ===\n")
    print(counts_10plus)

    # Optionally, save to CSV:
    # counts_10plus.to_csv(f'filtered_combined_names_{prefix}_10plus.csv')

# Usage:
medicine_set = load_medicine_names('unique_medicine_names.txt')

count_special_substances_filtered(young_filtered, medicine_set, "Alder<70")
count_special_substances_filtered(old_filtered, medicine_set, "Alder>70")

=== Alder<70 Combined names (filtered by unique_medicine_names.txt, at least 10 occurrences), counted: ===

brintellix      45
ozempic         35
intuniv         34
jardiance       29
apoquel         29
lurasidon       29
latuda          28
colchicin       26
tecfidera       22
myresyre        18
medanef         15
bravecto        13
briviact        13
attentin        12
deltamethrin    11
lipistad        11
reagila         10
melatonin       10
ketamin         10
vitamin c       10
Name: count, dtype: int64

=== Alder>70 Combined names (filtered by unique_medicine_names.txt, at least 10 occurrences), counted: ===

ozempic    10
Name: count, dtype: int64

In [8]:
# Fine adjustments of list by hand
#First list: items to add
additions=['brintellix','ozempic','benzodiazepin','xanax','lamotrigen','valium']


# Second list: items to remove
deletions=['apoquel','myresyre','brevecto','deltamethrin','mandel','vitamin c','ketamin']

In [9]:
# Adding and deleting
import pandas as pd

def load_medicine_names(filename):
    with open(filename, encoding='utf-8') as f:
        meds = {line.strip() for line in f if line.strip()}
    return meds

# Your additions and deletions (lowercased for consistency)
additions = ['benzodiazepin','xanax','lamotrigen','valium']
deletions = ['apoquel','myresyre','brevecto','deltamethrin','mandel','vitamin c','ketamin']

# Step 1: Load initial medicine set
medicine_set = load_medicine_names('unique_medicine_names.txt')

# Step 2: Apply additions and deletions
# Normalize case: ensure all comparison is lower, and apply consistently
medicine_set = set(m.lower() for m in medicine_set)
medicine_set.update(a.lower() for a in additions)
medicine_set.difference_update(d.lower() for d in deletions)

# Step 3: Show the final list (sorted for readability)
final_list = sorted(medicine_set)
print("Final medicine name list:")
for name in final_list:
    print(name)

Final medicine name list:
(131-i)meta-iodobenzylguanidine diagn. ge healthca
(131-i)meta-iodobenzylguanidine therap. ge health.
13c-urea
3-iodobenzylguanidinsulfat, iobenguan (123-i)
5-aminolevulinsyre
[64cu] kobberchlorid
abacavir, lamivudin
abacavir/lamivudin
abacavir/lamivudine
abacavirhydrochlorid, lamivudin
abacavirsulfat
abacavirsulfat, dolutegravir, lamivudin
abacavirsulfat, dolutegravirnatrium, lamivudin
abacavirsulfat, lamivudin
abacavirsulfat, lamivudin, zidovudin
abaloparatid
abasaglar
abasaglar kwikpen
abasaglar tempo pen
abatacept
abavalex
abbonate
abboticin
abboticin novum
abdomin citrus
abdomin junior neutral
abdomin neutral
abecma
abemaciclib
abevmy
abigerd
abilify
abilify maintena
abirateron
abirateronacetat
abirateronacetat, niraparib-tosylatmonohydrat
abiraterone
abiraterone “vivanta”
abraxane
abrocitinib
abrysvo
abseamed
absimky
abstral
acalabrutinib
acalabrutinibmaleat
acamprosatcalcium
acarizax
accofil
aceinhib
aceprolab
acepromazinmaleat
acetazolamid
acetylcystein
acetylcysteine
acetylisovaleryltylosintartrat
acetylsalicylsyre
acetylsalicylsyre carefarm
acetylsalicylsyre, caffein
acetylsalicylsyre, clopidogrelhydrogensulfat
acetylsalicylsyre, dipyridamol
acetylsalicylsyre, komb. excl. psykoleptika
aciclodan
aciclovir
aciclovir al
aciclovir carefarm
aciclovir, hydrocortison
aciniks
acipimox
acitretin
acivir
aclasta
aclidiniumbromid
aclidiniumbromid, formoterolfumarat dihydrat
aclonia
acnatac
acnenor
acoramidishydrochlorid
acrivastin
actelsar hct
actikerall
actilax
actilyse
actiq
activelle
activelle low
activyl til ekstra storehunde
activyl til mellemstore hunde
activyl til miniaturehunde
activyl til små hunde
activyl til små katte
activyl til store hunde
activyl til store katte
actos
actraphane 10 novolet
actraphane 20 novolet
actraphane 30
actraphane 30 flexpen
actraphane 30 innolet
actraphane 30 penfill
actraphane 40 penfill
actraphane 50 penfill
actrapid
actrapid flexpen
actrapid innolet
actrapid penfill
acular
acvybra
adagrasib
adalat la
adalat oros
adalimumab
adapalen
adapalen, benzoylperoxid, vandig
adapalen, kombinationer
adapalene/benzoyl peroxide
adasuve
adaxio vet.
adcetris
adcirca
addimag vet.
adempas
adenocor
adenosin
adenuric
adequan vet.
adhesa
adipine
adixemin
adjupanrix
adport
adrenalin
adrenalin, articainhydrochlorid
adrenalin, mepivacainhydrochlorid
adrenalintartrat
adrenalintartrat, articainhydrochlorid
adrenalintartrat, lidocainhydrochlorid
adrenalintartrat, lidocainhydrochlorid, vandfrit
adrenalintartrat, lidocainhydrochloridmonohydrat
adrenalintartrat, mepivacainhydrochlorid
adrenalintartrat, procainhydrochlorid
adreview, iobenguane (i-123) injection
adriamycin
adrovance
adtab til hunde 1.3-2.5 kg
adtab til hunde >11-22 kg
adtab til hunde >2.5-5.5 kg
adtab til hunde >22-45 kg
adtab til hunde >5.5-11 kg
adtab til katte 0.5-2.0 kg
adtab til katte >2.0-8.0 kg
adtralza
aduvanz
advagraf
advantage vet. til hund
advantage vet. til hunde (10-25 kg)
advantage vet. til hunde (4-10 kg)
advantage vet. til kat
advantage vet. til katte (4 kg og derover)
advate
advocate til ekstra store hunde
advocate til mellemstore hunde
advocate til små hunde
advocate til små katte og fritter
advocate til store hunde
advocate til store katte
adynovi
adzynma
aerinaze
aerius
aerivio spiromax
aerobec
aerobec autohaler
aesculaforce forte
aethoxysklerol
afamelanotid
afatinib
afinitor
afiveg
aflibercept
aflunov
aforbe
afoxolaner
afoxolaner, eprinomectin, praziquantel
afoxolaner, milbemycinoxim
afqlir
afstyla
agalsidase alfa
agalsidase beta
agamree
agenerase
ageniprim
agilus
aglepristone
agodep
agomelatin
ahzantive
aimovig
ainil
airapy
airexar spiromax
airflusal aerosol
airflusal forspiro
airflusal sprayhaler
airomir
airomir autohaler
airsalb
aitgrys
aitmyte
aivlosin
aivlosin til fasaner
aivlosin til kalkuner
aivlosin til kyllinger
ajovy
akantior
akeega
akineton
aklief
aktiprol
aktivt kul
akynzeo
alacare
alamycin prolongatum vet.
alanylglutamin
alarimed
albendazol
albiotic
albumin
albumin, human
albumin, human, technetium (99m-tc) humanalbumin
albunorm
albutrepenonacog alfa
alcort
aldara
aldurazyme
alecensa
alectinibhydrochlorid
alemtuzumab
alendronat
alendronat/cholecalciferol
alendronate/cholecalciferol
alendronsyre og colecalciferol
alensol
alfa-1 proteinaseinhibitor, humant
alfacalcidol
alfacalcidol cande
alfacalcidol carefarm
alfadexx
alfaglandin c
alfax multidose vet.
alfaxalonum
alfentanil
alfentanilhydrochlorid
alfuzosin
alfuzosinhydrochlorid
alglucosidase alfa (rhgaa)
algovil
alhemo
alimta
alirocumab
alisade
aliskirenfumarat
aliskirenfumarat, hydrochlorthiazid
alitretinoin
alitretinoin orifarm
alizin vet.
alk (108) betula verrucosa
alk (225) phleum pratense
alk (312) artemisia vulgaris
alk (503) dermatophagoides pteronyssinus
alk (504) dermatophagoides farinae
alk (553) hundehår
alk (555) kattehår
alk (801) bigift
alk (802) hvepsegift
alk 402 alternaria alternata
alk 405 aspergillus fumigatus
alk 417 cladosporium herbarum
alk 701 hønseæg
alk 713 komælk rå
alk 725 sild
alk 726 torsk
alk 729 krabbe
alk 731 reje
alk 762 jordnød
alk 764 mandel
alk 778 sojabønne
alk 779 hvedemel
alk soluprick negativ kontrol
alk soluprick positiv kontrol
alk-diluent
alkacit
alkeran
alkindi
allergodil
allergodil forte
allergone
alli
allopurinol
alluzience
alminox
almogran
almotriptan
almotriptan dl-hydrogen maleat
almoxin vet.
alnodine
alnok
alofisel
alogliptinbenzoat
alogliptinbenzoat, metforminhydrochlorid
alogliptinbenzoat, pioglitazonhydrochlorid
aloxi
alpelisib
alpha ject 3000
alphagan
alpramil vet.
alprazolam
alprimox
alprolix
alprostadil
alprostadil carefarm
alprox
altaromin
alteplase
alterfast
alternaria alternata
altifex
altrenogest
altresyn
altuvoct
alunbrig
alunbrig startpakke
aluvia
alvegesic vet.
alvesco
alyftrek
alymsys
alzane
amantadinhydrochlorid
ambirix
ambisome liposomal
ambofoz
ambrisentan
ambrisentan viatris
ambroxolhydrochlorid
amdocyl
amelgen
ameluz
amflee vet.
amgevita
amglidia
amidazed
amifampridine serb
amifampridinphosphat
amikacin
amikacinsulfat
amilco
amiloridhydrochlorid dihydrat, hydrochlorthiazid
amiloridhydrochlorid, vandfrit, furosemid
aminolaevulinsyrehydrochlorid
aminoplasmal
aminoplasmal elektrolyt
aminoven 10%
aminoven forte
amiodaron
amiodaron hameln
amiodaronhydrochlorid
amiped
amisulprid
amitraz
amitriptylin
amitriptylinhydrochlorid
amivantamab
amlodipin
amlodipin sandoz
amlodipin/valsartan
amlodipin/valsartan/hydrochlorthiazid
amlodipinbesilat
amlodipinbesilat, hydrochlorthiazid, valsartan
amlodipinbesilat, ramipril
amlodipinbesilat, telmisartan
amlodipinbesilat, valsartan
amlodipine
amlodipine/valsartan
amlodipine/valsartan/hydrochlorothiazide
amlodistad
amlodorion
amlohexal
ammonaps
amodip
amorina
amorolfinhydrochlorid
amoxar
amoxibactin vet.
amoxicillin
amoxicillin carefarm
amoxicillin, clavulansyre
amoxicillin/clavulansyre
amoxicillin/clavulansyre aurobindo
amoxicillinnatrium
amoxicillinnatrium, kaliumclavulanat
amoxicillintrihydrat
amoxicillintrihydrat, clavulansyre
amoxicillintrihydrat, kaliumclavulanat
amoxinsol 50 vet.
amoxival vet.
amoxonor
amphen
amphotericin b
amphotericin b liposomal
ampicillin
ampicillin/sulbactam
ampicillinnatrium
ampicillinnatrium, sulbactamnatrium
ampicillintrihydrat
ampitar
amprenavir
ampres
amproline
amprolium
amproliumhydrochlorid
amroliv
amsacrin
amsalyo
amsparity
amversio
amvuttra
amylmetacresol, dichlorbenzylalkohol
amyvid
amzolynic
anafranil
anafranil retard
anagrelid
anagrelide
anagrelide viatris
anagrelidhydrochlorid
anagrelidhydrochloridmonohydrat
anakinra
anapen
anapen junior
anastelb
anastrella
anastrella 28
anastrozol
anatera
ancozan
ancozan comp
andabra
andatin
andembry
andexanet alfa
andolex
andre midler mod led- og muskelsmerter, udvortes
androcur
androcur depot
andusomeran
anesketin
angiotensin ii acetat
angusta
anidulafungin
anifrolumab
aniketam vet.
animedazon spray
animeloxan
anopyrin
anoro ellipta
antabus
antabuse
antazolinsulfat, naphazolinnitrat
antepsin
anti t-lymphocyt immunoglobulin (equin oprindelse)
anti-d (rh) immunoglobulin
anti-d immunglobulin, humant
antirobe vet.
antisedan vet.
antistina-privin
antithymocytglobulin (kanin)
antitrombin iii
antoreq
anzupgo
apacross
apadamtase alfa
apalutamid
apealea
apelka vet.
apexelsin
aphiahsone
apidra
apidra solostar
apiguard vet.
apinovia
apiretam
apivar
apixaban
apixerin
apo-go pen
apo-go pod
apo-go pumpfill
apobilen
apomorfin
apomorphinhydrochlorid
apomorphinhydrochlorid hemihydrat
apotel
apovit b-combin stærk
apovit b1 vitamin ekstra stærk
apovomin vet.
apozepam
apraclonidinhydrochlorid
apramycinsulfat
apravet ws
apremilast
apremilast accord
apremilast startpakke
aprepitant
apretude
aprocitentan
aprokam
aprotinin
aprovel
aptivus
apydan
aquacycline vet.
aqualec
aquavac erm vet.
aquavac relera vet.
aquavac vibrio vet.
aquipta
aqumeldi
aranesp
arava
arax
arax extra
arax forte
arax hot
arax junior
arcoxia
arctic root rosenrod
areleptan
arelzamio
arexvy
argatroban (vandfri)
argininhydrochlorid, lysinhydrochlorid
argipressin
ariclaim
arikayce liposomal
arimidex
aripiprazol
aripiprazole
aripiprazolmonohydrat
aritavi
arixtra
arlevert
armisarte
aromasin
aropilo sr
arpoya
arsenic trioxide
arsenic trioxide mylan
arseniktrioxid
arsentrioxid
artelac
artenimol, piperaquin fosfat
artesunat
artesunat, pyronaridintetraphosphate
artesunate amivas
arthricox
arthrotec
arthrotec forte
arti-cell forte
artiss
arupsan
asacol
asciminibhydrochlorid
ascorbinsyre
ascorbinsyre, ferrofumarat
asenapin maleat
aservo equihaler
asfotase alfa
asmanex twisthaler
asparaginase, l-, rekombinant, e. coli
aspaveli
aspergillus fumigatus
astepro
asubtela
atacand
atacand zid 16 mg/12,5 mg
atacand zid 32 mg/12,5 mg
atacand zid 32mg /25 mg
atacand zid 8 mg/12,5 mg
ataluren
atazanavir
atazanavirsulfat
atazanavirsulfat, cobicistat
atectura breezhaler
atenativ
atenodan
atenolol
atezolizumab
atgam
atidarsagene autotemcel
atimos
atinvicitinib
atipam
atipamezolhydrochlorid
atogepantmonohydrat
atomoxetin
atomoxetin teva
atomoxetine
atomoxetinhydrochlorid
atopica vet.
atorker
atorvastatin
atorvastatin xiromed
atorvastatincalcium
atorvastatincalcium (trihydrat)
atorvastatincalcium (trihydrat), ezetimib
atosiban
atosibanacetat
atovaquon
atovaquon, proguanilhydrochlorid
atovaquone
atovaquone/proguanil
atozet
atriance
atropin
atropine
atropinsulfat
atrovent
atrovent nasal
attane vet.
attentin
aubagio
aucatzyl
augermid
augmentin forte
augtyro
aurizon vet.
aurovet
avacopan
avaglim
avalglucosidase alfa
avamys
avanafil
avandamet
avandia
avapritinib
avastin
avatrombopagmaleat
avaxim
avaxim junior
avelumab
avibactamnatrium, aztreonam
avibactamnatrium, ceftazidim
avipro ae
avipro ib h 120
avipro ibd lc-75 vet.
avipro ibd v217
avipro thymovac
aviptadil, phentolaminmesilat
avishield ib gi-13
avishield ib h120
avishield ib qx
avishield ibd plus
avishield nd b1
avonex
avtozma
avzivi
awiqli
axhidrox
axicabtagenciloleucel
axitinib
axiumopto
axumin
axura
aybintio
ayvakyt
azacitidin
azacitidine
azacitidine betapharm
azacitidine kabi
azalia
azaperon
azaporc
azarga
azathioprin
azatioprin
azecort
azeflone
azelainsyre
azelastine hydrochloride/fluticasone
azelastinhydrochlorid
azelastinhydrochlorid, fluticasonpropionat
azelastinhydrochlorid/fluticasonpropionat
azilect
azilsartan kamedoxomil
azithromycin
azithromycin sandoz
azithromycin teva
azithromycindihydrat
azithromycinmonohydrat
azithromycinmonohydrat-hemiethanolat
azomyr
azopt
aztarol
aztreonamlysin
azyter
azzalure
baclofen
bactocin
bactroban
bactroban nasal
baiama
baklofen
balance 1,5 % glucose, 1,25 mmol/l calcium
balance 1,5 % glucose, 1,75 mmol/l calcium
balance 2,3 % glucose, 1,25 mmol/l calcium
balance 2,3 % glucose, 1,75 mmol/l calcium
balance 4,25 % glucose, 1,25 mmol/l calcium
balance 4,25 % glucose, 1,75 mmol/l calcium
balancid novum
balidax
baloxavirmarboxil
balsalaziddinatriumdihydrat
balversa
baqsimi
baraclude
baricitinib
bariumsulfat
basiliximab
basiron
basiron wash
bavencio
baxiren
baxogar
baxumil
baycox iron
baycoxine vet.
bayticol pour-on vet.
baytril vet.
bayvantic vet.
bayvantic vet. til hunde 10-25 kg
bayvantic vet. til hunde 25-40 kg
bayvantic vet. til hunde 4-10 kg
bayvantic vet. til hunde op til 4 kg
bazedoxifen
bazedoxifenacetat, østrogener, konjugerede
bcg
bcg medac
bcg vaccine
becaplermin
beclomet easyhaler
beclometasondipropionat
beclometasondipropionat carefarm
beclometasondipropionatmonohydrat
beconase
bedaquilinfumarat
bedinvetmab
befoair
bekemv
bekuval
belabel vet.
belantamab mafodotin
belatacept
belatamin vet.
belfer vet.
belimumab
belzutifan
bemeson
bemfola
bempedoinsyre
bempedoinsyre, ezetimib
bemrist breezhaler
benaday
benadil vet.
benadryl
benakor vet.
benaliv
benamix
benarhin
benazeprilhydrochlorid
benazeprilhydrochlorid, pimobendan
benazeprilhydrochlorid, spironolacton
bendamedac
bendamustin
bendamustine
bendamustinhydrochlorid
bendamustinhydrochloridmonohydrat
bendroflumethiazid, kaliumchlorid
bendroza
benefix
benelyte
benepali
benestermycin vet.
benferol
benlysta
benralizumab
benserazidhydrochlorid, levodopa
benylan
benysine
benzathincefapirin
benzocain
benzocain, myrratinktur
benzodiazepin
benzoylperoxid, vandfrit
benzoylperoxid, vandfrit, clindamycin
benzoylperoxid, vandig
benzoylperoxid, vandig, clindamycinphosphat
benzydaminhydrochlorid
benzylpenicillin
benzylpenicillin vetcare
benzylpenicillin, procain
benzylpenicillin, procain, monohydrat
benzylpenicillin, procain, neomycin
benzylpenicillinkalium
benzylpenicillinnatrium
beovu
beqvez
beremagene geperpavec
berinert
berodual
beromun
berotralstathydrochlorid
bertolix
besilesomab
besponsa
besremi
betacaroten
betaferon
betafuse vet.
betahistin
betahistindihydrochlorid
betahistine
betain
betaklav
betalataz
betaloc zok
betamethason
betamethason, calcipotriol
betamethason/salicylsyre
betamethasonacetat, florfenicol, terbinafin
betamethasonacetat, terbinafin
betamethasondinatriumphosphat, calcipotriol
betamethasondipropionat
betamethasondipropionat, calcipotriol
betamethasondipropionat, calcipotriol hydrate
betamethasondipropionat, salicylsyre
betamethasonvalerat
betamethasonvalerat, clotrimazol, gentamicinsulfat
betamethasonvalerat, fusidinsyre
betamox vet.
betaserc
betaxololhydrochlorid
betiatide
betmiga
betnovat
betnovate
betolo
betolo appelsin
betolo honning & citron
betolo mint
betolvex
betoptic s
bettamousse
betula sp. (birk)
betula verrucosa/alba/pendula (birk)
bevacizumab
bevespi aerosphere
bevione
bevitan
bevitrio
bexaroten
bexarotene
bexsero
beyfortus
beyonttra
bezlotoxumab
bibrocatholum
bicalustad
bicalutamid
bicalutamid bluefish
bicalutamide
bicalutamide teva
bicavera 1,5 % glucose, 1,25 mmol/l calcium
bicavera 1,5% glucose, 1,75 mmol/l calcium
bicavera 2,3 % glucose, 1,25 mmol/l calcium
bicavera 2,3% glucose, 1,75 mmol/l calcium
bicavera 4,25 % glucose, 1,25 mmol/l calcium
bicavera 4,25% glucose, 1,75 mmol/l calcium
bicisathydrochlorid, technetium (99m-tc) bicisat
bifidobacterium longum, enterococcus faecium
bifoglan
biktarvy
bilaska
bilastin
bildyos
bilprevda
bimatix
bimatoprost
bimatoprost, timololmaleat
bimatoprost/timolol
bimatoprost/timolol zentiva
bimectin plus
bimectin vet.
bimekizumab
bimervax
bimoxyl la
bimprocil vet.
bimtim
bimzelx
binimetinib
binocrit
binosto
bio-biloba
bio-c-vitamin syreneutral
bio-qinon q10
biobhyo
bioclavid
biocom p vet.
biocom vet.
bioequin f
bioequin ft
bioestrovet
bioestrovet swine
biopoin
biorphen
biovac vet.
biperidenhydrochlorid
biperidenlactat
biphozyl
biquetan
biresp spiromax
bisacodyl
bismuthsubcitrat
bismuthsubnitrat
bismuthsubnitrat, tung
bisolvon
bisoprolol
bisoprololfumarat
bisoprololfumarat, hydrochlorthiazid
bitifrin
bitrisal
bivalirudin
bladasin
blenrep
bleomycin
bleomycin accord
bleomycinsulfat
blinatumomab
blincyto
blitzima
blomensy
bloxazoc
bluetongue virus serotype 8 antigen
bluetongue virus vaccine
bluetonguevirus
bluevac btv8
bluevac-3
bocouture
bomyntra
bonaxon
bondronat
bonjesta
bonqat
bonviva
bonyl
boostrix
boostrix polio
bopazir
bordetella bronchiseptica vaccine
borgal vet.
borsyre, calciumgluconat monohydrat
bortezomib
bosentan
bosentan, monohydrat
bosulif
bosutinib
bosutinib monohydrat
botox
botulinum toxin
bovalto
bovalto respi 2
bovela
bovifer
boviffens
bovigen rce vet.
bovilis blue-8
bovilis bovipast rsp
bovilis cryptium
bovilis nasalgen-c
bovilis ringvac vet.
bovilis rotavec corona vet.
bovilis rsp live vet.
boviqarai
braftovi
braltus
bramitob
branzil vet.
bravecto
bravecto combiuno
bravecto plus
bravecto til hunde 2-4,5 kg
bravecto til hunde >10-20 kg
bravecto til hunde >20-40 kg
bravecto til hunde >4,5-10 kg
bravecto til hunde >40-56 kg
bravecto til katte 1,2-2,8 kg
bravecto til katte >2,8-6,25 kg
bravecto til katte >6,25-12,5 kg
bravecto triuno
brensocatibmonohydrat
brentacort
brentan
brentuximab vedotin
bretaris genuair
bretovameran
brevibloc
brexpiprazol
brexucabtagen autoleucel
breyanzi
bricanyl
bricanyl retard
bricanyl turbohaler
bricanyl turbuhaler
bridion
brigatinib
brilique
brimica genuair
brimonidin
brimonidine/timolol
brimonidintartrat
brimonidintartrat carefarm
brimonidintartrat, brinzolamid
brimonidintartrat, timololmaleat
brimonidintartrat/timolol
brimozept
brinavess
brineura
brinsupri
brintellix
brinzolamid
brinzolamid, timololmaleat
brinzolamid/brimonidin
brinzolamid/brimonidintartrat carefarm
brinzolamid/timolol
brinzolamide
brinzolamide/brimonidine
brinzolamide/timolol
briumvi
brivaracetam
briviact
broadline katte 2,5 - 7,5 kg
broadline katte <2,5kg
brodalumab
brolucizumab
bromazepam
bromcriptinmesilat
bromfenac natrium sesquihydrat
bromhexin
bromhexinhydrochlorid
bronchitol
bropair spiromax
broxeltia
brucella abortus, stamme aq1302, protein extract
brucellin aquilon
brufen
brufen retard
brufen sr
brukinsa
btvpur
buccolam
budekron
budenocare
budenofalk
budenopar
budenova
budesonid
budesonid medical valley
budesonid sandoz
budesonid teva pharma
budesonid, formoterolfumarat dihydrat
budesonid/formoterolfumaratdihydrat
budesonide
bufomix easyhaler
bugvi
bulevirtidacetat
bultavo 3
bumacor
bumetanid
bumetanid carefarm
bunalict
bupaq multidose vet.
bupaq vet.
bupivacain
bupivacain-morfin sad
bupivacaine
bupivacainhydrochlorid monohydrat
bupivacainhydrochlorid, vandfri
bupredine vet.
buprefarm
buprelab
bupremyl
buprenorphin
buprenorphin carefarm
buprenorphin, komb.
buprenorphin/naloxon
buprenorphine
buprenorphinhydrochlorid
bupropion
bupropion hydrochloride
bupropionhydrochlorid
bupropionhydrochlorid, naltrexonhydrochlorid
burinex
buripal
buronil
burosumab
busalair
buscopan
buserelinacetat
busilvex
busol
buspiron
buspirone
buspironhydrochlorid
busulfan
butafosfan, cyanocobalamin
butagran equi
butamiratecitrate
butasal vet.
butedronsyre, technetium (99m-tc) butedronat
butomidor vet.
butorgesic vet.
butorphanoltartrat
butorvet
butoxvet
butrans
buventol easyhaler
buvidal
byannli
bydureon
byetta
byfavo
bylvay
byooviz
c1-esterase inhibitor, human
cabazitaxel
cabazitaxelmonohydrat
cabenex
cabergolin
cablivi
cabometyx
cabotegravir
cabotegravirnatrium
cabozantinib
cabozantinib (s)-malat
cabozantinib, cabozantinib (s)-malat
cadorex vet.
caelyx pegylated liposomal
caffein, ergotamintartrat
caffein, paracetamol
caffeincitrat
calcibel
calcibel forte
calcichew-d3 forte
calcifediolmonohydrat
calcigran forte
calciject 30+3 vet.
calciject 40 vet.
calcipotriol
calcipotriol, kombinationer
calcipotriol/betamethason
calcipotriol/betamethason carefarm
calcipotriol/betamethasone
calcipotriol/betamethasone sandoz
calcipotriolmonohydrat
calcitonin
calcitonin (laks)
calcitonin (laks, syntetisk)
calcium folinate
calcium-sandoz
calciumacetat, magnesiumcarbonat, tungt
calciumascorbatdihydrat
calciumcarbonat, calciumlactogluconat
calciumcarbonat, cholecalciferol
calciumcarbonat, magnesiumhydroxid
calciumchlorid
calciumchloriddihydrat
calciumchloridhexahydrat
calciumfolinat
calciumfolinate
calciumgluconat
calciumgluconat monohydrat
calciumlevofolinat
calciumpolystyrensulfonat
calciumpolystyrensulfonat carefarm
calciumtrinatriumpentetat
calmafusion
caloket
calquence
calrecia
camcevi
campral
camzyos
canagliflozin
canagliflozin, metforminhydrochlorid
canakinumab
canarypox virus vcp65 rekombinant
canaural
cancidas
candemox
candemox comp
canderion

In [10]:
# Next step is: eliminating based on substans type.
# We find the unique values in generisk navn and navn. cross check to see if it has a MED in as well. convert to MED if MED. if neither is the case, we can delete the row.
# # LAstly we eliminate the multiples.

In [11]:
# BIO elimination
import pandas as pd

def combined_bio_name_counts(df, prefix=""):
    # To collect all names (both generisk and navn) when type is BIO
    all_names = []

    for i in range(1, 16):
        col_subst = f'[substans type(gift{i})]'.lower()
        col_gn = f'[generisk navn(gift{i})]'.lower()
        col_navn = f'[navn(gift{i})]'.lower()

        # Ensure columns exist
        if all(col in df.columns for col in [col_subst, col_gn, col_navn]):
            mask = df[col_subst] == 'BIO'

            generics = df.loc[mask, col_gn].dropna().tolist()
            navns = df.loc[mask, col_navn].dropna().tolist()

            all_names.extend(generics)
            all_names.extend(navns)

    # Count all unique names (case-insensitive, optional)
    name_counts = pd.Series(all_names).value_counts()

    print(f"\n=== {prefix} Combined unique values ([generisk navn] and [navn]), counted: ===\n")
    print(name_counts)

# For both sheets:
combined_bio_name_counts(young_filtered, "Alder<70")
combined_bio_name_counts(old_filtered, "Alder>70")

=== Alder<70 Combined unique values ([generisk navn] and [navn]), counted: ===

Bitter mandel                                         49
Perikon                                               38
Fjæsing                                               37
Echiichtys draco                                      37
Hveps                                                 37
Vipera berus                                          32
Hugorm                                                31
Psilocybe semilanceata                                30
Apis mellifera                                        29
Svampe - ukendte                                      26
Brandmand                                             18
Cyanea capillata, Cyanea lamarckii                    18
Spids Nøgenhat                                        13
Svampe - symptomer                                    13
Paravespula vulgaris                                  10
Hallucinogene svampe                                  10
Liljekonval                                            9
Læge-Baldrian                                          9
Høst-Tidløs                                            9
Ukendt svamp                                           8
Digitalis purpurea                                     7
                                                       7
Fingerbøl                                              6
Pastinak                                               5
Galerina marginata                                     4
Baldrian                                               4
Stormhat                                               4
Rabarber                                               4
Bjørneklo                                              4
mandel                                                 4
Randbæltet Hjelmhat                                    4
Cyanogene glykosider i planter                         4
Kermesbær                                              3
Laurbær-Kirsebær                                       3
Ramsløg                                                3
Bittermandel                                           3
Benved                                                 3
Taks                                                   3
svampe                                                 3
Paxillus involutus                                     3
Dansk Ingefær                                          3
Mandel                                                 3
Almindelig Netbladhat                                  3
Thuja                                                  2
Guldregn                                               2
Galnebær                                               2
Hestebønne                                             2
ukendt insekt                                          2
Sort Natskygge                                         2
Hyld                                                   2
Pigæble                                                2
hallucinogene svampe                                   2
Cypres-Vortemælk                                       2
Cowboykaktus                                           2
Grøn Fluesvamp                                         2
Rød Fluesvamp                                          2
Processionsspinder                                     2
Levende pind                                           2
Pragtsnerle                                            2
Amanita muscaria                                       2
Sambucus nigra                                         2
Myresyre                                               2
Ricinus communis                                       2
Olieplante                                             2
Coprinus atramentarius                                 2
Ukendt stik i hud                                      1
Madagascar jewel                                       1
Kantareller                                            1
Perikon                                                1
Brændenælde                                            1
Syre, rusmiddel ukendt                                 1
Botulismus                                             1
Karbol champignon                                      1
Svampe - the Hawaii                                    1
Svampe/ rusmiddel                                      1
Svampe/Hallucinogene                                   1
alm mandel                                             1
Shiitake svamp                                         1
Baldrian kapsler                                       1
Brændenælde pressejuice                                1
Calman                                                 1
lavendel                                               1
Svampe - paryk                                         1
Syrekoncentrat                                         1
Gifttyde ekstrat                                       1
Rabarberblade                                          1
Lemur                                                  1
Abrikos mandler                                        1
Processionslarve                                       1
sommerfugle larve                                      1
Weber multiclean 30                                    1
Slåen mjød                                             1
Tragt Kantarel                                         1
Golden Teacher, svampe                                 1
Svampe hallucinogene                                   1
Artemisia absinthium                                   1
Fiskeaffald                                            1
kristi tornekrone                                      1
Baldrian tabletter                                     1
Hibiskus                                               1
Amaryllis                                              1
Abrikoskerner                                          1
Svampe - Orissa India                                  1
Pascoflair                                             1
Capsaicin Essex creme                                  1
Longo Skøn                                             1
Mistelten                                              1
Coral/ Palytoxin                                       1
abrikoskerner                                          1
hallucinogene svamp                                    1
pinto Bønner                                           1
svampe/Spids Nøgenhat                                  1
Squash                                                 1
Life stock acid                                        1
Morning Glory                                          1
sommerfuglelarve                                       1
Julerose extrakt                                       1
Almindelig Blækhat                                     1
Glansbladet Hæg                                        1
Ricin                                                  1
Ricinus                                                1
Hallucinogene svampe                                   1
Botulismus/madforgiftnig                               1
 Hawaiianske svampe                                    1
Salix Alba, pasiflora incarnata, crataegus oxyacan     1
Snebær                                                 1
kapsler                                                1
ukendt                                                 1
pilea                                                  1
Påskelilje løg                                         1
fingeralger                                            1
Robinie                                                1
 Femiplus                                              1
cambodianske mushrooms                                 1
trævlhat [måske]                                       1
Svampe - ukendte (2 stk)                               1
 Mexicanske svampe                                     1
Hveps død                                              1
Kantarel                                               1
Rødkløver ekstrakt                                     1
grøn fluesvamp                                         1
Bistk                                                  1
Tarpon fisk                                            1
Vortemiddel, Vortefri                                  1
ukendt hallucinogen svampe                             1
Trævlhat                                               1
Plettet Dieffenbachia                                  1
Sild                                                   1
Violin-Figen                                           1
Shiitake svampe                                        1
Paternoster-Bønne                                      1
Ukendt plante. andet?                                  1
Panaeolus                                              1
Læge-Baldrian m Humle                                  1
Fingerbøl frø                                          1
Edderkop                                               1
ukendt gren                                            1
Skvalderkål/Bingelurt                                  1
Portobellosvampe                                       1
Psilicybin svampe                                      1
Ukendt                                                 1
Skorpion                                               1
Kirsebærsten                                           1
recinus communis                                       1
Lupin-frø                                              1
Snehvid Fluesvamp                                      1
grønt bær                                              1
Hvid Fluesvamp                                         1
Rørhatte                                               1
Æblekerner                                             1
Bøg - bog                                              1
Betel nødder                                           1
Grøn Fluesvamp ?                                       1
Svampe - gastrointestinale ?irritanter                 1
Hugorm/Regnorm                                         1
Mexican mushroom                                       1
Skarntyde                                              1
Salvie                                                 1
Glanshatte                                             1
 Symphoricarpos albus                                  1
Amanita virosa                                         1
Randbæltet hjelmhat                                    1
hallcinogene svampe                                    1
Russula                                                1
 Proto Bothrops Cornutus                               1
Svampe                                                 1
Hydrangea macrophylla                                  1
Passiflora, passionsblomst                             1
måske Psilocybe semilanceata                           1
Agerpadderokke                                         1
euphorbia tiruculli                                    1
vorterod                                               1
Agarius xanthoderma                                    1
abrikos kerner                                         1
Rensevæske                                             1
orthophosphorsyre semilanceata                         1
Røllike                                                1
Elledans bruskhat                                      1
Alm netblad hat                                        1
Kaktus                                                 1
Syre                                                   1
Brombærspinder                                         1
Gifttyde måske                                         1
Colchicin lægemiddel                                   1
Svampe ukendte                                         1
Tryne Snog                                             1
Mckenniae, Cubanesis                                   1
Hallucinogene svampe -                                 1
Slåen                                                  1
Bi hveps                                               1
Rabarber Blade                                         1
bjørneklo                                              1
Strand kål                                             1
Svampe købt på nettet                                  1
hasselnød                                              1
Hortensia                                              1
Gedehams/bi                                            1
Perikon, bær                                           1
 Processionsspinder                                    1
Insekt                                                 1
Magic Mushrooms                                        1
Nerie                                                  1
stok Rose                                              1
Skade- Blækhat                                         1
Mexikanske svampe                                      1
Grape                                                  1
Svampe - ukendte, brune lamel                          1
Golden Teacher mushroom                                1
Nellike, krydderi                                      1
Pieris                                                 1
Ukendt plante                                          1
Te på Taks, hakket                                     1
Diktam                                                 1
Blå bær                                                1
Vortefri                                               1
Ukendt antikolinerge planter                           1
larve                                                  1
mirabella                                              1
Ukendt svamp Helt Hvid                                 1
Engletrompet                                           1
Natskygge bittersød                                    1
Gedehams                                               1
Larve                                                  1
Skørhatte                                              1
 Asiatisk hugorm                                       1
Tryptonat m Baldrian                                   1
Tranebær-extrat                                        1
Name: count, dtype: int64

=== Alder>70 Combined unique values ([generisk navn] and [navn]), counted: ===

Apis mellifera                         5
Hveps                                  5
Echiichtys draco                       4
Fjæsing                                4
Læge-Baldrian                          3
Hugorm                                 3
Vipera berus                           3
Svampe - ukendte                       3
Høst-Tidløs                            2
Perikon                                2
Bitter mandel                          2
hveps                                  2
Paravespula vulgaris                   2
Blågrøn alger                          1
Bi                                     1
Ukendt svamp                           1
Skorpet søanemone                      1
Guldregn                               1
skærmplante                            1
Kæmpe støvbold                         1
Mandel                                 1
Svampe - symptomer                     1
Tryptonat                              1
Asters                                 1
Nerie                                  1
rBitter mandel                         1
Bjørneklo                              1
Velzina Perikon                        1
kirsebærsaft/rom                       1
Svampe - ukendte                       1
Puklet Giftslørhat                     1
Almindelig Netbladhat                  1
Bi stik                                1
Humlebi                                1
Taks                                   1
Artemisia absinthium, egen blanding    1
Grapefrugt                             1
baldrian                               1
Hypericumperforatum                    1
Cortinarius rubellus                   1
Paxillus involutus                     1
Dahlia                                 1
Name: count, dtype: int64

In [12]:
# We have manually verified that the above list contains only BIO-substances.
# There is not a significant amount of medicine that has been miscategorized as BIO.

In [13]:
# #ToDo:
# # combine all the 'årsag' 

# Filter out the non-medicine related rows from the categories below.
#x AMED: 4
#x BIO: 22795
# DIVERSE: 14213
# KEMI: 51993
# MED: 51811
# RUS: 10893
# SPECIALDONOTDELETE: 8010 
# ZZMED: 29477
#Visit each type and convert to MED as appropriate

#Filter all the MED to see if there are non-medicine items (count them)

#x  Next step is: import data from official lists to create list of medications.
#https://laegemiddelstyrelsen.dk/da/godkendelse/godkendelse-af-medicin/lister-over-godkendte-og-afregistrerede-laegemidler/saadan-bruger-du-listen-over-afregistrerede-laegemidler/
#https://laegemiddelstyrelsen.dk/da/godkendelse/godkendelse-af-medicin/lister-over-godkendte-og-afregistrerede-laegemidler/saadan-bruger-du-listen-over-godkendte-laegemidler/


#remember when searching and filtering to search the WHOLE cell, as there can be multiple words separated by a comma in one cell (ANY match - keep everything lowercase)